### ISSUE TITLE
Allow to disable automated discovery of other comit nodes

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1007]
With the addition of #883 in #1002, it is possible to send swap requests to other nodes without discovering them first.

As pointed out by @D4nte [here](https://github.com/comit-network/comit-rs/pull/1002#discussion_r289666782), it would be good to disable discovery in order to test this properly.

- broadcast peerID via mDNS should be opt-in
- broadcast peerID via DHT should be opt-in
- answering DHT queries should be opt-in
- the comit_node should actively make DHT queries to find other nodes

DoD:
- Discovery can be disabled _in some way_
- The test in `dry/rfc003_swap_with_ip.ts` no longer relies on the fact that the Alice cannot discover herself
- configuration file: 
  - [network.discoverable] = true or false #automatically enables mDNS and DHT

**Comment by thomaseizinger** [comment]
This proposal actually has a flaw.
Consider the following scenario:

- comit_node A has `discoverable` set to `false`
- comit_node A sends a swap request to comit_node B
- comit_node B learns the PeerID + public IP address from comit_node A

comit_node B can now put comit_node A's PeerID and public IP into the DHT or/and answer other queries from other nodes about an IP address of comit_node A.

We simply cannot prevent leaking an IP address to other nodes if we are talking to them, hence naming the feature `discoverable` seems wrong and actually does __not__ describe what the flag is controlling.

A more descriptive name would communicate something like "no active broadcasting" since that is the only thing that is disabled by setting the flag to false.

Also note that just because another node learns the IP address of a node, it doesn't mean that it can connect to it. If the node is behind a NAT, that is still not possible.

Since privacy is a sensitive topic, we should really be careful about the language that we are using here so that users understand, what these configuration options are doing.

**Comment by D4nte** [comment]
Moved to "New issues" due to the insight above.

**Comment by thomaseizinger** [comment]
Closed because we won't have a DHT anytime soon.
