### ISSUE TITLE
Find better terminology for a the initial ledger state

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1011]
When a swap is started, the Ledger state is `NotDeployed`:

https://github.com/comit-network/comit-rs/blob/020171506f8cdfad5014abee42eed92a4469e9d3/application/comit_node/src/swap_protocols/rfc003/ledger_state.rs#L11

This only makes sense if the ledger is Ethereum as nothing get "deployed" on Bitcoin.

A better name should be found and implemented. Proposals:
- "Initial"
- "Start"

**Comment by luckysori** [comment]
"HtlcNotReady"?

**Comment by D4nte** [comment]
"NopeDoneYet"
"WaitingForGodot"

**Comment by thomaseizinger** [comment]
Closed because no consensus reached and not that important.
