### ISSUE TITLE
Don't use the rebase strategy in mergify

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1018]
Reconfigure mergify to use merge instead of rebase strategy.

Reason: Rebase destroys the signature of signed commits.

**Comment by D4nte** [comment]
> Rebasing destroys the signature of signed commits.

What is the downside?

**Comment by thomaseizinger** [comment]
> What is the downside?

Commits that used to be signed are no longer signed.

**Comment by thomaseizinger** [comment]
Also, the rebasing adds quite some noise to the history of a PR. For example, it always references you (@D4nte) in other issues if one of the commits references an issue as in:

"@D4nte references this issue in PR #abc". Even though the original author was someone else.

**Comment by D4nte** [comment]
I have no strong opinion on the matter.

**Comment by bonomat** [comment]
I always was pro merge because of the mentioned reasons: 
* rebasing can be cumbersome 
* you might end up with a non working versions due to merge mistakes
* it changes commit hashes 
* it is a bit annoying in PRs
