### ISSUE TITLE
beta-ledger is reported as `NotDeployed` if alpha-ledger is refunded even though it was previously funded

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1026]
The comit_node REST API returns `NotDeployed` for BetaLedger when AlphaLedger is funded and then refunded. This was observed for Alice (need to check Bob)

1. Alpha is Funded
2. Beta is Funded
3. Refund alpha -> Beta shows as `NotDeployed`, it should show as `Funded`

Beta should be refunded first.

DoD:
- [ ] Create failing test for Alice (checks that beta is `Funded` after alpha refund)
- [ ] Create test for Bob to confirm that beta is `Funded` after alpha refund and ensure refund action is returned
- [ ] Fix the tests

**Comment by tcharding** [comment]
Looks like this issue is invalid.  A PR wast still opened in response to this issue:  #1088.
