### ISSUE TITLE
Fail the test suite if a local comit node is already running and the one to be tested was not able to bind to the port

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1036]
Currently, if the `comit_node` started by the test suite cannot bind to the local port, the test suite continues and test against the already running node.

Instead, the test suite should fail when starting `comit_node` to prompt the user to stop any other comit_node (or btsieve) running on the local machine.

Note, the comit_node may not die if it cannot bind to ipv4 localhost (due to libp2p it would bind to ipv6 localhost and be happy).

Ways to proceed :
1. Modify comit_node to figure out whether you could not bind and die, e2e test can check that comit_node is still alive
If 1. is not possible:
2. Check before starting the comit_node
3. Check logs after starting comit_node

**Comment by tcharding** [comment]
After exploration of this issue I believe that this issues is not correct

> Currently, if the comit_node started by the test suite cannot bind to the local port, the test suite continues and test against the already running node.

If one runs `target/debug/comit_node` and then runs ` cargo make e2e` we get
```
Starting comit node for alice, bob
{ Error: connect ECONNREFUSED 127.0.0.1:8010
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8010,
  response: undefined }
cleaning up
Stopping Btsieve(s): main
Stopping comit nodes: alice, bob
Stopping ledgers: bitcoin, ethereum
Stopping regtest_eth_1 ... done
Stopping regtest_btc_1 ... done
Removing regtest_eth_1 ... done
Removing regtest_btc_1 ... done
Removing network regtest_default
cleanup done
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```
And the same for `make cargo dry`
```
[cargo-make] INFO - Running Task: dry-tests
Starting comit node for alice, bob, charlie
{ Error: connect ECONNREFUSED 127.0.0.1:8010
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8010,
  response: undefined }
cleaning up
Stopping comit nodes: alice, bob, charlie
cleanup done
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```

**Comment by tcharding** [comment]
@thomaseizinger am I missing something?

**Comment by thomaseizinger** [comment]
Interesting, seems to be fixed then :)

**Comment by tcharding** [comment]
PROFIT!

**Comment by thomaseizinger** [comment]
> PROFIT!

@tcharding https://www.youtube.com/watch?v=tO5sxLapAts ?
