### ISSUE TITLE
Events in COMIT should have timestamps

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#1044]
This just came up in a discussion: 
Events should have timestamps, e.g.:

* When was a swap request sent?
* When was the swap request accepted?
* When was it funded or even when was the funding transaction broadcasted?
* When was it redeemed or even when was the redeeming transaction broadcasted?
* When was it refunded?

DoD:
- [ ] Define above timestamps (spike part)
- [ ] Create issue(s) to make comit-rs/comit-i compliant

Note: think about timestamp spoofing/corruption

Further Description (cut'n'pasted from https://github.com/comit-network/spikes/pull/19#issuecomment-510279784):

The aim of the timestamp is for the client to have an idea of the order of events and have the information. This would allow comit-i to display the events in the right order or it could allow a trading bot to analysis how much time a given peer is taking to do his part of a swap (ie, if a given peer is always taking a long time then he is likely to be using the option and hence the trading bot may decide to take action against this specific peer).

There is no possible "spoofing" in this scenario as we currently always assume that a client can trust its COMIT node.

As a base assumption for this spike, I would not expect comit_node to get any timestamp from another COMIT node. As you said, the comit_node should either make a timestamp by registering when a message arrives/is sent (from another COMIT node) or looking at the blockchain messages.

For this spike I'd expect to have the list of events, (swap request sent, acceptance of swap received, decline of swap received, transaction on blockchain seen/etc) and for each event have a list of the possible timestamps (ie, timestamp of when a message was sent vs timestamp of the transaction vs timestamp of the block etc) with a declaration of the risk for each (e.g., using timestamp of the block gives a precision of 10min etc).

**Comment by bonomat** [comment]
Related to comit-network/comit-i#98

**Comment by D4nte** [comment]
Please note there is 2 kind of timestamps to be considered when grooming this:
- when comit_node "learns"
- the timestamp native to a blockchain event

**Comment by D4nte** [comment]
Not sure why I closed that.  I must have Zenhub'd it.
