### ISSUE TITLE
Decide on releasing strategy for comit_node

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1050]
Decide on a release strategy for comit_node. Make sure to cover the following questions:

- Define versioning strategy until ready for mainnet (what is version 1.0.0?)
- What is the frequency of releases? What is the trigger? (Fixed time vs. feature)
- What does the technical process of "doing a release" look like? List all steps necessary that need to be done.
- Define release-"naming" strategy
- Cover major vs minor vs patch (what are we versioning? HTTP API vs COMIT-messages vs CLI interface)

Post-1.0.0 discussions like maintenance window and bug-fix releases are out of scope.

Post-merge task of the spike document:
- Create the first release!
- If OSX release is included do a swap between two machines, one running Linux one running OSX.

**Comment by tcharding** [comment]
From Cargo book, might be useful knowledge for this issue:
```
- Before you reach 1.0.0, anything goes, but if you make breaking changes, increment the minor version. In Rust, breaking changes include adding fields to structs or variants to enums.
- After 1.0.0, only make breaking changes when you increment the major version. Don’t break the build.
- After 1.0.0, don’t add any new public API (no new pub anything) in patch-level versions. Always increment the minor version if you add any new pub structs, traits, fields, types, functions, methods or anything else.
- Use version numbers with three numeric parts such as 1.0.0 rather than 1.0.
```

**Comment by D4nte** [comment]
- Consider including a run of e2e tests against all `--release` binaries (linux and mac) before releasing
- Consider getting latest comit-i before releasing

**Comment by D4nte** [comment]
I am defining the scope as follow:

```Scope:

 - comit-rs repo (cnd and btsieve)
 - comit-i repo

Out of scope:

- Maintenance window/versions that are supported
- What would happen if btsieve/cnd become libraries
```

**Comment by D4nte** [comment]
> From Cargo book, might be useful knowledge for this issue:
> 
> ```
> - Before you reach 1.0.0, anything goes, but if you make breaking changes, increment the minor version. In Rust, breaking changes include adding fields to structs or variants to enums.
> - After 1.0.0, only make breaking changes when you increment the major version. Don’t break the build.
> - After 1.0.0, don’t add any new public API (no new pub anything) in patch-level versions. Always increment the minor version if you add any new pub structs, traits, fields, types, functions, methods or anything else.
> - Use version numbers with three numeric parts such as 1.0.0 rather than 1.0.
> ```

Do you have a link please?

**Comment by D4nte** [comment]
== Scope

Scope:

 - comit-rs repo (cnd and btsieve)
 - comit-i repo

Out of scope:

- Maintenance window/versions that are supported
- What would happen if btsieve/cnd become libraries

== Considerations

- What triggers a release publication? e.g.:
  - Time frequency (monthly, etc)
  - Major feature (OKR achievement, accumulation of features)
  - Breaking change (on http api, comit api, CLI interface, internal API such as btsieve http api)
  - Bug fixed (all bugs, only security bugs)
  - Embed new comit-i version
- What triggers a major/minor/patch version increment? e.g.:
  - COMIT protocol breaking change
  - HTTP API breaking change
  - Embedded comit-i version upgrade
  - security bugs
  - "major features"
- What validation should be do before releasing? e.g.:
  - No added validatio
  - Run release binaries against e2e test suite
  - Run other platforms (not supported by CI such as Mac OS or Windows) against e2e test suite
  - Embed (release) latest comit-i
  - comit-i/comit-rs full compatibility (manual or automated checks)
  - do a testnet swap
  - Valgrind/memory/performance run
- Versioning phases
  - No phase, start at 1.0.0 and increment from there
  - Two phases versioning: Alpha/Beta then stable (start at 0.1.0, Keep 0.Y.Z until considered stable and it becomes 1.0.0)
- If versioning phases, What is the trigger for 1.0.0?
  - When it is mainnet ready?
- Release naming? (Ubuntu style)
- Crate publication?
- Rust practices
- Release early, release often motto

**Comment by tcharding** [comment]
> Versioning phases
> * No phase, start at 1.0.0 and increment from there

I like this - we can handle it.  Drop v1.0.0 as the first release @D4nte

**Comment by tcharding** [comment]
> If versioning phases, What is the trigger for 1.0.0?
> * When it is mainnet ready?

Perhaps when we decide its mainnet ready we just advertise vX.Y.Z is mainnet ready!

**Comment by tcharding** [comment]
> Release naming? (Ubuntu style)

I vote no names, just the number X.Y.Z
The Linux kernel has no names and no one has ever missed them.

**Comment by tcharding** [comment]
> Crate publication?

I think we should consider the extra work involved with having a post 1.0.0 crate on crates.io vs the advantage.  I don't see any advantage to publishing before we are mainnet ready.  We definitely should publish crates as we pull them out of cnd though IMO.

**Comment by tcharding** [comment]
Thanks
