### ISSUE TITLE
Add logging so we can see the BAM messages as they go on/off the wire

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#1056]
## Problem

libp2p encrypts the traffic between the two peer cnds.  This is good for security but makes debugging the messages impossible.  

## Aim

Be able to log what messages are being sent over the wire.  

## Idea

One simple solution is just to log each outgoing message before we send it to libp2p and each incoming message when we get it from libp2p.

**Comment by D4nte** [comment]
The right way to do check boxes is `- [ ]` :)

**Comment by thomaseizinger** [comment]
I think this might already be (partially) in place. Did you enable the `sub-libp2p` log target in the logger configuration for the right level? (I think it is TRACE)

**Comment by tcharding** [comment]
> I think this might already be (partially) in place. Did you enable the sub-libp2p log target in the logger configuration for the right level? (I think it is TRACE)

Thanks, will check this out and post my findings.

**Comment by thomaseizinger** [comment]
@tcharding you might want to add the `feels good` label to this if you care enough :D

**Comment by thomaseizinger** [comment]
Closed because of inactivity.
