### ISSUE TITLE
Detect missing blocks (i.e. model the blockchain)

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1063]
Motivation:
According to https://github.com/bitcoin/bitcoin/blob/master/doc/zmq.md, it is possible to miss blocks from ZMQ.
Moreover, if btsieve crashes and recovery is done (see #1062) then it is likely that blocks would be missed on Ethereum or Bitcoin.

Task:
For Bitcoin & Ethereum, btsieve should realise that blocks are missing in the sequence. For now, we only want to log a message when a missing block is detected.

To achieve that, we want to introduce a component (that implies designing an API :) ) that:
- stores incoming blocks
- verifies that you have the previous block (issue a warning if that is not the case)
- still processes the block as we do now

Only keep the latest 6 blocks for Bitcoin, 200 for Ethereum (1 hour)

Only use the stored chain to ensure blocks are not missed, features on top of this such as "confirmations" should be done later.

DoD:
- [ ] Do it for Bitcoin
- [ ] Create issue for Ethereum

**Comment by thomaseizinger** [comment]
Instead of just retrieving missing blocks, maybe we should start modelling the blockchain (without PoW validation for the beginning) but just so that we actually _know_ which blocks are missing?

This would also allow us to drop `zmq` as a dependency and make btsieve more generic.
As a result, we can build several adaptors for fetching blocks:

1. JsonRPC
2. layer1
3. blockchain.com API

**Comment by D4nte** [comment]
Pushed back to new to shortly discuss @thomaseizinger's point

**Comment by bonomat** [comment]
One thing I was just thinking of is that if we clearly keep separation of concerns, we could allow building arbitrary connectors:
* get blocks using web3
* get blocks from etherscan
* get blocks from ledgerlive: e.g.
https://explorers.api.live.ledger.com/blockchain/v2/eth/blocks/0xc0279b832620e0eb7b942bb920699d093db5e381e9d3b7ef230764c4559b21c8

**Comment by da-kami** [comment]
I'm keen on working on that  - who would like to to pair programming?
