### ISSUE TITLE
Expose State Machine failures to the REST API

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1064]
When the state machine goes to `Swap::Error`, relevant information should be available on comit_node REST API.

DoD:
- [ ] Expose the `rfc003::Error` on the REST API of comit_node
- [ ] Check the possible error cases and ensure that there is enough meaningful information for us (CoBloX) to understand the possible root cause of the issue if a user reports it

**Comment by thomaseizinger** [comment]
Still relevant but we are going a different approach now:

We will bubble up all the errors and exposing them later once we are more confident what the actual issues are.
