### ISSUE TITLE
Rename `comit_node` to `cnd`

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1072]
Rename the `comit_node` Rust binary to `cnd`.

DoD:
- [x] Make sure the README is up to date
- [ ] Send a reminder to everyone to now use `cnd` in issues
- [ ] Update the end-to-end tests (JS code and log messages)
- [x] Full-text search for "comit_node" and "comit-node" must be 0 hits

Kept for historical purposes:

Currently, we refer to our node usually as `comit_node` or `comit-rs`.

It would be good if we can find a name that:
- is universally applicable (no binary-name clash with popular tools)
- short (easier to type on the command line)
- descriptive (should be easy to remember)

The reason I am unhappy with the current situation is mostly because it is not a very creative name and I don't like the underscore in there.

Suggestions: (feel free to add your own if something comes to your mind)

- `cnd`: Short for "comit network daemon".
I am not aware of any name clashes with other binaries (apart from `cmd` on windows). It is heavily inspired by "lnd" which means "lightning network daemon", hence the community should have an easy time remembering that since we follow the same naming scheme.

**Comment by D4nte** [comment]
* `rcomit`

**Comment by thomaseizinger** [comment]
> I would like to keep `comit-rs`

I'll try to expand a bit more on why I think there is an issue.

At the moment, only the repository is called `comit-rs`, the node is called `comit_node`. That is the inconsistency that I would like to clean up.

The problem with the current situation is that it is ambiguous and regularly causes confusion in meetings & issue descriptions. Even you yourself had to recently say "with `comit-rs`, we mean all the components needed to run COMIT" :)

Hence, I'd advocate for a clear 1-to-1 mapping between repository name and the name of the binary for our COMIT node. Since `btsieve` will eventually be moved out of the repository or the code be inlined into `comit_node` again, having that one in there is not an issue to me, especially once #626 is resolved.

**Comment by D4nte** [comment]
I am ok with `comit_node` to be called `comit-rs`.

**Comment by thomaseizinger** [comment]
> I am ok with `comit_node` to be called `comit-rs`.

I find that to be a very unconventional and ugly name for a binary :(

1. binary names are usually short
2. they rarely include the _language_ they are written in (as a user, you don't care)
3. dashes/underscore are also pretty rare

**Comment by D4nte** [comment]
And I find that quite pretty 🌷
