### ISSUE TITLE
Store config file in a path based on platform conventions

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1074]
During the workshop, I received the feedback that we are statically assuming the user's desired folder for config files is `.config` whereas at least under (most?) Linux distributions, that is controlled through the `$XDG_CONFIG_HOME` environment variable.

Make use of `directories-rs` which is specifically designed to solve this problem cross-platform: https://github.com/soc/directories-rs#projectdirs

Tasks:
- Use `directories-rs` to resolve the config folder for 
  - `btsieve` - done in: comit-network/comit-rs#1236 
  - `comit_node` - done in: comit-network/comit-rs#1242
- Print a log message of where the config file is loaded from (no matter if path was overridden through `--config` or the default path was used)

**Comment by D4nte** [comment]
As I previously stated I disagree with the use of `.config` folder.
This folder only contains my comit and yarn config files (a strange combination).

On Mac Os, everyone uses the `Library Support` folder, even the Lightning Labs apps and Bitcoin-QT!

I am strongly in favour of using `directories-rs`.
