### ISSUE TITLE
cnd refund availability

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#1075]
## Problem

cnd makes refund available as action even before the expiry timestamp is reached. 

## Goal

Applications on top of COMIT don't have to deal with the time calculation when refund is available, but cnd does that for the application.

## Proposal 

The cnd REST API _hides_ the `refund` action if it is not available yet due to time constraints. 
The state machine does still emit that redeem and refund is available, but the HTTP interface does not emit the refund action until the expiry is reached. It should still be possible to retrieve the refund action through the API before the expiry time is reached, but it would not be returned by default.

The solution is to retrieve the current network time through btsieve which gets it from block stored in the internal DAG.

Note: due to the missing confirmation feature on btsieve, this solution is not perfect. If btsieve is aware of a block before the node to which comit-i/bobtimus is connected to then comit-i/bobtimus refund transaction may be rejected.

**Comment by thomaseizinger** [comment]
Needs refinement after btsieve refactoring.

**Comment by tcharding** [comment]
Seems one cannot connect to a draft PR.  [This PR](https://github.com/comit-network/comit-rs/pull/1755) potentially resolves this (needs testing).

**Comment by thomaseizinger** [comment]
Removing `no-activity` because I think this is still something quite important to do but just not yet.
