### ISSUE TITLE
Duplicate code for configuring `btsieve` and `comit_node`

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#1081]
Currently `comit_node` and `btsieve` each handle their own configuration i.e. they both load settings from a config file specific to the service.  There is duplicate code between the two services because of this e.g. `comit_node/src/load_settings.rs:load_settings()`.  This issue is deeper than just duplicate code; the configuration of `btsieve` and `comit_node` are dependent on each other i.e. setting the listen port in `btsieve` requires setting the same port number in `comit_node` within `btsieve_url`.  Since there is a dependency we should handle the configuration in a single place.  This would make configuring COMIT easier and enable removal of duplicate code.

**Comment by D4nte** [comment]
I would tend not to agree as ultimately `btsieve` should go in its own repo and I must say I am hoping it happens this quarter depending on the direction we take.

**Comment by thomaseizinger** [comment]
Closed because:
1. The separation is actually be design
2. We hope to remove `btsieve` from the repository at some point
3. We'd rather have some code duplication instead of the coupling that is created by a unified config solution
