### ISSUE TITLE
Use CircleCI orbs for custom slack messages that mention user names

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1098]
Currently, we get slack notifications to a slack channel every time the build fails. Unfortunately, these messages don't tag the relevant person in Slack but only mention the Github username.

Using the CircleCI slack orb, we can implement a [`status`](https://circleci.com/orbs/registry/orb/circleci/slack#commands-status) command that mentions the correct user based on the commit that failed the build.

**Comment by bonomat** [comment]
Closing this as we hardly use these notifications.
