### ISSUE TITLE
Should cnd expose public address?

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#1109]
Currently cnd exposes its metadata on `http://localhost:<port>/`, i.e.: 
```
{
  "id": "QmYaEdADq9nZqNWLUXtMP9tnfjLKrwjMBuVSSNyPz2wLLd",
  "listen_addresses": [
    "/ip4/127.0.0.1/tcp/8011",
    "/ip6/::1/tcp/8011",
    "/ip4/192.168.1.36/tcp/8011"
  ]
}
```

However, these addresses are only locally available which is a problem if run in the cloud as cnd does not know its public IP.  

Should cnd be able to expose its public address?

**Comment by thomaseizinger** [comment]
For documentation purposes:

`libp2p` exposes a way of how nodes can identify their external address: the `identify` protocol.
However, a pre-condition for that is that at least one other node was able to connect so that it can report the externally observed address.

**Comment by D4nte** [comment]
To help with the conversation, several ways to move forward:

1. implemented `identify` protocol as per @thomaseizinger's [comment](https://github.com/comit-network/comit-rs/issues/1109#issuecomment-512655169)

### To resolve IP
2. Add a `external_ip` field to the config file to allow user to configure
3. Use external service to automatically discover ip (usually via an HTTP GET)

### To resolve port
4. Add a `external_port` field to the config file to allow user to configure
5. Always assume that the same port is used locally and through the NAT
6. Use UPnP magic features (need more research, I am not too verse in this)

**Comment by thomaseizinger** [comment]
Closed because we agreed that `cnd` doesn't need to expose its external IP atm. Should be implemented in clients like `bobtimus` etc.
