### ISSUE TITLE
Flaky e2e tests tracking issue

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1119]
Issue for collecting data on why e2e tests failed seemingly random.

- Bitcoin for Ether, Alice doesn't see redeem action: (i.e. she didn't transition to correct state -> didn't see Bob's Ethereum funding): https://circleci.com/gh/comit-network/comit-rs/659
- Connection refused to `127.0.0.1:8000`: https://circleci.com/gh/comit-network/comit-rs/768
- RFC003: Bitcoin for ERC20 - ERC20 (beta) refunded to Bob -> [bob] transitions to correct state: Timeout
   - https://circleci.com/gh/comit-network/comit-rs/1152
   - https://circleci.com/gh/comit-network/comit-rs/1507
   - https://circleci.com/gh/comit-network/comit-rs/1644
   - https://circleci.com/gh/comit-network/comit-rs/1701
---

- ~btsieve, bitcoin block height query:~
   - ~https://circleci.com/gh/comit-network/comit-rs/667~
   - ~https://circleci.com/gh/comit-network/comit-rs/972~
   - ~https://circleci.com/gh/comit-network/comit-rs/1010~
   - ~https://circleci.com/gh/comit-network/comit-rs/1103~
   - ~https://circleci.com/gh/comit-network/comit-rs/1103~
   - **Block height queries were removed in https://circleci.com/gh/comit-network/comit-rs/1507**
- ~btsieve, ethereum block height query:~
   - ~https://circleci.com/gh/comit-network/comit-rs/989~
   - ~https://circleci.com/gh/comit-network/comit-rs/1099~
   - ~https://circleci.com/gh/comit-network/comit-rs/1108~
   - **Block height queries were removed in https://circleci.com/gh/comit-network/comit-rs/1507**
- ~ERC20 for Bitcoin - Bob did not see the fund action:~
   - ~https://circleci.com/gh/comit-network/comit-rs/676~
   - ~7 more of this one~
   - **Dedicated issue created here: https://github.com/comit-network/comit-rs/issues/1232**

**Comment by thomaseizinger** [comment]
Created separate ticket for the "apt-lock" problem because it is unrelated to the e2e tests but a general CI issue: https://github.com/comit-network/comit-rs/issues/1231

**Comment by D4nte** [comment]
There are still issue with the ERC20 scenario

**Comment by thomaseizinger** [comment]
@d4nte

Yes correct. Please note that everything above the line is not resolved. There are only issues/fixes for the issues reported below the horizontal line.

**Comment by D4nte** [comment]
I thought @luckysori tried to fix the ERC20 issue.

**Comment by thomaseizinger** [comment]
AFAIK, he only focused on one particular test. Not sure if the failures of the other tests are related to the same problem (maybe we just need a longer sleep? 😅)

**Comment by da-kami** [comment]
Assumption is, that the E2E tests are not flaky any more after we replace the `.wait()` btsieve behaviour for retrieving transaction data by transactions-hash by using `Future`s instead.
In case flakyness still appears, please track in new ticket!
