### ISSUE TITLE
Lightclient

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1129]
## Thoughts that have not yet been converted into issues:

- how does a user choose between implementations of `BlockSource` (config vs compile-time flag)

## Btsieve as a library

We want to re-design the state machine first.
The re-design will also help with https://github.com/comit-network/comit-rs/issues/1061

## Move btsieve to its own repository

- Is easier after the lib interface stabilizes
- Probably needs `vendor/` to be gone (https://github.com/comit-network/comit-rs/issues/626)

**Comment by D4nte** [comment]
I am not sure it makes sense to have new Epic and I would suggest to track this under an existing OKR Epic.

**Comment by thomaseizinger** [comment]
I would consider this to be done.
