### ISSUE TITLE
Replace `zmq` with `BlockSource` implementation for HTTP API of bitcoind

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1131]
Goal of the implementation:
We no longer use zmq but HTTP API to get blocks.

Consider doing https://github.com/comit-network/comit-rs/issues/1348 at the same time / before because it might make your life easier.

**Comment by da-kami** [comment]
Get latest block:

* latest block hash: https://github.com/bitcoin/bitcoin/blob/master/doc/REST-interface.md#chaininfos - use `bestblockhash`
* block by hash: https://github.com/bitcoin/bitcoin/blob/master/doc/REST-interface.md#blocks - use `hex` format and directly deserialise into `Block`
