### ISSUE TITLE
Can we cross-compile cnd for MacOS in our CircleCI build?

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1133]
1. Start with trying to compile on a local Linux machine
2. If you manage to create a binary, give it to a Mac person and run e2e tests
3. Try to replicate build on CircleCI
4. Test the binary created on CircleCI on one of our Mac computers

If all steps are successful, create a `--release` build on every release analogues to https://github.com/comit-network/comit-rs/issues/1121.

**Comment by bonomat** [comment]
@D4nte : you did some investigation on this already right? What was the outcome?

**Comment by D4nte** [comment]
Nothing done for this :)

**Comment by bonomat** [comment]
Closing this as too low priority.
