### ISSUE TITLE
Use siren for ledger actions

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1134]

**Comment by thomaseizinger** [comment]
I assume you are talking about the _response_ of a ledger action? What is added benefit of modelling them as a Siren entity (that is what expressing them through Siren is doing)?

None of the ledger actions instruct the client to do additional communication with `cnd` so the `actions` will always be an empty array. In fact, that is why we refer to them as _ledger_ actions: they need to be executed against a ledger and not against `cnd`.

In other words, how is this:

```json
{
  "class": [ "action" ],
  "properties": {
	  "type": "bitcoin-send-amount-to-address",
	  "payload": { 
	  	"to": "bcrt1qs2aderg3whgu0m8uadn6dwxjf7j3wx97kk2qqtrum89pmfcxknhsf89pj0",
	  	"amount": "10000000000000",
	  	"network": "mainnet"
	  }
  },
  "entities": [],
  "actions": [],
  "links": []
}
```

superior to this:

```json
{
  "type": "bitcoin-send-amount-to-address",
  "payload": { 
  	"to": "bcrt1qs2aderg3whgu0m8uadn6dwxjf7j3wx97kk2qqtrum89pmfcxknhsf89pj0",
  	"amount": "10000000000000",
  	"network": "mainnet"
  }
}
```

I think that you may want to answer the question: "How do clients know _what_ they have to do with the response of a siren action?" The answer to that is "look at the `Content-Type` header". That one in our case is only `application/json` and hence doesn't provide any information to the client. Instead, we should be stating a mediatype here, that allows the client to identify, that the payload of a response is in fact a ledger action. There is already a ticket for this here: https://github.com/comit-network/comit-rs/issues/992

**Comment by D4nte** [comment]
The current payload and proposed payload of #992 does not resolve the issue around the way the expiry information is dealt with. Need to think and revisit.
