### ISSUE TITLE
Infer `bitcoind` `.cookie` file path and port from network

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#1137]
This is an extension of https://github.com/comit-network/comit-rs/issues/1105 

The goal is to reduce the configuration options that you need to supply for btsieve in the best case.
Given the `network` we should be able to infer:

- port
- cookie file location

Given we default:
- host to localhost
- datadir to whatever the default location of bitcoin is for the current OS

Make sure that:
- All settings are overridable
- Clear log messages are emitted if omitted config values are defaulted

**Comment by thomaseizinger** [comment]
Closed because we want to revamp the config and we don't use JsonRPC in the near future but the HTTP API.
