### ISSUE TITLE
Make all JSON keys in APIs use `camelCase`

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#1138]
~This topic was meant to be a brownbag session initiated by Philipp, but we can probably make a decision about this in one of the grooming sessions.

It is related to: https://github.com/comit-network/comit-rs/issues/845~

This ticket is about just changing the casing in all the existing APIs.
Ticket https://github.com/comit-network/comit-rs/issues/985 will take care of adding tests for this.

**Comment by thomaseizinger** [comment]
Thumbs up this comment for `snake_case`.

**Comment by thomaseizinger** [comment]
Thumbs up this comment for `camelCase`.

**Comment by thomaseizinger** [comment]
Snake_case has the advantage that it is the default Rust convention, hence we don't have to do anything to get snake_case in our JSON documents when we serialize Rust structs.

There doesn't seem to be a clear advantage to using camelCase other than it being more idiomatic for JavaScript consumers.

I'll close this for now, maybe we can collect some feedback from users on whether they would want the API to use camelCase?
