### ISSUE TITLE
Rename the `vendor` directory

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1160]
"Vendoring" actually has a very distinct meaning and is totally unrelated to what we are doing with the `vendor` folder: https://doc.rust-lang.org/nightly/cargo/commands/cargo-vendor.html

We should rename our folder to `internal` to something else that makes more sense :)

**Comment by D4nte** [comment]
Or should we just leave it and trash it soon?

**Comment by thomaseizinger** [comment]
Given that the change is super trivial and the unknown timeline of "soon", I'd vote for changing it to avoid further confusion.
