### ISSUE TITLE
Investigate solutions for connecting two cnds behind NAT

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#1172]
# Problem

Currently, the person in the role of cryptographic Alice needs to send the SWAP REQUEST to the person in the role of the cryptographic Bob. This implies that the person taking the role of cryptographic Bob needs to have a port open.

# Goal 

Ideally, we want to allow users to use COMIT without opening a port.

# Recommendation

I don't remember where this list comes from, so treat it with a grain of salt:

Consider the following:
- Implement circuit relay ourselves (see https://github.com/comit-network/comit-rs/issues/1172#issuecomment-575452698)
- hole punching
- UPnP
- how BitTorrent does it
- available standards
- how Skype does it
- rendezvous nodes

Keep in mind that the solution needs to be compatible with libp2p.

**Comment by thomaseizinger** [comment]
Circuit relay seems to be fairly easy to implement: https://github.com/libp2p/specs/tree/master/relay

We should contribute that back to `rust-libp2p`.

**Comment by thomaseizinger** [comment]
Could we just solve this by using IPv6 ?!?!

cc @d4nte @bonomat

**Comment by D4nte** [comment]
> Could we just solve this by using IPv6 ?!?!
> 
> cc @D4nte @bonomat

I recently checked and very few ISPs support ipv6 in Australia.
In what countries is IPV6 available on consumer isp?
I feel like we are raising the entry criteria with such requirement.

**Comment by thomaseizinger** [comment]
> > Could we just solve this by using IPv6 ?!?!
> > cc @D4nte @bonomat
> 
> I recently checked and very few ISPs support ipv6 in Australia.
> In what countries is IPV6 available on consumer isp?
> I feel like we are raising the entry criteria with such requirement.

I wouldn't make it a must but it seems like something worth trying out and documenting: if you have IPv6, you can just trade peer to peer :)
