### ISSUE TITLE
No explicit claims about the transport layer

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#1184]
Currently cnd uses libp2p on top of TCP.  Neither are mentioned in RFC-001.  cnd makes assumptions about the transport layer and increasingly about the use of libp2p.  We should have a think/talk about what assumptions we make and explicitly state them in the RFCs.  How tightly do we want to be coupled to libp2p?

Related to https://github.com/comit-network/RFCs/issues/65

EDIT (considering comments below): Added item in DoD of above issue to ensure this gets resolved.  This issue should most likely be done as part of the above mention issue.

**Comment by thomaseizinger** [comment]
All of your concerns will be addressed by the above referenced issue, which is even in the current sprint :)
I think this issue can be closed then (or do we expect source code changes as part of addressing this because you opened it on the `comit-rs` repository?)

**Comment by tcharding** [comment]
> or do we expect source code changes as part of addressing this because you opened it on the comit-rs repository

During grooming please explain again process on where to open issues RFCs vs comit-rs

**Comment by thomaseizinger** [comment]
Closed in favor of https://github.com/comit-network/RFCs/issues/65.
