### ISSUE TITLE
Update code inline with RFC-002 (remove status code)

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#1187]
Recent amendment to the RFCs removed the status code.  An issue was created that was meant to bring the code inline with RFCs 1-3.  During coding on that issue (https://github.com/comit-network/comit-rs/issues/995) we added a `CLOSE` frame (still in progress).  We (@da-kami and @tcharding) decided to split #995 into separate issues to reduce the scope. Code in cnd that implements RFC-002 (and consecutively RFC-003)  needs to be brought into line with the RFCs.

- Remove status code
- Ensure all error logic is correctly handled by the `decision: declined` header

**Comment by da-kami** [comment]
After discussion with @thomaseizinger : Implement decline body without details is sufficient at the moment. We can add the details later, if/when needed. 
The `StatusCode` will be completely removed, there will be *no* distinction between `declined` and `rejected`.
