### ISSUE TITLE
Consider allowing send of CLOSE frame any time

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#1188]
Define 'any time' as any time it is the nodes turn to send a message.

If we were building COMIT from scratch using libp2p it seems feasible that the first message type would be a `CLOSE` message.  Usage being to signal that the stream was about to be closed.  Having this message type implicitly gives us an error frame.

Consider implementing handling of `CLOSE` frame as the initial message as one would if this was the first frame type implemented.  (Assumes PR to add `CLOSE` frame used by RFC-003 is merged, currently in progress.)

This has the added advantage of decoupling the `CLOSE` frame from RFC-003.

The goal of this ticket is to create a draft PR. If accepted, create ticket for documenting the behaviour in RFC001.

**Comment by thomaseizinger** [comment]
I think this should move to the RFC repository and be discussed there first :)

**Comment by luckysori** [comment]
Obsoleted by comit-network/RFCs#121.
