### ISSUE TITLE
Automatically determine feasible poll interval based on connected network

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1191]
In order to create a useful abstraction in https://github.com/comit-network/comit-rs/issues/1132, I would like to propose to remove the "poll interval" configuration parameter from the btsieve configuration and instead replace it with an algorithm that determines a reasonable poll interval based on the average blocktime of the connected network.

The current implementation requires the caller to pass in a "ticker" that will trigger a new request to fetch the latest block: 

https://github.com/comit-network/comit-rs/pull/1192/files#diff-713ff15f4b79a4a5f85bd0b190deb65fR18-R21

However, that abstraction does not really make sense. The underlying client can already talk to its source and determine a feasible interval based on the connected network.

**Comment by tcharding** [comment]
+1 for reducing the configuration burden on the user.
