### ISSUE TITLE
Replace bitcoin_quantity usage with rust-bitcoin `Amount` struct

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1195]
Latest release of rust-bitcoin (0.19.*) provides an `Amount` type. We want to make use of that.

Tasks:
- Upgrade `rust-bitcoin`
- Remove dedicated dependency on `bitcoin_hashes` and use the re-exported `hashes` crate from `rust-bitcoin`
- Remove all usages of `BitcoinQuantity` and replace with `Amount`
- Archive the `bitcoin_quantity` repository

**Comment by thomaseizinger** [comment]
`rust-bitcoin` just released a new version that includes the `Amount` type!

**Comment by D4nte** [comment]
Cannot use `rust-bitcoin:0.20.0` as we use `rust-bitcoin/rust-bitcoincore-rpc` that uses `rust-bitcoin:0.19.1`

**Comment by D4nte** [comment]
bitcoin-quantity repo archived.
