### ISSUE TITLE
Refactor `WaitingOpen` state of messaging state machine

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#1210]
*Current Situation*
`WaitingOpen` is currently a separate state of the messaging state machine. It is the state where we wait for the other party to accept a substream to be opened (similar to a handshake).  

*Problem*
`WaitingOpen` is not actually a state for messaging. It is more like a precondition to get the messaging state machine going. 

*Solution*
- Remove `WaitingOpen` as specific state and handle the waiting until we have the substream open in `handler.rs`. 
- Track in a separate list, which substreams we want to open
- Emit the necessary event in `poll` for each substream

**Comment by bonomat** [comment]
@thomaseizinger was this solved as part of refactoring the state machine accept/decline?

**Comment by thomaseizinger** [comment]
> @thomaseizinger was this solved as part of refactoring the state machine accept/decline?

No, it wasn't. I'll re-open it as it is still an issue.
