### ISSUE TITLE
Investigate the complexity of the swap state machine and propose a solution

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#1212]
Brian Kernighan famously said:
> Controlling complexity is the essence of computer programming.

Perhaps we should consider reducing the complexity of the state machine in cnd.  This came up a few times in conversation and then as part of thinking about our quarterly OKR on stability and robustness.

Already known pain points:
- the state machine is a giant `Future`
- errors cannot be recovered easily
- lots of generated code that one cannot see

The spike should cover these and possible further pain points and contain an alternative technical design for the state machine.

**Comment by D4nte** [comment]
Spike?

**Comment by da-kami** [comment]
@thomaseizinger is this still valid?
Groom when @thomaseizinger is back.

**Comment by luckysori** [comment]
Closed. @thomaseizinger do you agree?

**Comment by thomaseizinger** [comment]
Agree with closing yes because the complexity is "known". Should likely rewrite it with `async/await` instead of `StateMachineFuture`.
