### ISSUE TITLE
Ensure non-regression of cnd REST API

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1221]
As a developer, I want to ensure that updating to a new version of cnd will not break my application by surprise.

Task: Research how we can non-regression test our REST API and ensure that we do not break it when we say that we do not break it.

Note:
- Look at API contracts
- Think about how a developer could validate its API usage against a common document

**Comment by thomaseizinger** [comment]
Inlined into https://github.com/comit-network/comit-rs/issues/1122.
