### ISSUE TITLE
Disable CircleCI build-failure emails

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1235]
Currently, CircleCI sends build notifications via email.
We already receive them in a slack channel and could hence disable the emails because they don't really add value on top of that.

**Comment by bonomat** [comment]
I don't get any emails from CircleCI. Maybe it's your personal config?

**Comment by thomaseizinger** [comment]
It is indeed a personal setting here: https://circleci.com/account/notifications
