### ISSUE TITLE
Use quickcheck for btsieve query matching unit tests

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1239]
At the moment, all the unit tests in btsieve concerning the query matching generate test data manually.

For example: https://github.com/comit-network/comit-rs/blob/90348b62d987ee702ece4285eaf79c5db0609991/btsieve/src/ethereum/queries/transaction.rs#L120-L148

That is:
1. cumbersome to type
2. does not reflect actual real-world data
3. Makes it hard to identify, what parts of the setup data are actually relevant

We should use quickcheck to do property-based testing and let it generate all the data for us.

---

Property-based testing was introduced for one test with #1331 as part of out-of-sprint-scope day. We should build on that work to resolve this issue.

**Comment by bonomat** [comment]
I think we should rather use real-world data from mainnet/testnet. 
This is something we should keep in mind when we come across the mentioned lines of codes. 
Closing this ticket for now.
