### ISSUE TITLE
Create a `Hello World` example using CND's API

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#1245]
As the first step for : 
> * Create a CLI for developing COMIT apps (inspired by create-react-app/angular/etc)

we should create a simple `Hello World` example.

Design constraints:
- Grab a mate and a room
- Use TypeScript/JavaScript
- Should be a script/application (not long-running)
- We _don't_ want developers to structure their applications into Alice/Bob, hence the example should not suggest that. Either go with different usecases (send request / receive request) or build a single example that can handle both.

**Comment by D4nte** [comment]
I would suggest to create a `docker-compose.yml` that prepares an alice and bob cnds/btsieves/node as a **separate** and **pre-**task of this to save time.

**Comment by thomaseizinger** [comment]
> I would suggest to create a `docker-compose.yml` that prepares an alice and bob cnds/btsieves/node as a **separate** and **pre-** task of this to save time.

We actually decided in grooming that setting up the nodes is out-of-scope for this task. We assume that they are there and want to mostly figure out, what the hello-world actually looks like since that is complicated enough.

**Comment by D4nte** [comment]
> > I would suggest to create a `docker-compose.yml` that prepares an alice and bob cnds/btsieves/node as a **separate** and **pre-** task of this to save time.
> 
> We actually decided in grooming that setting up the nodes is out-of-scope for this task. We assume that they are there and want to mostly figure out, what the hello-world actually looks like since that is complicated enough.

Wouldn't #1245 made easier if the scripts were already here?

**Comment by thomaseizinger** [comment]
> > > I would suggest to create a `docker-compose.yml` that prepares an alice and bob cnds/btsieves/node as a **separate** and **pre-** task of this to save time.
> > 
> > 
> > We actually decided in grooming that setting up the nodes is out-of-scope for this task. We assume that they are there and want to mostly figure out, what the hello-world actually looks like since that is complicated enough.
> 
> Wouldn't #1245 made easier if the scripts were already here?

Maybe. We wanted to be more demand-driven since we don't yet know what the hello-world thingy looks like. Based on the outcome, we may need automation of one party etc.
