### ISSUE TITLE
Rewrite the first happy path e2e test (bitcoin <> ether) 

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#1246]
[Spike 11](https://github.com/comit-network/spikes/blob/master/0011-revise-e2e-test-framework.adoc) recommends a new e2e test design.
This ticket is about changing an initial test to this new design.

We recommend to start with "bitcoin" <> "ether".
Get inspired by the suggested design here: https://github.com/comit-network/spikes/blob/master/0011-revise-e2e-test-framework.adoc#the-ideal-test

This ticket on purpose doesn't include anything about the test-harness. You are only supposed to implement the test "framework".

Use the sdk.

**Comment by thomaseizinger** [comment]
Swapped this with https://github.com/comit-network/hello-swap/issues/33 because it makes more sense to do the e2e test ticket after this and use as much of the SDK as possible.
