### ISSUE TITLE
Bitcoin layer-1 support

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1250]
## Problem

At the moment, the only available connectors for the Bitcoin blockchain are the `blockchain.info` HTTP API and a bitcoind connector. This is problematic because:

- the `blockchain.info` connector assumes trust towards a central entity
- the bitcoind connector implies a bitcoind node (either running locally or publicly reachable)

## Goal

Allow users to do swaps on Bitcoin with the least amount of setup possible (including other software).

## Recommendation

Implement the two connector traits `LatestBlock` and `BlockByHash` by establishing connections to bitcoin nodes via the p2p protocol.
To start with, I'd recommend the following set of nodes per network:
- Mainnet -> connect official bootnodes
- Testnet -> connect to official bootnodes
- Regtest -> listen on localhost (if easy, local network)

**Comment by D4nte** [comment]
I'd replace "layer 1" with "bitcoin p2p protocol"

**Comment by bonomat** [comment]
Not a near term goal.
