### ISSUE TITLE
Have protocol events timestamped so that they can be ordered

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1252]
Currently we have no way of ordering events that happen within the COMIT protocol.  The assumption is that it would be useful for cnd clients to be able to order events and/or see the time that has elapsed since events occurred.

[Spike 10](https://github.com/comit-network/spikes/blob/master/0010-timestamps.adoc#recommendations) researched adding timestamps.  Spike makes a suggestion to which events should be timestamped.

## In Scope

Goal: To have timestamps for all events as perceived by cnd.  

## Out of Scope

- On chain timestamps (see https://github.com/comit-network/comit-rs/issues/1451)

- Exposing timestamps to cnd clients (see https://github.com/comit-network/comit-rs/issues/1452)

**Comment by D4nte** [comment]
It'll be good for the scope to be task listed here.

**Comment by luckysori** [comment]
Close because this is low priority at the moment. Instead we will focus on #1481.
