### ISSUE TITLE
Remove `ToEthereumAddress`

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1281]
- Check if we actually need to calculate the address dynamically in the test code
- Move code to `key_gen`
- Remove the trait
- Remove the TODO (https://github.com/comit-network/comit-rs/issues/1203)

**Comment by bonomat** [comment]
@D4nte : is this still a thing?

**Comment by D4nte** [comment]
Probably can be merged into #1472

**Comment by D4nte** [comment]
This is actually only in blockchain_contracts. It looks like it's used so not sure we should remove it. @thomaseizinger what do you think?

**Comment by thomaseizinger** [comment]
We no longer have it in comit-rs, so I think this can simply be closed :)
