### ISSUE TITLE
Change cnd to use public keys for the Bitcoin identity

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1296]
Right now our we use the "pubkey hash" as the identity in [RFC005](https://github.com/comit-network/RFCs/blob/master/RFC-005-SWAP-Basic-Bitcoin.md). This is the wrong choice for two reasons:

1. This blocks the adoption of miniscript because the HTLC created from the miniscript policy uses public keys and not pubkey hashes. This makes sense because it is obfuscated through the P2WSH address anyway.
2. In the [taproot proposal](https://github.com/sipa/bips/blob/bip-schnorr/bip-taproot.mediawiki) outputs are locked to public keys. So sending to someone's public key will become the standard way of transferring Bitcoin (hopefully).

You would probably want to start by changing this line to a `PublicKey`: 

https://github.com/comit-network/comit-rs/blob/5702e0a207784745e5bb256014487cb6cce1b20f/cnd/src/swap_protocols/ledger/bitcoin.rs#L31

and simply follow the compile errors :)

**Comment by D4nte** [comment]
Can't just get codin', need to update the HTLC hex first...

**Comment by thomaseizinger** [comment]
> Can't just get codin', need to update the HTLC hex first...

Sure? Each party could hash the pubkey after receiving it. Then it would be an implementation detail of the current HTLC that would be removed once we move to miniscript.

**Comment by bonomat** [comment]
I think you only need to change the internals and once handed the pubkey to the htlc generation you create the hash.
