### ISSUE TITLE
Btsieve block pruning in bitcoin and ethereum block processing

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#1298]
At the moment the when processing blocks, we just store all blocks within our internal `Blockchain` representation. Here is the example code for bitcoin:

https://github.com/comit-network/comit-rs/blob/41145dd3e8e83473897ade47a6c5e571c3e53bd4/btsieve/src/main.rs#L115-L128

Instead of storing all blocks, we should have a sliding window of blocks and drop blocks old blocks.
We should only store X number of blocks for each blockchain. Hardcode the value per chain (6 for bitcoin, 200 for ethereum).

This ticket is only about ensuring that we don't allocate large amounts of memory over time.

**Comment by luckysori** [comment]
Closed because the DAG is going away.
