### ISSUE TITLE
Btsieve blocksource configuration

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#1299]
This ticket sums up implementation proposals to deal with different blocksources in btsieve. Solution to be discussed in Grooming on basis of the solution proposal below. 

Currently there is no way to configure different blocksources in btsieve (even though there are already different blocksource implementations).

Proposed solution: 
All blocksources (current and future) are used in parallel and poll for blocks. Once the block is added to our internal block-structure (`processor`) we check if the block is there, if so we just don't add it again. 

Tasks:
1. Combine the already existing blocksources to poll for blocks in parallel.
2. Don't bother logging/reporting blocks that are already in the structure. 

After this is done there can be a follow up ticket for:
Configure btsieve to ONLY use a CERTAIN blocksource. This could be done by configuration parameters or feature flags (so btsieve would be compiled to only allow plugging e.g. blockchain clients and no http source).

Blocked by: #1300

**Comment by thomaseizinger** [comment]
Closed under the assumption that this is actually what #1300 is about.

@da-kami please re-open and clarify if that is not the case.
