### ISSUE TITLE
Btsieve startup and block polling behavior

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#1300]
Solution proposal (below) to be discussed in Grooming.

Currently btsieve knows how to connect to the blockchain nodes through its configuration file. It would be easier to define `ledger` + `network` and btsieve would initialise all available blocksources automated internally.  

Solution proposal:
1. When starting btsieve, tell btsieve if it starts up for testnet or mainnet (configure for each ledger).
2. Btsieve automatically initialises all blocksources for mainnet/testnet and starts polling for blocks.
3. If blocks are persisted (for recovery, ...) testnet and mainnet have to be distinguished.

Assumption for local blockchain clients: scan the default ports

**Comment by thomaseizinger** [comment]
Obsolete as per https://github.com/comit-network/comit-rs/issues/1350.
Replaced with https://github.com/comit-network/comit-rs/issues/1455.
