### ISSUE TITLE
Verify block hash against content

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1319]
In btsieve, when receiving a new block (Bitcoin or Ethereum), check that the block hash matches the content.
Log an error if it does not matches as it means the source may be compromised.

**Comment by bonomat** [comment]
I think this is something each blocksource should deal with in separation. e.g. when getting a block from blockstream.com I would expect that this is a *trusted* source and one should only activate *trusted* blocksources. 
Differently, if the blocksource is layer-1, e.g. you retrieve the block directly through the bitcoin protocol, then this block should be validated. 

Hence, I would close this issue and rather add this to the corresponding blocksource ticket.

**Comment by D4nte** [comment]
To be done per block source.

Example:
* Bitcoin explorer: You trust the API already
* Bitcoin p2p protocol: Must be done as part of the implementation
