### ISSUE TITLE
Replace `InMemoryEthereumWallet` with emerald-rs

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1321]
Instead of our own, handrolled library for signing ethereum transactions during the test, we should be using a proper ethereum wallet:

https://docs.rs/emerald-rs/0.25.6/emerald_rs/

We may even be able to replace rust-web3 with this.

Related to coblox/blockchain-contracts#4.

**Comment by D4nte** [comment]
What about `ether.js` ?

**Comment by bonomat** [comment]
Closing this as there is not `InMemoryEthereumWallet` in our code base and it's something one could do when rewriting the tests. If we never touch them again, then there is no need to have a different library for that.

**Comment by thomaseizinger** [comment]
It is just called slightly different from what the ticket says:
https://github.com/comit-network/comit-rs/blob/master/blockchain_contracts/tests/ethereum_helper/wallet.rs

I am keen to keep this open because it removes a lot of duplicated code that we created as part o trying to get rid of `ethereum_support`.

**Comment by thomaseizinger** [comment]
> If we never touch them again, then there is no need to have a different library for that.

I disagree :)
One, the "we never touch it again" is seldomly true and two, in this case, we have untested code that verifies that our code works. That is suboptimal and should be changed.

However, all that information should go into the ticket obviously but I didn't take the time for that when writing it down :)

**Comment by thomaseizinger** [comment]
Closed in favor of https://github.com/coblox/blockchain-contracts/issues/9.
