### ISSUE TITLE
COMIT as a library (on crates.io)

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1327]
This epic tracks all issues that are related to separating out the core parts of `cnd` into a `comit` library.

Requirements:
- A library released on crates.io cannot have path dependencies

Scope:
- Everything defined in the RFCs would be implemented as part of this library, every functionality _not_ specified in RFCs would need to go into the application

Other notes:
- Need extensive testing on the API of the library (probably replacing our current e2e tests)

**Comment by bonomat** [comment]
The main effort was to remove path dependencies and that is done.
