### ISSUE TITLE
Specify API of cnd using OpenAPI

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1336]
As per spike 16: https://github.com/comit-network/spikes/blob/master/0016-how-to-document-cnd-http-api.adoc#recommend-openapi

Endpoints to be documented:
- GET /swaps
- POST /swaps/rfc003

Additionally
- Custom section for ledger actions (not as `path` but as custom section with custom content type)

include section about siren & actions.
figure out how our JSON schema integrates with this.

schema + open api files should be in the repository

**Comment by D4nte** [comment]
Some people from TenX use OpenAPI, @bonomat knows who.

**Comment by luckysori** [comment]
Closed because we have realised that we only want to write a HTTP API specification for testing or internal documentation and not for public documentation.
