### ISSUE TITLE
Embed rendered OpenAPI document in cnd on every build

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1338]
We want cnd to serve a rendered version of the API documentation as it is running.

To achieve this, we need to:
- add a build step that renders the current OpenAPI document as part of the build using ReDoc
- serve the rendered version from cnd (similar to how we serve comit-i)

Currently, we serve comit-i on a different port than the API, if we do the same for thing for the docs, it would be three.
Since it is all just HTTP traffic, we should consolidate that to one port and just use different routes.
The proposal is:
- `/api` for the API
- `/docs` for the documentation
- `/comit-i` for comit-i

**Comment by luckysori** [comment]
Closed, see: https://github.com/comit-network/comit-rs/issues/1336#issuecomment-532475868.
