### ISSUE TITLE
Be able to fetch Bitcoin testnet blocks from HTTP block explorer

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#1340]
## Problem

blockchain.info does only return raw-hex blocks for mainnet (see: https://github.com/comit-network/comit-rs/pull/1305) so we cannot fetch testnet blocks from a Bitcoin block explorer at the moment.

## Goal 

Be able to fetch Bitcoin testnet blocks from HTTP block explorer.

## Proposal

Note that the `Blocksource` trait does not longer exist, it was split up into:
* `LatestBlock` trait
* `BlockByHash` trait

As by the original ticket, the blockstream API was evaluated to be best suited, see https://github.com/comit-network/comit-rs/issues/1247#issuecomment-526075960

The JSON-mapping part is already mostly done, see: 

https://github.com/comit-network/comit-rs/tree/1247-additional-bitcoin-http-blocksource
There are several `TODO`s in the code, see https://github.com/comit-network/comit-rs/blob/25fa395d33edffb1ac7f9b66016666a5bb9310e7/btsieve/src/bitcoin/blockstream_bitcoin_http_blocksource.rs#L214-L226

**Comment by thomaseizinger** [comment]
I think this one should be refined as per the new issue writing approach.

**Comment by D4nte** [comment]
assigned to @da-kami for refinement

**Comment by bonomat** [comment]
Closed for now. We are fine with having full nodes for testnet and we don't have a way of configuring cnd.
