### ISSUE TITLE
Create docker images for `cnd` and `btsieve` for releases

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1341]
Do this:

- where to build the container
  - Dockerhub (free)
- parent image
  - Ubuntu (works)
- how config files are handled
  - Hard coded default config file in a volume.
- default entrypoint
  - binaries (nothing else makes sense)
- one vs two Dockerfiles
  - two dockerfiles (simple)

**Comment by D4nte** [comment]
I would expect both binaries to be in the same Docker.

**Comment by thomaseizinger** [comment]
There are still quite a few things open for this ticket and to be decided during grooming :)

- where to build the container
- parent image
- how config files are handled
- default entrypoint
- one vs two Dockerfiles

**Comment by thomaseizinger** [comment]
Draft PR here: #1416.

**Comment by thomaseizinger** [comment]
I am compiling cnd and btsieve inside the containers now because the artifacts don't exist yet at the time when the container build is triggered on the release branch.
It takes an aweful lot of time but it is an async process that can run in the background so I'd say it is fine :)
And this way, the images can even be created on MacOS!
