### ISSUE TITLE
Create cache proxies for blockchain connectors

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1349]
## Problem

With the changes to what a `BlockchainConnector` is in https://github.com/comit-network/comit-rs/issues/1347 and https://github.com/comit-network/comit-rs/issues/1346, we will fire a request towards the `LatestBlock` and `BlockByHash` traits. The same requests are sent several times from different invocations of `MatchingTransactions`.

## Goal

Use the network more efficiently. Ideally, we want to request each block only once.

## Recommendation

Make use of the proxy pattern to write caching implementations of for each connector: `BitcoindConnector` and `Web3Connector`.
The cache proxy can be specific to each chain but should be generic over the respective traits (`BlockByHash`, `LatestBlock` and `ReceiptByHash`) to allow any connector for this particular chain to be plugged in.

We'd recommend a struct with a generic inner (connector, implements `BlockByHash`, etc traits) field. The struct would store the result and then forward it to the inner. 

Ethereum needs to cache receipts and blocks. Recommendation would have a `BlockHash` and `ReceiptHash` structs. Or you could be generic over what you are caching.

Note that the facade needs to have all 3 traits implemented (`BlockByHash`, `LatestBlock` & `ReceiptByHash`) so the proxy struct will have to implement them too.

**Comment by tcharding** [comment]
I feel that this is two separate issues.

a) `block_by_hash` should cache blocks and return local cached block if a lookup is made for a block we have already fetched from the connector.
b) Optimise `LatestBlock` so we don't fetch data when the latest block has already been fetched.
