### ISSUE TITLE
Remove duplication in `main.rs` with a macro

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1350]
PR https://github.com/comit-network/comit-rs/pull/1345 moved the conditional code for initializing the btsieve routes to the very outside of the `main`.

This caused some code duplication which unfortunately cannot be extracted with variables/methods (Rust limitation of `impl Trait`).

We should use a macro that takes the routes as arguments and expands to the code we need in order to remove this duplication.

**Comment by thomaseizinger** [comment]
Obsolete as per https://github.com/comit-network/comit-rs/issues/1350.

**Comment by luckysori** [comment]
> Obsolete as per #1350.

This is recursive.

**Comment by D4nte** [comment]
@thomaseizinger did you see [Lucas' comment](https://github.com/comit-network/comit-rs/issues/1350#issuecomment-536354890)?

**Comment by luckysori** [comment]
Did you see my comment?
