### ISSUE TITLE
Store query-matching transactions in `btsieve` instead of just storing the tx-hash

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#1375]
Currently we just store the tx-hash after a query matched a transaction. However, CND sometimes requires the complete transaction to be returned. For these cases we currently fetch the transaction twice from the block-source (fetch by tx-hash when needed). 

Instead of fetching the TX twice we should store it.

Tasks:
- Store complete transaction instead of tx-hash after matching query for bitcoin and ethereum. Split up for bitcoin and ethereum needed.
- Fetch complete transaction from store upon request from CND and return hash or complete transaction.
- Check if `transaction_by_hash(...)` in `bitcoind_http_blocksource` (see https://github.com/comit-network/comit-rs/pull/1371) is still needed. It would be good to do this before #1347 (thus blocked for now)

**Comment by D4nte** [comment]
Is it really a technical debt? Sounds like an optimisation to me.

**Comment by thomaseizinger** [comment]
> Is it really a technical debt? Sounds like an optimisation to me.

It is kind of technical debt.

With the undergoing changes to btsieve, only storing the TX hash no longer really makes sense.
Actually, from the moment we introduced the "return_as" feature, not storing the transaction was already technical debt. Even though just storing the whole transaction would have probably been the faster change ...

**Comment by bonomat** [comment]
Closed in the favor of #1408: the reason is that we don't need to store this anymore if we return the transaction directly through the futures.
