### ISSUE TITLE
Rethink how we handle/embed `comit-i` in `cnd` (without embedding statically-compiled version of openssl)

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1377]
Replace `reqwest` with another https-able crate to fetch the comit-i bundle in `internal/comit_i`.

This will allow `cnd` and `btsieve` to not have openssl statically linked.

See https://github.com/comit-network/comit-rs/pull/1376#issuecomment-530226535 for more details.

Note: Looks like [ureq](https://crates.io/crates/ureq) was made exactly for this purpose:
> Motivation
> - Minimal dependency tree

**Comment by thomaseizinger** [comment]
Both, `ureq` and `reqwest` depend on `rustls` though :(
We could shell out to `curl` for the download possibly?

**Comment by D4nte** [comment]
curl is a not available by default on Ubuntu Docker so that's something that the user would have to install. Rustls is not openssl though.

**Comment by D4nte** [comment]
Well actually, downloading a remote zip may not be our best idea. Instead we could use git sub modules and using the features as above, only checkout and bundle if the xomit-i feature is enabled. Also, make it disabled by default.

**Comment by D4nte** [comment]
I am keen on the feature cause it's a pain to compile in the train due to xomit-i download

**Comment by thomaseizinger** [comment]
> I am keen on the feature cause it's a pain to compile in the train due to xomit-i download

Yeah, I agree. We should rethink the way we do this (like, should we even embed comit-i at all?)

**Comment by D4nte** [comment]
> > I am keen on the feature cause it's a pain to compile in the train due to xomit-i download
> 
> Yeah, I agree. We should rethink the way we do this (like, should we even embed comit-i at all?)

Embedded comit-i sounds good to me but I think it should be opt-in :)

**Comment by luckysori** [comment]
Closed because this was mostly done when we replaced  `reqwest` with `ureq`.
