### ISSUE TITLE
Close the substream instead of declining the request if a header is missing

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1405]
## Problem

The RFC says that to [close the substream](https://github.com/comit-network/RFCs/blob/master/RFC-001-libp2p.adoc#442-dealing-with-errors) if an error occurs.

We are not doing that. Our implementation is still sending back `declined` messages.

## Goal

Align the implementation with the specification.

## Recommendation

Instead of always returning a response, we should make use the Error kind of the Future returned from the [`handle_request`](https://github.com/comit-network/comit-rs/blob/12d2fb12214868c9a1f3afd305f7b3be593fbc6f/cnd/src/network.rs#L171-L175) function.
Given this error, the only way of closing the substream for now is to drop the channel that we received through `BehaviourOutEvent::PendingInboundRequest` inside the `NetworkBehaviourEventProcess` implementation. Dropping this channel will cause the polling inside `libp2p_comit::substream::inbound::State` to fail and hence, the substream will be closed.

**Comment by luckysori** [comment]
Do we wanna fix this RFC mismatch?

**Comment by thomaseizinger** [comment]
No because we are going to trash the whole libp2p module soon and replace it with something better :D
