### ISSUE TITLE
Unnecessary custom adaptor struct: `HttpApiProblemStdError`

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1437]
Problem: We are currently using a custom adaptor struct that is no longer needed.

## History

In order to use warp's custom rejections with `HttpApiProblem`, we had to define an adaptor struct that implements `std::error::Error`:

https://github.com/comit-network/comit-rs/blob/6616f56206b3a4d40feaaf15de40b9925a9dae6c/cnd/src/http_api/problem.rs#L11-L14

## Update

With a recent version of the http-api-problem crate (0.13.1), the `HttpApiProblem` type directly implements `std::error::Error`: https://github.com/chridou/http-api-problem/commit/3e59dc7b1bdd6e35eb9ae749e93aef9579d57371

## Recommendation

We already depend on version 0.13.1.
Given that, we can remove our adaptor struct and directly use `HttpApiProblem` in all places where we use `HttpApiProblemStdError`.

**Comment by thomaseizinger** [comment]
Feels good because it removes unnecessary code :)

**Comment by luckysori** [comment]
It feels very good.

**Comment by tcharding** [comment]
Issue needs re-writing to use problem/goal/solution -  suggesting here instead of attempting this.

**Comment by D4nte** [comment]
@korrat go for it!
