### ISSUE TITLE
Use structs for `Network` instead of enums?

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#1444]
Goal: Be able to write code that abstracts over the different networks of a ledger through type variables:

```rust
impl BlockSource<bitcoin::Mainnet> for BitcoindHttpBlockSource {}
```

Problem: Ledger networks are currently structured in enums, which does not allow us to use them as types in generic implementations (such as `Blocksource`)

Solution:

```rust
mod bitcoin {
  struct Mainnet;
  struct Testnet;
  struct Regtest;
}

impl Ledger for bitcoin::Mainnet {}
impl Ledger for bitcoin::Testnet {}
impl Ledger for bitcoin::Regtest {}
```

**Comment by thomaseizinger** [comment]
This has non-trivial implications and should be done as part of https://github.com/comit-network/comit-rs/issues/1708.
