### ISSUE TITLE
cnd's config file has sections that are required but don't need to

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1448]
**Problem:**
The sections `http_api` and `network` are required to exist in the config file.
1. This makes changes to these sections more painful because it invalidates the old config file.
2. We only write default values to those sections upon the first startup anyway.

**Recommendation:**
Instead of writing default values for `http_api` and `network` to the configuration file, we should make them optional and default to the values we would have written otherwise.

Note:
This ticket, in the long run, helps with making the config file totally optional because:
- the secret seed will be removed in #948 
- the `btsieve` section went away with #1408

**Comment by D4nte** [comment]
@thomaseizinger back to backlog?
