### ISSUE TITLE
Extract ledger event timestamps from the blockchain

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#1451]
Assumption:  cnd client would like to see the on chain time of events.

Context: Resolution of issue: https://github.com/comit-network/comit-rs/issues/1252 will add timestamps for ledger events as they are perceived by cnd.  This time is not necessarily the same time as the event was recorded in the blockchain e.g., if cnd was down when the block was first propagated to the network.

Goal: Have on chain timestamps for events stored within cnd.

**Comment by thomaseizinger** [comment]
I am blocking this on #1408 because it should make this ticket a lot easier to achieve.

**Comment by luckysori** [comment]
We only needed this when we originally wrote the timestamp spike, for logging in comit-i. However, now we only need the timestamp of when the swap was started for btsieve to be able to [look back in time](https://github.com/comit-network/comit-rs/issues/1289).
