### ISSUE TITLE
Expose event timestamps to cnd client

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#1452]
Assumption: cnd client apps would like to have the feature where COMIT protocol events have an associated timestamp.

Goal: Expose timestamps to cnd clients for various events.  Suggested events are outlined in the spike: https://github.com/comit-network/spikes/blob/master/0010-timestamps.adoc

For this to be done cnd first needs to have some timestamps available to expose.  These may/will be added by:
- https://github.com/comit-network/comit-rs/issues/1252
- https://github.com/comit-network/comit-rs/issues/1451

**Comment by luckysori** [comment]
We only needed this when we originally wrote the timestamp spike, for logging in comit-i. However, now we only need the timestamp of when the swap was started for btsieve to be able to [look back in time](https://github.com/comit-network/comit-rs/issues/1289).
