### ISSUE TITLE
Most of the code assumes that we are always connected to a bitcoin and an ethereum node

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1458]
**Problem:** With https://github.com/comit-network/comit-rs/pull/1443, it became clear that many places in the codebase assume that we are always connected to a bitcoin and an ethereum node. Previously, this was not a problem because the "connection" was hidden behind btsieve's HTTP API.

Now, we are instantiating the blocksources directly in cnd:

https://github.com/comit-network/comit-rs/blob/3ecf41edaea94e06bd3ab3d61cc88a4ef8211885/cnd/src/main.rs#L57-L65

**Goal:** To not instantiate any blockchain clients until we actually need them.

**Recommendation:** -

**Comment by bonomat** [comment]
@bonomat=stalebot: 

Let's revisit this once we need to / want to support a new ledger
