### ISSUE TITLE
Compile binaries with static libs (all)

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1461]
## Problem

The glibc library shipped with Linux distros is not always the same.

## Goal

Generate a binary with glibc as a static library

## Recommendation

```
rustup target add x86_64-unknown-linux-musl
cargo build --release --target x86_64-unknown-linux-musl
```

should do it.

**Comment by thomaseizinger** [comment]
Finding one: needs the `musl-tools and musl-dev` packages on ubuntu to build.

**Comment by D4nte** [comment]
Finding two: be sure to install the target for the right rust toolchain.

**Comment by tcharding** [comment]
From my understanding statically linking glibc is not recommended.  Here is a link explaining why https://stackoverflow.com/questions/57476533/why-is-statically-linking-glibc-discouraged

**Comment by thomaseizinger** [comment]
> From my understanding statically linking glibc is not recommended. Here is a link explaining why [stackoverflow.com/questions/57476533/why-is-statically-linking-glibc-discouraged](https://stackoverflow.com/questions/57476533/why-is-statically-linking-glibc-discouraged)

Very good insight, thanks @tcharding! Should definitely consider this thoroughly before moving forward :)

**Comment by luckysori** [comment]
Closed because you can just run cnd inside docker.
