### ISSUE TITLE
The ideal continuous integration process

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1475]
> Note: This is a follow-up to https://github.com/comit-network/comit-rs/issues/1382.

## Goal: Implement the ideal continuous integration process.

The ideal process has (at least) the following four characteristics:

- **safe**:
	- There should be no merge conflicts in the target branch
	- There should be no semantic conflicts in the target branch (i.e. master is always green)
- **efficient**:
	- The process should not trigger more builds than necessary
	- The process should not require making more commits than necessary
- **automated**:
	- Merging a pull request should be a single action (clicking a button, applying a label, delegating to a bot, etc)
- **easy to understand**:
	- The process should be visible (one can see what is going on)

## Problem

The current process does not fulfill these criteria in several ways:

- Unnecessary commits have to be added in order for the process to work (either through rebasing or merging in the target branch)
- In order to merge N pull requests, at least N builds have to be triggered (one after each PR has been merged)
- The process is barely visible: it is not clear, which PRs are going to be merged in which order by mergify

## Recommendation: Adopt bors

https://github.com/bors-ng/bors-ng

Here is why:

- **less builds**: bors queues up several PR than are ready to be merged in a staging area, thus testing several PRs for their compatibility with each other and with master
- **less commits**: bors only uses the original commits added by their authors and tests them against latest master. no rebasing/merging required to trigger builds
- **visible**: bors has a dashboard

There are some more things that we could do _in addition_ to adopting bors, that could help adopting the process:

- Disallow manual merging: Force ourselves to go through bors in order to merge PRs so that the process is enforced and people don't infer with the work of the bot.

**Comment by D4nte** [comment]
Due of #1476 ?

**Comment by thomaseizinger** [comment]
Closed in #1484.
