### ISSUE TITLE
Fastest way to Testnet

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#1480]
## Problem

Currently, it is not straightforward to setup cnd for testnet and actually test it on testnet.

## Goal

Find a way to make it easy as possible to setup cnd for testnet but also prepare the environment to use it.
This includes the funding/faucet problematic.

## Recommendation
Grab a room, grab a mate.

Steps:
1. Setup cnd for testnet
2. Take note of any cumbersome steps, steps that requires knowledge
3. Find an easy way to fund
4. Propose solutions to remove such steps

**Comment by thomaseizinger** [comment]
Created the following epic as a result of this issue: https://app.zenhub.com/workspaces/coblox-scrum-5be4c2ea4b5806bc2bf2d351/issues/comit-network/comit-rs/1503
