### ISSUE TITLE
Store a timestamp to the start of a swap

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#1481]
**Goal**:
To be able to (eventually) persist a timestamp of the start of a swap which could then be used to create btsieve queries that [look back in time](https://github.com/comit-network/comit-rs/issues/1289).

**Recommendation**:
Take the timestamp of when the swap was accepted and store it in the state store.

---

Related to #1289.
Related to https://github.com/comit-network/comit-rs/pull/1453.

**Comment by luckysori** [comment]
Not now because we are still coming up with the data model to be persisted.

**Comment by tcharding** [comment]
We did this already but closed it because without using it in btsieve the code introduced is dead.

https://github.com/comit-network/comit-rs/pull/1453
