### ISSUE TITLE
Include community chat link in README

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1499]
## Problem

External contributors and users do not have an easy synchronous way to reach the team.

## Goal

Enable people to contact the COMIT team through a chat application.

## Recommendation

Create a gitter for community and add it to the readme (and all other readmes of comit-network projects).

Invites to slack are on a personal basis after first contact in gitter.

**Comment by D4nte** [comment]
@da-kami @bonomat are we happy with the recommendation?

**Comment by D4nte** [comment]
@da-kami It seems like it's not up to date anymore as you mentioned Slack in the hackathon issues?

**Comment by bonomat** [comment]
Thank for pointing this out: Let's bring all community chats to slack

**Comment by da-kami** [comment]
> Thank for pointing this out: Let's bring all community chats to slack

Do you mean CoBloX slack? 
Are you OK with anybody entering?

Should I really publish a link openly for our slack? (what about trolls...?)

I would propose:
- Still use gitter for public first contact
- once we had first contact we invite to slack

**Comment by D4nte** [comment]
> We already have a community group: gitter.im/comit-network/community
> So far it did not fly. But we don't know the reason why. Maybe just because people don't know.

I was not even aware of this room...

**Comment by bonomat** [comment]
I agree with Daniel, let's not put a slack invite link publicly online but use it as invite-only.
