### ISSUE TITLE
Configuring cnd is complicated as soon as we have more than one configuration file

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1501]
## Problem / question

Which tools do we (want to) give to users to configure cnd?
At the moment we have a single configuration file and a commandline parameter to override it.

As soon as we move the secret seed out of the configuration file (https://github.com/comit-network/comit-rs/issues/948), we have _two_ files that the user needs to configure / handle. We also talked about separating out the configuration of individual ledgers into distinct files (one for bitcoin, etc), resulting in potentially even more files.

## Goal

Keep the configuration complexity to a minimum.

## Recommendation

Enter _profiles_.

We introduce profiles to cnd. A profile is a named configuration set, consisting of all the files needed to run an instance of cnd.

- Profiles are managed as subdirectories in the default configuration folder (`~/.config/comit` on Linux).
- cnd can be started with a profile string: `cnd --profile bob` starts cnd with the "bob" profile
- the `--profile` is an optional parameter and defaults to the string "default": invoking `cnd` is therefore equivalent to `cnd --profile default`
- If the given profile string does not match any existing profile, startup should fail
- If the given profile string is a _path_ (is there a reliable heuristic for that?) that resolves to a directory, try and load the folder as a profile.

Files within a profile folder have a fixed name and cannot be changed.

**Comment by tcharding** [comment]
Perhaps also add `--profile-dir <path>` ?

**Comment by thomaseizinger** [comment]
> Perhaps also add `--profile-dir <path>` ?

You mean as an alias to `--profile`? I'd like to avoid dashes in commands as much as possible because they are weird to type :sweat_smile:

**Comment by D4nte** [comment]
> I'd like to avoid dashes in commands as much as possible because they are weird to type 😅

I don't understand. Many applications have dashes/hyphens in their command. e.g. `git`.

**Comment by D4nte** [comment]
I do not understand the reason behind this proposal. Such proposal would be valid for an application for which we expect a user to switch easily between profiles or even run several instances of the application between profiles.

I don't believe this is the case for cnd.

My counter-proposal:
- `--config path/to/config/folder`: in such folder, you would expect to have your seed file and config file. By default it's `~/.config/comit` as it is currently.
- `--seed path/to/seed/file`: if the user wishes to store the seed somewhere different than the config (e.g. encrypted folder), then such option would allow the user to do so.

The `--seed` option could be put on the back burner until someone asks for it.

**Comment by thomaseizinger** [comment]
> > I'd like to avoid dashes in commands as much as possible because they are weird to type sweat_smile
> 
> I don't understand. Many applications have dashes/hyphens in their arguments. e.g. `git`.

True, and I dislike all of them because it is cumbersome to write/autocomplete :)

> I don't believe this is the case for cnd.

Maybe profiles are an overkill yeah. Best to discussed in person/slack I'd say. Happy to chat about it anytime :)

**Comment by bonomat** [comment]
@thomaseizinger: can you please organise a meeting for this ticket (and others in comit-network/comit-rs#1503)

**Comment by thomaseizinger** [comment]
> @thomaseizinger: can you please organise a meeting for this ticket (and others in #1503)

Done!

**Comment by bonomat** [comment]
From my understanding from last weeks call we will not go for profiles but for config directories. @thomaseizinger / @D4nte : can you refine this ticket please?

**Comment by thomaseizinger** [comment]
Superseded by https://github.com/comit-network/comit-rs/issues/1583.
