### ISSUE TITLE
Allow users to configure ledgers without touching a configuration file

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1502]
## Problem

The configuration of ledgers is a bit odd at the moment (see https://github.com/comit-network/comit-rs/issues/1455).
In addition to that, people have to know the config file structure in order to actually configure those ledgers.

## Goal

Allow users to configure ledgers without touching a configuration file.

## Recommendation

> This builds on the assumption that https://github.com/comit-network/comit-rs/issues/1455 is implemented.

Add a commandline parameter for each ledger (bitcoin & ethereum at the time of writing) that accepts the respective network as an argument:

- `cnd --bitcoin=testnet --ethereum=ropsten`

In combination with https://github.com/comit-network/comit-rs/issues/948 and https://github.com/comit-network/comit-rs/issues/1448, this allows us to _not_ generate a config file at all upon startup and instead resolve everything from default values.

**Comment by bonomat** [comment]
To be considered in #1844
