### ISSUE TITLE
Simplify cnd configuration file in regards to comit-i

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1504]
## Problem

Currently, we open up to _two_ ports when we start cnd: one for the API and one for comit-i. This is problematic in several ways:

- it causes CORS issues because comit-i is served from a different port than the API it needs to access
- it adds an entry to the configuration file

## Goal

Reduce configuration complexity and improve developer user experience.

## Recommendation

Use paths instead of ports to separate the two HTTP applications:

- `/api/` -> HTTP API
- `/comit-i/` -> comit-i

Note that this is a breaking change in our API and clients will have to update accordingly. To avoid this in the future, I would also propose to allow clients to not hard-code the API paths.
Concretely, we I propose to:

- serve a Siren-document for GET requests on `/` with `Accept: application/json`
- redirect to `/comit-i` for GET requests on `/` with `Accept: text/html`

The Siren document would (for now) contain two links:

- `list-swaps`, would point to `/swaps`
- `new-rfc003-swap` would point to `/swaps/rfc003`

**Comment by bonomat** [comment]
Since we do not know how comit-i will evolve/survive I propose to remove comit-i from cnd.

**Comment by thomaseizinger** [comment]
> Since we do not know how comit-i will evolve/survive I propose to remove comit-i from cnd.

@D4nte @da-kami @luckysori @tcharding can you vote on this please?

**Comment by luckysori** [comment]
Remove imo.

**Comment by tcharding** [comment]
+1 for remove

**Comment by thomaseizinger** [comment]
Replaced by
- https://github.com/comit-network/comit-rs/issues/1557
- https://github.com/comit-network/comit-rs/issues/1558
