### ISSUE TITLE
Change our network-layer API to allow sending a response at any time

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1507]
## Problem

Currently, upon receiving a swap request, the network layer emits an event that contains a channel which you have to use to send the response back to the other party:

https://github.com/comit-network/comit-rs/blob/0e9bacbc3e5a2dddcfae3ebc38edf593870fbad9/cnd/src/network.rs#L132-L149

This is problematic because it means we have a source-code dependency between the part of the code that handles the receiving of a message and the part that computes the response. Concretely, the code path from the above linked function leads to spawning the state machine for Bob where we perform some channel trickery to receive the response on this end once the user submits it via the HTTP API.

## Goal

Ideally, all we want to do when receiving a message from the other party is to store it in a persistent place. Other parts of the codebase, like the HTTP API can then perform appropriate actions as they inspect the current state.

## Recommendation

The use of channels inside the network layer should be an implementation detail an not leak to the application code.
Instead, the network layer should offer an API to send a response at any time. This will require one of two things:

a. If we stick to the request-response based message model, the API needs to give an identifier to the caller upon receiving an event that can be used to send the response back
b. ~The messaging model moves to something that is not request-response. That means the network layer can close the substream after receiving a message and sending a response back is entirely application logic.~

**Comment by tcharding** [comment]
Passing this issue back to you to refine @thomaseizinger.
