### ISSUE TITLE
Reduce the amount of stale branches

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1518]
# Problem

Too many stale branches.

# Goal

Less stale branches.

# Recommendation

Stop more stale branches by having bors/mergify/github actions clean them up.

**Comment by thomaseizinger** [comment]
If bors can't do it, we could also make a mergify action.

**Comment by thomaseizinger** [comment]
This already happens:

![image](https://user-images.githubusercontent.com/5486389/70626585-061aaa80-1c25-11ea-8a61-125801b26a32.png)
