### ISSUE TITLE
MatchingTransactions is actually only ever used as MatchingTransaction

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#1519]
**Problem**:
After #1514, the implementation of `MatchingTransactions` for Bitcoin blockchain connectors returns a stream of transactions to match the return type of the function defined by the trait. In reality the implementation generates a single future (expecting only one transaction to match the query) which is then converted into a stream via `stream::futures_unordered`. Furthermore, when calling `matching_transactions` in `HtlcEvents` implementations we immediately convert the stream into a single future by chaining a call to our custom combinator `first_or_else`.

This means that we go from a future to a stream of one item and back to a future.

**Goal**:
To simplify the code.

**Recommendations**:

Replace the trait with a single `async` function that takes a connector `C` with `C` implementing the necessary traits (`BlockByHash` etc).

**Comment by thomaseizinger** [comment]
This blocks https://github.com/comit-network/comit-rs/issues/1349 because the current setup of blanket impls (`MatchingTransactions` is one of them) makes the dataflow unnecessarily complex and https://github.com/comit-network/comit-rs/issues/1349 hard to implement.
