### ISSUE TITLE
Trash internal/key_gen crate

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1520]
## Problem

We have this binary crate in comit-rs that nobody has used for a while and his just here to slow down compilation or big secp related refactoring

## Goal

Get rid of it

## Recommendation

Trash it. Also trash the code in bitcoin_support that is only used by key_gen crate.

**Comment by thomaseizinger** [comment]
If people need to generate wallets/keys locally, this might be helpful: https://github.com/ArgusHQ/wagyu

**Comment by D4nte** [comment]
ok well, that's it, time to trash!!!

**Comment by D4nte** [comment]
Another reason why we should do it:

```
▶ cargo run -- --secret-seed-file ./bla
error: `cargo run` could not determine which binary to run. Use the `--bin` option to specify a binary, or the `default-run` manifest key.
available binaries: cnd, key_gen
```
