### ISSUE TITLE
libp2p Transport creation is not production ready

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#1547]
We build the libp2p `Transport` using `libp2p::build_development_transport`.  The [docs](https://docs.rs/libp2p/0.12.0/libp2p/fn.build_development_transport.html) explicitly state that this function should not be used in production.

> Note: This Transport is not suitable for production usage, as its implementation reserves the right to support additional protocols or remove deprecated protocols.

## Goal

Do not rely on code that is explicitly stated to be non-production code.

## Suggestion

Cut and paste the code out of the libp2p library (excluding all the feature flagged stuff we don't nee) and create our own `Trasport` in cnd.

**Comment by thomaseizinger** [comment]
@tcharding please refine this further before we go through it in grooming, i.e. work out concrete action items (kind of what the issue says yes but otherwise it is just one more ticket that is sitting around).

**Comment by tcharding** [comment]
No worries, done.
