### ISSUE TITLE
Fetched transaction receipts can end up unused

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#1551]
**Problem**:

We eagerly fetch transaction receipts even though for `TransactionPattern`s that don't care about logs we don't need them until we find the matching transaction and want to return the `TransactionAndReceipt`. This is wasteful.

https://github.com/comit-network/comit-rs/blob/49271bce29a2dad60fca77b830000d101a316101/btsieve/src/ethereum/mod.rs#L76-L104

Also function `matches(transaction: &Transaction) -> bool` defined on `&bitcoin::TransactionPattern` and  function `matches(transaction: &Transaction, receipt: &TransactionReceipt) -> bool` defined on `&ethereum::TransactionQuery` are still a bit awkward to read because "pattern matches transaction" is not really correct since it should be the other way around: "transaction matches pattern".

**Goals**:

- Clear code.
- Efficient code.

**Recommendation**:

- Create trait `FindTransactionMatching` that defines a function `find_transaction_matching(self, pattern: TransactionPattern) -> Option<Transaction>`.

Implement on `bitcoin::Block`, `ethereum::Block<Transaction>` and interestingly also on `ethereum::Block<TransactionAndReceipt>`, since an Ethereum block takes a generic type parameter which is normally either a transaction or a transaction ID, but which can hold our custom `struct` instead.

- Create trait `HasBloomFilterMatching` that defines a function `has_bloom_filter_matching(self, pattern: TransactionPattern) -> Outcome`, where

```rust
enum Outcome {
  Match,
  NoMatch,
  Inconclusive,
}
```

which can encode all the possible paths:

1. `Outcome::Match`: the block's bloom logs match the pattern; look at the transactions (and their receipts) in this block.
2. `Outcome::NoMatch`: the blocks' bloom logs do not match the pattern; skip this block.
3. `Outcome::Inconclusive: the pattern cannot be used to decide based on bloom logs; look at the transactions in this block.

Implement on `ethereum::Block<T>` and use to decide what to do with each block.

---

The names defined here are not definitive (nor should be the proposal, really), in particular `HasBloomFilterMatching` and `Outcome`.

**Comment by thomaseizinger** [comment]
This should be taken care of by https://github.com/comit-network/comit-rs/issues/1781.
