### ISSUE TITLE
Improving structure of our documentation repositories

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1552]
## Problem

1. The `RFCs` repository only contains COMIT protocol related documents which are actually specifications.
2. There is a bunch of unused discussions issues open in the RFC repo.
3. The spikes repository actually contains a range of RFCs related to decisions we made for any project. It may not be clear from an external point of view what spikes are about: Readme says `List of spike outcomes for COMIT network.`
4. The spikes are not organised and covers a wide range of subject
5. The spike's `Recommendation` is often changed before merging until a consensus is reached

## Goal

Ensure that things are clear from an outsider point of view.

## To Do

1. Rename the `RFCs` repository to `spec`.
2. Rename `RFC` documentations to `CIP` documents (**C**OMIT **I**mprovement **P**roposal)
3. ~Delete the discussion issues in the RFCs repository~
4. Update the spikes readme and templates to clarify and explicitly state that spikes are _summaries of a structured decision process to answer a specific question_.
5. Update the spikes readme/template to categorise spikes (field in template): cnd, process, create-comit-app, etc.
6. Update the spikes readme/template to rename the `Recommendation` to a `Decision`: Decision is accepted when the PR is merged.

**Comment by thomaseizinger** [comment]
`spec` is actually cool because it means we can specify more than the protocol (if we'd want to).

**Comment by D4nte** [comment]
> `spec` is actually cool because it means we can specify more than the protocol (if we'd want to).

I don't think the name `RFCs` stopped us to do that. I guess it's more a re-structure of it and put currenct RFCS under a current `COMIT protocol` folder?

**Comment by bonomat** [comment]
@D4nte : this has been in To-Refine for a while and was marked as stale once :) What's the status of this please?

**Comment by D4nte** [comment]
> @D4nte : this has been in To-Refine for a while and was marked as stale once :) What's the status of this please?

Thanks for the bump. Looks good to me.
