### ISSUE TITLE
Reduce the coupling of cnd's clients to its API

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1557]
> This is a follow-up ticket from: https://github.com/comit-network/comit-rs/issues/1504

## Problem

Currently, clients of cnd have to hardcode the paths `/swaps` and `/swaps/rfc003` for retrieving all swaps and creating a new one. This creates coupling and makes it a breaking change for us to change those paths (as for example suggested in https://github.com/comit-network/comit-rs/issues/1504. This coupling restricts the solution-space for tackling issues like https://github.com/comit-network/comit-rs/issues/1504. Making a breaking change might just not be a viable solution (depending on the adoption of cnd and the comit-js-sdk), given the pain we'd have in upgrading things like the sdk and having to match the version of cnd used inside create-comit-app.

## Goal

Not to constrain the future coblox team in the solution space regarding changes to cnd's API.

## Recommendation

We already make good use of siren in cnd's API to reduce the coupling when it comes to executing actions. We can reduce the coupling further by returning a siren document on `GET /`that has two links:

```json
{
  "class": [],
  "properties": {},
  "entities": [],
  "actions": [],
  "links": [
    { "rel": [ "collection" ], "class": ["swaps"], "href": "/swaps" },
    { "rel": [ "collection", "edit" ], "class": ["swaps", "rfc003"], "href": "/swaps/rfc003" },
  ]
}
```

### Rationale

We try to use as many standard link relations as possible. By combining them with siren's `class` attribute, we can easily differentiate between all our usecases.

1. `collection` is a link-relation that describes a link that points to a collection. Hence, we can describe the link that points to a collection of swaps by adding the class `swaps`.

2. `edit` describes a link that can be used to change a link's context. Together with the `collection` relation and the two classes `swaps` and `rfc003`, we can describe the link that allows a client to **edit** the **rfc003** **collection** of **swaps**.

**Comment by tcharding** [comment]
+1
