### ISSUE TITLE
Upgrade our usage of bitcoin js lib

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1572]
## Problem

We are getting these deprecation warnings:
```
Deprecation Warning: TransactionBuilder will be removed in the future. (v6.x.x or later) Please use the Psbt class instead. Examples of usage are available in the transactions-psbt.js integration test file on our Github. A high level explanation is available in the psbt.ts and psbt.js files as well.
DEPRECATED: TransactionBuilder sign method arguments will change in v6, please use the TxbSignArg interface
```

## Goal

No warning

## Recommendation

Update how we build transactions when using bitcoinlib-js. See how it was done in bobtimus: https://github.com/coblox/bobtimus/commit/71b704d961abdf0610d592928730be8f0ddd6a8b

**Comment by luckysori** [comment]
Obsoleted by #1594, since this code will eventually go away as we rewrite all e2e tests.

**Comment by luckysori** [comment]
Obsoleted by #1594, since this code will eventually go away as we rewrite all e2e tests.
