### ISSUE TITLE
MacOS: Store config in `Application Support` and not `Preferences`

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1577]
## Problem

As a Mac user, I find it very strange that the configuration file for cnd is stored in `Library/Preferences`. A folder I never went into before.

With any application I ever used, if I had to manually update a config file, this config file would be stored in `Library/Application Support`. Please note this is the case for bitcoind, lnd, etc..

Moreover, with #1569, the seed would be stored in `Application Support` and the configuration in `Preferences` which makes it even odder.

## Goal

Improve the user experience by storing files where the user would expect them

## Recommendation

For Mac OS, store config and seed in `Library/Application Support` folder.

**Comment by bonomat** [comment]
Closing this for now as we need some more input from users/devs.

**Comment by D4nte** [comment]
> Closing this for now as we need some more input from users/devs.

Meh. As a user I say the current way is odd.
