### ISSUE TITLE
Deprecate `network` property for Ethereum in HTTP API

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1580]
## Problem

The `network` property is accepted/returned on the HTTP API only for backward compatibility reasons.

## Goal

Avoid code/API complexity/technical debt due to unneeded features.

## Recommendation

Remove `network` property for Ethereum on the HTTP API, both for request, responses and ledger action payloads.

## Dependencies

Blocked by coblox/bobtimus#139
Blocked by comit-network/create-comit-app#119
Blocked by coblox/comit-i#126

**Comment by bonomat** [comment]
@D4nte : what was it made deprecated by?

**Comment by D4nte** [comment]
> @D4nte : is this deprecated because of the chainID ? Because the chainID was already added to the API?

Well, yes
Step 1: Add chainId
Step 2: Make clients/sdk use chainId
Step 3: Remove network

**Comment by D4nte** [comment]
This should still be done.
