### ISSUE TITLE
Move negotiation protocol prototype into comit-js-sdk

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#1593]
# Problem

After comit-network/create-comit-app#127 the proposed protocol lives only in an example in create-comit-app. This limits the usage to this particular example.

# Why

We want this protocol to be used across different projects. 

# Goal

Move the negotiation protocol from the example and integrate it into the comit-js-sdk. 

# Recommendation

While doing this, also move the auto-accept into the comit-js-sdk

**Comment by bonomat** [comment]
Created in the wrong repository.

**Comment by D4nte** [comment]
delete issue?
