### ISSUE TITLE
ProtocolDependencies structs are unnecessary 

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#1596]
## Problem

Currently we have two protocol dependency objects, one for Bob and one for Alice.  These contain the same fields except for and additional field in Alice that references the libp2p swarm.  There is a linear dependency depicted as Bob -> Swarm -> Alice i.e., Alice needs a reference to the swarm which needs a reference to bob.

Secondly, we have a facade `Dependencies` that acts as a superset of all the traits satisfied by the all the objects within the above mentioned protocol dependencies.  This is, quite clearly, overly complex.

The primary task of any software developer is to control complexity - this issue makes the assertion that we can do better in reducing the complexity around this code.

## Goal

Having unnecessary, if it is in fact unnecessary, complexity is a cost to the project.  It slows down development.  There is value to be attained here by reducing the code complexity around the dependencies needed to transfer data (messages) to/from the user (http client) and the peer node (libp2p). 

## Suggestion

Remove `bob::ProtocolDependencies` and `alice::ProtocolDependencies`.  Move `http_api::Dependencies` to `cnd/src/dependencies.rs`.  Make it the same as the superset of bob and alice currently with the swarm field of alice optional.  Implement all traits currently implemented on the removed alice/bob onto the newly created `Dependencies`.  Just thoughts ...

**Comment by D4nte** [comment]
To me you are saying "let's remove ProtocolDependencies by renaming it Dependencies", am I correct?

**Comment by tcharding** [comment]
No, currently we have `alice::ProtocolDependencies`, `bob::ProtocoloDependencies`, and `http_api::Dependencies`.  I am proposing unifying them into data structures that have more meaning i.e., it is not immediately clear _why_ the Bob protocol does not need access to the swarm. When thinking about the rfc003 protocol it took me ages to work out why we don't need access to the swarm from Bob (because we use a future and hold on to the incoming substream to send the response back).  There is obvious tie between the dependencies needed from within the swarm and the Bob role - hence I feel this naming could be improved.  PR to come :)
