### ISSUE TITLE
Document configuration

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1657]
## Problem

With our current auto-generated files that only generate mandatory values and the fact that the rest of the configuration values are defaulted, a user simply does not know what are the available options.
Hence, if such user were to try to use cnd on mainnet or testnet, they would need to look at Rust code to know what needs to be configured.

## Goal

Make it clear for the user what can be configured on cnd.

## Recommendation

A. A markdown file that explains the available options (like [bitcoind does](https://github.com/bitcoin/bitcoin/blob/master/share/examples/bitcoin.conf)).
B. The auto-generated files contains comments that explains all options

**Comment by thomaseizinger** [comment]
Option C:
Move the configuration from TOML to JSON and provide a JSON-schema that explains the config format?

**Comment by luckysori** [comment]
@D4nte: what was the actual pain-point?

**Comment by bonomat** [comment]
@da-kami: in addition to Lukas' comment: we pushed this back to you as from the description it is not clear what pain point you had and we did not want to have a documentation just for the sake of having a documentation :)

Can you refine this ticket please?

**Comment by D4nte** [comment]
To me it seems straightforward: if someone wants to actually use cnd on mainnet then they have to look at Rust code to understand what needs to be configured.

**Comment by thomaseizinger** [comment]
Can we consider this to be (at least for now) resolved through #1670 ?
