### ISSUE TITLE
Bob can derive a (incorrect) secret - prevent this at compile-time

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1682]
## Problem

The current design of Bob's `State` holds an implementation of `SecretSource`. `SecretSource` allows you to derive a secret and keys from the underlying seed.
Bob doesn't need to have access to this functionality in the rfc003 protocol because Alice is the one to generate the secret.

## Goal

Alter the design of the `SecretSource` and `State` structs in a way that models the real world better, making it impossible for Bob the derive a secret.

## Recommendation

1. Split up the `SecretSource` into three traits:
a. `DeriveSecret`
b. `DeriveRedeemIdentity`
c. `DeriveRefundIdentity`

> `DeriveRedeemIdentity` and `DeriveRefundIdentity` might be also be combined into `DeriveIdentities`.

2. Replace all the usages of `SecretSource` with the actual trait bounds that are needed.

3. Change the instance of `SecretSource` inside the `State` struct to only hold the minimal interface that is actually needed for the code to work. (Bob should only need `DeriveIdentities` here).

**Comment by bonomat** [comment]
I'm curious about this one. Do you have some more details please?
