### ISSUE TITLE
Towards a richer domain model

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1708]
## Problem

Currently, several of the core types in our codebase come from external libraries:

- bitcoin::Amount,
- web3::Address,

This is problematic in several ways:

1. The names of these types are fixed
2. We cannot change the API
3. We cannot implement foreign traits on those types

We can workaround some of these problems (f.e. (3)) with solutions like generic newtypes. However, I see the core problem in (1). Our domain model is in-consistent in several ways (Amount vs Quantity for example).

## Goal

Have a richer domain model that models the domain as accurately as possible, both in terms of type names and their APIs.

## Recommendation

Introduce our own types for all crucial concepts of our domain:

- amounts
- identities (public keys & addresses)

We don't have to implement all of the logic of those types ourselves. They can wrap library types to get access to certain functionality.
As part of this ticket, we should also trash the `ethereum_support` crate as most of that functionality is only used inside `cnd`.

Tagging this one as a spike because it is mostly a design task. The choices in names are important here and should be discussed and documented. Creating a spike seems like a good fit!

**Comment by tcharding** [comment]
I'd like to suggest adding a crate `xchain` that holds types ect. for cross chain development.  Reasons
- Its an awesome name
- We can put it up on `crates.io` and it could actually be useful to others
- All the reasons stated above in this spike description ...

**Comment by D4nte** [comment]
> I'd like to suggest adding a crate `xchain` that holds types ect. for cross chain development. Reasons
> 
>     * Its an awesome name
> 
>     * We can put it up on `crates.io` and it could actually be useful to others
> 
>     * All the reasons stated above in this spike description ...

I am not sure about that as each lib (rust-bitcoin, web3) already bring their own types and most likely our xchain crate would fix one specific lib usage (e.g. rust-bitcoin 0.19.0 and web3 2.3) creating more cross-dependencies than what we have.
Look at the latest PRs on blockchain-contracts, that should give you an idea of the issues we are facing.

**Comment by thomaseizinger** [comment]
> All the reasons stated above in this spike description ...

@tcharding put yourself in the shoes of someone who would be depending on that crate. Wouldn't they face the same issues we face now (not being able to modify the types, can't implement foreign traits, etc).

What I tried to capture in this spike is that any application you are building should have control over the types that resemble the domain. If you follow that, I don't think it makes sense to try and provide a crate to the ecosystem that only contains a domain-model (and not functionality).

On the contrary I'd say, good crates give you functionality without forcing a domain-model on you. Or, if they do, have it as generic as possible. For example, it makes perfect sense for `rust-bitcoin` to provide an `Address` type, because a bitcoin address is a concept with well-defined functionality.

`serde` is another good example: it gives you functionality without interfering with your domain model.

Parts of the frustration with face with the `web3` library is that exactly the opposite is happening there: They provide (layers of) crates that _only_ define types. This results in a deep dependency tree which makes it a PITA to upgrade any of these dependencies because they always have to fit together.

I hope that makes things clearer :)
