### ISSUE TITLE
Swap status in unclear

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1712]
## Problem

The swap status in http API can only be:
- `IN_PROGRESS`
- `SWAPPED`
- `NOT_SWAPPED`
- `INTERNAL_FAILURE`

To filter swaps the SDK provides the following function: `getNewSwaps()` and `getOngoingSwaps`.
Both methods use the `actions` to proceed with the filtering.
This feels _hacky_ because the actions can be role specific, e.g.:
- `getNewSwaps()` filter on `accept` actions, hence only work for `Bob`
- `getOngoingSwaps()` filter on `redeem` and `fund` action, so it was not working for `Bob` after bob accepted before Alice funds,

## Goal

Have a straightforward API that allows the consumer to retrieve swaps at various stage of the protocol

## Recommendation

See if we can make `status` field more detailed to avoid filtering by action?
Or acknowledge this complexity and move forward with our lives.

**Comment by thomaseizinger** [comment]
The status field is just a summary at the moment. You could always check the status field inside `state` for communication and both ledgers. Is that sufficient?

**Comment by D4nte** [comment]
> The status field is just a summary at the moment. You could always check the status field inside `state` for communication and both ledgers. Is that sufficient?

oh good point! Will check.

**Comment by thomaseizinger** [comment]
Closing this for now because I think we expose everything that is requested in this ticket. If not, please re-open :)
