### ISSUE TITLE
Replace web3 with reqwest

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1718]
## Problem

The Rust web3 library uses an outdated version of tokio and doesn't have a good API design (EventLoopHandle ...).
We only need a handful of RPC requests so we actually don't need to depend on it for cnd.

## Goal

Less nasty dependencies -> fewer headaches -> happier developers.

## Recommendation

Replace our usages of the `Web3` client with `reqwest` and simple structs that define the JSON rpc requests we need.

**Comment by thomaseizinger** [comment]
https://github.com/althea-net/clarity is a good candidate for basic types of ethereum like `Address` or a `U256` number type.

We could also contribute our `CalculateContractAddress` functionality to this crate.

**Comment by thomaseizinger** [comment]
> json_rpc requests can easily be reimplemented

We literally use 2 JsonRPC calls from Web3. Let's through this library out already ...

**Comment by thomaseizinger** [comment]
Once the new version of `reqwest` (with async/await support) is released, we can start with this!

**Comment by bonomat** [comment]
@thomaseizinger : shall we upgrade this ticket to an epic and track the libraries you want to replace/rewrite?

**Comment by thomaseizinger** [comment]
> @thomaseizinger : shall we upgrade this ticket to an epic and track the libraries you want to replace/rewrite?

I don't think we need to, for now my only concern is `web3`. All the crucial information is already in this ticket, it just needs to be written up properly.

**Comment by bonomat** [comment]
Ok, thanks for the info.
