### ISSUE TITLE
Can miss matching transaction if fetching receipt fails

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#1726]
## Problem

With #1633, when an Ethereum transaction has been identified as a matching transaction, if fetching its receipt fails, we just log and continue to look for a matching transaction.

## Goal

To not miss the matching transaction.

## Recommendation

Try to fetch the receipt again after a delay if you get an error from the blockchain connector.

**Comment by D4nte** [comment]
Due to recent changes #1780/#1860, we currently fail when such error occurs. Such explicit failure allows us to understand the behaviour and then later do proper error handling.
