### ISSUE TITLE
Remove dependency on `TaskExecutor` from `btsieve::ethereum::MatchingTransactions`

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1780]
## Problem

The implementation of `MatchingTransactions` depends on the `tokio::executor::TaskExecutor` trait to spawn background tasks. This is sub-optimal for a number of reasons:

- It couples us to the tokio-executor
- It makes it harder to clean-up resources of finished swaps

## Goal

To have code that is not more complicated than actually necessary.

## Recommendation

The ideal API of the `MatchingTransactions` trait (or with #1519, the function) is: `async (connector, pattern) -> transaction`. For this, we should not need to spawn background tasks, everything that needs to be implemented can be done as part of the future that is returned.

I believe it should be somehow possible to use the current implementation design (based on message passing through channels) without spawning them away but either composing through combinators or polling them manually.

**Comment by D4nte** [comment]
I think a `not` needs to be added to the Goal section.

**Comment by thomaseizinger** [comment]
> I think a `not` needs to be added to the Goal section.

@D4nte, it says: 

> To have code that is **not** more complicated than actually necessary.

Where would you add another "not"?
