### ISSUE TITLE
`TransactionPatterns` are unnecessarily generic and complex

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1781]
## Problem

The current design of `TransactionPattern` is very generic. It supports matching on all kinds of aspects of a transaction. In reality, we only use a fraction of this design.

The overly generic design is a legacy of times when btsieve was running in its own process and we had ideas of hosting it for users etc.

The problem with this design is that it has been and is a source of bugs and a lot of developer time has already been spent on debugging this part of the code.

## Goal

Propose a design that fits our purpose. That is, it completely reflects the way the patterns are used and turns invalid usage of them compile-errors.

Aspects the spike should address:

- The design should still allow us to use the main parts of btsieve (looking in the past, etc) for future protocols which will likely require different patterns
- Invalid usages of patterns should be compile-errors
- The output of a specific pattern should be linked to the usage.
For example, for the pattern of sending bitcoin to an address, we are interested in the specific `Outpoint`. Currently, we only return the full transaction from `MatchingTransactions` and look for the `Outpoint` again inside `HtlcEvents`. This is an unnecessary indirection. Similarly, we don't always need the `TransactionReceipt` for `TransactionPattern`s on Ethereum. Yet the current design forces us to always return a `TransactionAndReceipt` because some patterns need to return the receipt.

## Recommendation

Avoid to abstract above both Bitcoin and Ethereum as it would introduce unnecessary complication.

## The following issues have been closed in favor of this redesign:

- https://github.com/comit-network/comit-rs/issues/1726
- https://github.com/comit-network/comit-rs/issues/1459
- https://github.com/comit-network/comit-rs/issues/1551
- https://github.com/comit-network/comit-rs/issues/826

**Comment by tcharding** [comment]
Ethereum side is done in PR: https://github.com/comit-network/comit-rs/pull/2039
Tracking issue for the Bitcoin side of this issue: https://github.com/comit-network/comit-rs/issues/2083

**Comment by D4nte** [comment]
Done with #2039
