### ISSUE TITLE
Web 3 connector gets hammered by current `ReceiptByHash` implementation

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#1782]
## Problem

Currently we hit the web 3 connector every time we call `receipt_by_hash`.  #1762 adds block caching when retrieving blocks by hash from the blockchain connector.  For the web 3 connector the value of this block cache is minimal because we immediately hit the connector to get the transaction receipts (assuming receipt is needed or transaction matches pattern).

## Goal

Do not make a request to the web 3 connector for transaction receipts that we have already fetched.

**Comment by bonomat** [comment]
Is this still valid after #1349?

**Comment by thomaseizinger** [comment]
I think we can close it as a dupe now. Originally, #1349 did not include the receipt part.
