### ISSUE TITLE
Evaluation of safety concerns for Alice and Bob

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#1819]
Disclaimer: This could be seen as part of https://github.com/comit-network/RFCs/issues/129 - Nevertheless I sum it up separately for now. Probably better to mob-program on it and then writing the spike rather than the other way round...?

## Problem

We have discussed `default expiries` at some point, but we have not discussed (and not implemented) other safety constraints based on expiries and underlying ledgers for Alice and Bob. 

Besides the initial expiries there are certain time windows within which both parties have to act to be on the save side. These time windows are to some extent described in our model https://github.com/comit-network/spikes/blob/master/assets/basic_expiry_model.pdf - but there is no feedback from cnd if one is still within a save window or not. 

## Goal

Make it possible to build applications on top of COMIT. 

## Proposal

Disclaimer: I don't have a complete solution lined out in my head yet. 

Add some kind of indicator for Alice and Bob that "tells" the respective actor if it is still save to commence with the swap, or abort. 
Alternatively we could also just abort in certain scenarios.

List of scenarios:
* Alice does not fund in time (Bob aborts)
* Bob does not fund in time (Alice waits for refund)
* Alice does not redeem in time (Bob has to refund as soon as available)
* Bob does not redeem in time (Bob has to be warned, that Alice can take both assets then)

**Comment by D4nte** [comment]
I believe this could just be summmarise in a guideline of having a timeout after which we advise the app to proceed with refund.
Note that we have not finalised the proper default expiries, I'd propose to do the suggested timeout at the same time.

From a code perspective, in `comit-sdk` there are timeouts on the actions, It'd be interesting to understand on how it fits together.

**Comment by da-kami** [comment]
Currently no a priority.
Consider extending the documentation around expiries at a later point.
