### ISSUE TITLE
Design new implementations of our core Ethereum types

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1848]
## Problem

The types we use for Ethereum, like `EtherQuantity` and `Erc20Quantity` are all baked by implementations found in crates like `web3` or its dependencies.
The crates have been a pain to work with because the implementations are scattered across different crates and repositories which makes it hard to find versions that are compatible with each other. They are also all macro based, so its hard to reason about their implementation.

## Goal

Design new implementations of our core Ethereum types that **don't depend on web3** or any of its dependencies.

## Recommendation

Several approaches exist:

- Write all of those types ourselves (by using types like `num-bigint` for the actual math for example)
- Use other implementations of those types (for example clarity)
- ???

We would expect the types to live in the `cnd` crate.

**Comment by bonomat** [comment]
Hi @D4nte : what's the state of this ticket please? It's currently in `Review` and I see you linked 2 tickets which both have been merged.

**Comment by D4nte** [comment]
Done with attached PRs.
