### ISSUE TITLE
Adapt implementation of bitcoin `matching_transaction` to what the Ethereum side does

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1878]
## Problem

The implementation of `matching_transaction` for Bitcoin is still on the first iteration of the initial design based on async/await. We have since figured out a better way of doing this and have successfully done so in `matching_transactions` for Ethereum.

The current implementation of `matching_transaction` for Bitcoin is also blocking the final steps of the overall async/await migration.

## Goal

- Unblock the async/await migration
- Simplify the code

## Recommendation

Look at what `matching_transaction` for Ethereum does and do the same / something similar (it is easier for Bitcoin because Bitcoin doesn't have receipts).
This ticket also includes getting rid of `TransactionPattern` for Bitcoin (see here https://github.com/comit-network/comit-rs/issues/2083).

Note: Tests need to be adapted of course keep them (similar to what is done is Ethereum). Some unit tests are going away (pattern tests).

**Comment by thomaseizinger** [comment]
The PR was reverted: https://github.com/comit-network/comit-rs/pull/2126

**Comment by tcharding** [comment]
This was resolved in: https://github.com/comit-network/comit-rs/pull/2142
