### ISSUE TITLE
Switch to git-flow branching model

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1900]
## Problem

In order to automate releases, we need to make sure that merging a release branch does not accidentally extend the scope of the release.
In our current branching model, this could happen if any other PR is landed between opening and merging a release branch.

## Goal

Have deterministic releases

## Scope

* Switch to git-flow as recommended below
* Document what has to be done to release a new version of cnd. The goal of this document should be that everyone on the team can do a release. 
  * Create a `RELEASING.md` document in the repository. 

## Recommendation

Switch to a git-flow like branching model:

- Change the default branch to `dev`
- Make sure all of our bots respect this new setting (I believe, most of them read the setting from GitHub anyway)
- Introduce new branch protection settings for `master` that requires at least 1 one approval to merge. More protection settings can be added later (like special CI checks that should run before a release)

**Comment by tcharding** [comment]
> In our current branching model, this could happen if any other PR is landed between opening and merging a release branch.

I don't understand this statement @thomaseizinger.  If we are switching branching models why is current branching model even being considered?

**Comment by D4nte** [comment]
This is now done for comit-network/comit-rs.
