### ISSUE TITLE
Document the release process

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1903]
## Problem

At the moment, it is unclear of what one has to do to release a new version of COMIT.

## Goal

Allow everyone on the team to do a release

## Recommendation

Document the current state of the release process in a file `RELEASING.md` in the repository.

**Comment by thomaseizinger** [comment]
This is blocked by https://github.com/comit-network/comit-rs/issues/1901 because our current release automation is broken and I don't see a point in documenting broken things. We should fix it first and then document the current state.

**Comment by bonomat** [comment]
I think we should do this together with #1901, i.e. as soon as #1901 is in a mergible form create this document (same person). If we keep the blocker as is, this ticket will only end up in a sprint 2 weeks after the other one was done and the person taking this ticket has to recall how releasing works.

@thomaseizinger : What do you think?

**Comment by thomaseizinger** [comment]
> I think we should do this together with #1901, i.e. as soon as #1901 is in a mergible form create this document (same person). If we keep the blocker as is, this ticket will only end up in a sprint 2 weeks after the other one was done and the person taking this ticket has to recall how releasing works.
> 
> @thomaseizinger : What do you think?

I would see the documentation as focusing on: what has to be done and not how does it work.
How it works can be figured out by looking at the workflow file.
That is whole point of the automation: not needing to know the specifics about how releases work.

The important bit (I think) is what needs to be done to do a release. That should be easy to remember but if you think strongly about your point, feel free to merge the tickets.

**Comment by bonomat** [comment]
I extended the scope of #1900 to include the work in of this ticket.
