### ISSUE TITLE
Run the e2e tests in parallel

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1927]
## Problem

At the moment, all of our e2e tests run sequentially. This takes a long time of our CI build and also when run locally.

## Goal

Fast e2e tests.

## Recommendation

Migrate the test runner from mocha to Jest.

Mocha cannot run tests in parallel, hence we will need to switch our test suite to a different runner, for example `Jest`.
Jest can be run [programmically](https://github.com/facebook/jest/issues/5048) as-well, although the API is not quite as nice as the Mocha one is.

Running Jest programmatically allows us to keep our `harness` entrypoint which can boot up the ledgers for us (if needed). We can then simply pass on the test files to Jest which will run them in parallel.

Replacing mocha with Jest will also allow us to remove all those `setTimeout` hacks we have in every test file.

Similar to how it's done now, replace the call to Mocha with a call to Jest in `harness.ts`.

**Comment by bonomat** [comment]
I see another advantage of this: it tests if cnd is able to deal with a _noisier_ blockchain.
