### ISSUE TITLE
Migrate the ERC20 tests to the new e2e tests

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1929]
## Problem

All e2e tests involving ERC20 are still written in the old format.

## Goal

Have all e2e tests use the same framework.

## Recommendation

We need to deploy an ERC20 contract for the tests to work.
Likely, the easiest option is to simply deploy a new ERC20 contract for each test instead of reusing an existing one.

**Comment by bonomat** [comment]
@thomaseizinger is this ticket really blocked by running the e2e tests in parallel?

**Comment by thomaseizinger** [comment]
> @thomaseizinger is this ticket really blocked by running the e2e tests in parallel?

Nope sorry! The dependency relationship is inverted ..
