### ISSUE TITLE
Replace remaining web3 types with our own ones

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1938]
## Problem

We are still depending on web3 for several for some of the types in our repository:

https://github.com/comit-network/comit-rs/blob/ad8d7d34aa227777c3eb7b8b57f1cc0624fd6bbf/cnd/src/ethereum/mod.rs#L5-L8

## Goal

Not depending on web3.

## Recommendation

- check which of the types re-exported from web3 are actually in use
- inline types like `Block`, `Transaction` etc (at this stage, we might also remove the annoying `Option` wrappers around certain fields)
- remove web3 from our production dependencies

**Comment by D4nte** [comment]
Maybe there is a reason for this option wrapper? Being able to fail under control instead of at deserialisation.

**Comment by thomaseizinger** [comment]
@D4nte 

> Maybe there is a reason for these option wrappers? Being able to fail under control instead of at deserialisation.

AFAIK, this is because you can fetch blocks and transactions for _pending_ blocks where these values are not yet known. We don't do that so we should be fine :)

**Comment by thomaseizinger** [comment]
I am blocking this on https://github.com/comit-network/comit-rs/issues/1781 because the solution to https://github.com/comit-network/comit-rs/issues/1781 is actually removing code (contract address calculation) that is currently still using web3 types and hence blocking this ticket.
