### ISSUE TITLE
Cnd does not support https for ethereum source

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#1940]
# Problem

it seems like that cnd does not support https urls for ethereum:

```
[2020-01-28 10:25:59.751][ERROR][cnd::swap_protocols::rfc003::create_swap:72] swap 094b9b5b-6c8c-408c-b449-5228eade95a7 failed with failed to find transaction for htlc deployment

Caused by:
    0: error sending request for url (https://ropsten.infura.io/v3/xyz): error trying to connect: invalid URL, scheme is not http
    1: error trying to connect: invalid URL, scheme is not http
    2: invalid URL, scheme is not http
```

This prevents us from using ethereum providers like infura.io

Further: if this breaks, the swap should basically be stopped. However, a client still retrieves the next actions and moves on unknowingly it will not be able to redeem. In my case, the client funded the Ether HTLC.

Imho: we should do a config sanity check during first start-up. 

```bash
Received latest order details: ether:bitcoin for a rate of 0.2:0.002
Swap started! Swapping 0.2 ether for 0.002 bitcoin
2. Continuing funding the Ethereum HTLC
Ethereum HTLC funded! TXID:  0x347a9118e9d4068747c43ea1e6e5902fe8ba1937891a06561356e358b276e605
4. Continuing redeeming the Bitcoin HTLC
```

//Note: url has been edited

**Comment by thomaseizinger** [comment]
> Further: if this breaks, the swap should basically be stopped. However, a client still retrieves the next actions and moves on unknowingly it will not be able to redeem. In my case, the client funded the Ether HTLC.
