### ISSUE TITLE
Cnd let clients continue with swap despite error

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#1945]
_follow up ticket from #1940_

# Problem

In #1940 matching an ethereum transaction failed with an error. However, cnd still returns the actions to continue with the swap. 

# Insights

c&p a comment from Thomas: https://github.com/comit-network/comit-rs/issues/1940#issuecomment-579024286

use an invalid url for the ethereum endpoint to reproduce.

> [...] I guess we don't update the state correctly somewhere so the API keeps emitting actions. 

# Recommendation

Outcome:
- Return 500 on the swap endpoint
- No longer return actions for swap that failed
- Still return the swap in the list of swaps (with no actions)

**Comment by thomaseizinger** [comment]
It is not mentioned in the issue but it would be good to not just return a 500 but also a body with a problem ( application/problem+json).
