### ISSUE TITLE
Extend cnd's configuration to account for an lnd instance

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1952]
## Problem

In order to do Lightning swaps, cnd needs to talk to an lnd instance. It should therefore be possible to configure:

- which port lnd is listening on
- where to find the macaroon that is used for authentication

## Goal

A minimalistic configuration interface which allows Lightning to be configured.

## Recommendation

According to the Lightning spike we are only [going to use HTTP](https://github.com/comit-network/spikes/blob/lnd-plan-of-attack/0022-lnd-plan-of-attack.adoc#L387) for communicating with lnd.

- The configuration MUST make it explicit that we need the HTTP port.
- The configuration MUST have a default value being the default lnd HTTP port.

What about the macaroon?

We MUST must maintain the zero-config approach of cnd.
To get access to the macaroon, we have two options:

- The user places it in cnd's config directory.
- We try to find a specific maracroon in lnd's config directory.

Both are well-known locations and therefore could act as the default value for the macaroon path.

I'd **recommend** the following algorithm:

1. Check if our config file explicitly defines a macaroon
2. Check if we have a macaroon with a default name inside cnd's config directory
3. Check if `LND_DIR` is defined
a. If yes, try and read the macaroon from the config directory with a specific name (decide on it)
b. If no, then default to default lnd config dir and look for the macaroon
c. If everything fails, tell the user which options they have to configure the macaroon.

**Comment by thomaseizinger** [comment]
This is blocked by https://github.com/comit-network/comit-rs/issues/1844 because we first need to sort out the existing ledger configuration to resolve the problem of knowing which network we want to connect to.

LND, similarly to bitcoind maintains a data directory per network. Hence, we need to resolve https://github.com/comit-network/comit-rs/issues/1844 first before this ticket can be implemented as the results apply here as-well.

**Comment by tcharding** [comment]
Does this issue assume that `lnd` is running on the same machine as `cnd`?

**Comment by thomaseizinger** [comment]
> Does this issue assume that `lnd` is running on the same machine as `cnd`?

You mean in regards to the default values? Yes you can assume both run on the same machine :)

**Comment by tcharding** [comment]
> You mean in regards to the default values? Yes you can assume both run on the same machine :)

In the end I elected to use a `Socket` instead of just a port number so that the user can run `lnd` where ever they please.
