### ISSUE TITLE
Finish re-modelling COMIT's core to account for HAN and HErc20

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1953]
## Problem

The protocol naming spike, with foresight for the Lightning integration identified that instead of a single swap protocol, we should be talking about a swap protocol _per ledger_.
This is a requirement for integration Lightning that allows us to re-use our existing swap protocols on the other ledger if we are doing a Lightning swap.

## Goal

Build on top of the work done in #2195 (and #2198) in order replace `rfc003` with `han` and `herc20` in the state and core. `rfc003` shall remain on DB, HTTP and COMIT APIs.

## Recommendation

I can't foresee a clear strategy until the work blocking this issue is done. That work used to be part of this issue, so it can only be easier to tackle this once all that is done, but it will still be a very major refactoring with unknowns. For that reason I would suggest this one should be treated as exploratory, with at least 2 people working on it at the same time.

You should not be touching the DB, HTTP API, COMIT API. The rfc003 request swap message has to stay as it is the one used on all APIs. Below that, then rfc003 should be gone.

**Comment by D4nte** [comment]
Ok for those interested, after reading the code and trying to understand what could be done, I decided to split the `rfc003/events` trait in 2 `han/events` and `herc20/events` and see where it leads.....

**Comment by D4nte** [comment]
Please note this is blocked as @thomaseizinger is currently doing a major refactoring that is creating merge conflicts.

**Comment by D4nte** [comment]
Learnings on how to do this issue so far:
- Backward compatibility with HTTP/COMIT API seems possible by having some superseeding traits (e.g. Ledger) at `swap_protocols` level to be deleted later
- Backward compatibility with DB seems a waste of time. Possible options:
   - Remodel sql db from `rfc003_` to `han_bitcoin_..herc20_ethereum`: seems like waste of effort
   - Keep `rfc003_` compability: huge work, waste of effrt
   - Migrate to nosql first
- In any case, it seems like extracting comit as a lib first, then do the han/herc20 changes and make the comit-lib crate compile to finally integrate it with the cnd crate by working on the various APIs sounds easier and more strategic

**Comment by D4nte** [comment]
Marked blocked until strategy is reviewed.

**Comment by thomaseizinger** [comment]
Thanks for reporting that! It is a little hard to judge remotely on how to proceed.
I'll think about it and have a look at the draft PR later.

**Comment by D4nte** [comment]
Assigning to @thomaseizinger as he wants to have a go.

**Comment by thomaseizinger** [comment]
@D4nte what do you think remains to be done after the two issues that already block this (https://github.com/comit-network/comit-rs/issues/2036 and https://github.com/comit-network/comit-rs/issues/2065)?

I have a feeling that we should try and remove the `Ledger` trait after https://github.com/comit-network/comit-rs/issues/2065. If we don't have one, I believe this issue is definitely unblocked and if we no longer have trait bounds on struct, I wouldn't know what the `Ledger` trait is good for :man_shrugging:

**Comment by D4nte** [comment]
> @D4nte what do you think remains to be done after the two issues that already block this (#2036 and #2065) are implemented?
> 
> I have a feeling that we should try and remove the `Ledger` trait after #2065. If we don't have one, I believe this issue is definitely unblocked and if we no longer have trait bounds on struct, I wouldn't know what the `Ledger` trait is good for 🤷‍♂

Once the Ledger trait is gone, the biggest challenges will be to keep the backward compatibility with the various APIs (comit, http, db).

I do not know at this stage if there is any work we can do beforehand to facilitate such task. I guess it will need to be a pair programming task knowing that this is an unknown/challenge.
Also thinking of a strategy so that you can:
1. change the core
2. adapt comit api and "know" it's done
3. adapt db and "know" it's done
4. adapt http api and "know" it's done

would be good. However this is such a massive work that you will not be able to rely on the compiler for that. In any case it will still be an exploratory issue.

**Comment by thomaseizinger** [comment]
Closing this because we are taking an incremental approach in remodelling the core.
