### ISSUE TITLE
Add a model-skeleton for the HALight protocol

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1954]
## Problem

In order to execute Lightning swaps, our software needs to model the protocol that is described in the according spike: https://github.com/comit-network/spikes/blob/lnd-plan-of-attack/0022-lnd-plan-of-attack.adoc

## Goal

Define a skeleton around the core concepts of the protocol:

- Ledger states
- Events
- `Lightning` ledger

## Recommendation

Inspire yourself from the existing protocols: `HAN` and `HErc20`.
This is only about implementing a _skeleton_, hence having `unimplemented!()` in several places is totally fine!

Implementing the event traits (analogous to `HtlcDeployed` for HErc20 for example) of HALight, will uncover, what the API of a future LN connector is.
It is within the scope of this ticket to define a stubbed `LndConnector` that already has the API needed for our event traits.

**Comment by D4nte** [comment]
Done as part of #2297.
