### ISSUE TITLE
Clean-up dry tests

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#2013]
# Problem

The PR https://github.com/comit-network/comit-rs/pull/1978 introduced code which asks for optimization as the goal of this PR was on moving to the new e2e test framework so that we can run the tests in parallel.

Generally the idea is to make those "old", moved dry tests similar to how we write e2e tests.

Concrete issues that were recorded:

**Assertions**
Instead of having the assert functions in the defined in the test, add them to the `Actor` as it is done in other e2e tests. This should make the code more readable.

https://github.com/comit-network/comit-rs/blob/5c2f4e06f24c84c751af76f906808b1d5310b8d0/api_tests/tests/peers_using_ip.ts#L10-L26
**Properly leverage the SDK for communication with cnd*

**Leverage the Cnd instance in Actor**

Instead of using the `actor.cndHttpApiUrl().get(...)`, we should use the `Cnd` instance that is provided in the `Actor` and use the `fetch()` method; inspire yourself from other tests. Consider using `ComitClient` if possible.

**Remove globally added test data**

Remove the globally added test data from `utils.ts`; consider moving all tests that rely on that data into one file and move the test data there.
Creating global test data leads to reusing it in different tests, which is bad for maintanability. 

https://github.com/comit-network/comit-rs/blob/b3a5012409787e86431bbb0817e04ba243eb64c3/api_tests/src/utils.ts#L52-L82

**Comment by bonomat** [comment]
Hi @thomaseizinger : this ticket has been on to-refine for a while now. What's the status here?  Might this even become obsolete soon once we have a new API?

**Comment by thomaseizinger** [comment]
> Hi @thomaseizinger : this ticket has been on to-refine for a while now. What's the status here? Might this even become obsolete soon once we have a new API?

The comments I made on the PR are still valid. I put it in to-refine because the issue you created doesn't actually say what should be done and the title is very generic.

Unfortunately, I never got around to actually do the refinement then. Since you opened it originally, do you mind if you do the refinement?
Otherwise I can do it when I get the time for it.

I labelled it as technical-debt because we took a shortcut in the PR to move faster.

**Comment by da-kami** [comment]
@thomaseizinger I gave it a try and updated this, hope I got all the things right :)

**Comment by da-kami** [comment]
Note: Some chai `expect` statements were already removed, might be interesting to take a look at when tackling this issues: https://github.com/comit-network/comit-rs/pull/2346

**Comment by thomaseizinger** [comment]
Thanks a lot @da-kami, much better :)
