### ISSUE TITLE
Migrate bitcoin_high_fee.ts to lib_sdk

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#2015]
## Problem

[`eth_btc/bitcoin_high_fee.ts`](https://github.com/comit-network/comit-rs/blob/58e8aa10b0f80c437a1123386f24e1d72e30aa73/api_tests/e2e/rfc003/eth_btc/bitcoin_high_fee.ts#L4) still uses the old test framework.

Also, `lib` folder should be removed and `lib_sdk` renamed to `lib`.
Please note some files in the `lib` folder are still relevant and might need to be preserved.

## Goal

Migrate all tests to use comit-sdk

## Recommendation

- Migrate this test to use comit-sdk
- Ensure that `lib/` folder with old framework is erased.

**Comment by da-kami** [comment]
need a different task than writing documentation for a while, so I pulled this in :)

**Comment by da-kami** [comment]
@D4nte there are quite a lot of dependencies from `lib` to the new tests. There are code parts that e.g. use code from `/lib/utils.ts`, `/lib/setup_chai.ts`, `/lib/bitcoin.ts` (...).

I'd move the necessary code parts into appropriate files in `lib_sdk`. Please let me know if you have something else in mind :)

**Comment by D4nte** [comment]
> @D4nte there are quite a lot of dependencies from `lib` to the new tests. There are code parts that e.g. use code from `/lib/utils.ts`, `/lib/setup_chai.ts`, `/lib/bitcoin.ts` (...).
> 
> I'd move the necessary code parts into appropriate files in `lib_sdk`. Please let me know if you have something else in mind :)

Yes of course there are some code that we need to keep from `lib`.
