### ISSUE TITLE
stdout muted and logs/test folder missing

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#2018]
Since #1978 was merged:
- `console.log` done in test fails for debugging purposes are not printed anymore
- `log/tests` is not created any more.

58e8aa10b0f80c437a1123386f24e1d72e30aa73: Not working
70dde0f2e0caad28e3506c52bfcb380a6541d770: Working fine

This is blocking #1951

**Comment by thomaseizinger** [comment]
@D4nte I've assign you to refine this because it is unclear to me, which tests you are talking about (only dry, all e2e, etc).

**Comment by D4nte** [comment]
Fixed with https://github.com/comit-network/comit-rs/pull/2019
