### ISSUE TITLE
LND sanity test is only two party

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2023]
## Problem

Lightning involves communication between a network of nodes not just two parties.  If we only test Lightning with two nodes we may be testing only a subset of Lightning's behaviour. 

## Goal

Have end to end tests that closely mimic the Lightning network.

**Comment by bonomat** [comment]
@tcharding : can you please rephrase this ticket to suit our usual ticket template?
```
## Problem
...
## Goal
...
## Recommendation (optional)
...
```

**Comment by bonomat** [comment]
I think there is not much value in testing this as we don't want to test that the Lightning Network supports multi-hop payments.
