### ISSUE TITLE
Docker images does not build at release time

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#2024]
See failure: https://app.circleci.com/jobs/github/comit-network/comit-rs/3887

**Comment by thomaseizinger** [comment]
Fixing this is already planned into the release automation: https://github.com/comit-network/comit-rs/issues/1901

We can track it separately, but I wouldn't fix it without moving to the new release automation.

**Comment by bonomat** [comment]
@thomaseizinger : do we want to do it in the phase of  https://github.com/comit-network/comit-rs/issues/1901?

**Comment by thomaseizinger** [comment]
Yes. If no one minds, I am closing this in favor of https://github.com/comit-network/comit-rs/issues/1901.

**Comment by thomaseizinger** [comment]
I've blocked https://github.com/comit-network/comit-rs/pull/2022 on https://github.com/comit-network/comit-rs/issues/1901.
