### ISSUE TITLE
Non-uniform usage of core domain terms

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2028]
Cryptocurrency is our core domain.  We should all use the correct terminology, spelling, acronyms etc. for our domain if we wish to present ourselves in a professional manner.

## Problem

Currency names are not capitalised [1].  Cryptocurrency names should therefore also not be capitalised.  We should be referring to 'bitcoin' and 'ether' as currencies.   Blockchains on the other hand should be capitalised, so we have 'Bitcoin' and 'Ethereum'.   (This has the added benefit, apart from just being correct, of reducing the overload of the term 'bitcoin'.)  We can also use the ticker symbols (all caps e.g. BTC and ETH).

## Goal

Use correct terminology anytime we talk, write docs, or write code comments.  Have all currencies (assets) written using lowercase and all blockchains written using capitals.

[1]: https://ell.stackexchange.com/questions/17517/why-arent-currency-names-capitalized

**Comment by D4nte** [comment]
Your link does not convince me for the capitalisation or not of cryptocurrencies tho.

**Comment by tcharding** [comment]
At the very minimum we should be uniform.  If there is no solid argument against it I would like to propose that we _do not_ capitialise currencies in line with common usage.  'Please give me 10 dollars'

**Comment by D4nte** [comment]
One of the reason proposed is that it is not a proper noun. You can say "the dollar".

However, to me you cannot say "the bitcoin" or "the ether" You say "Bitcoin".

I believe such new currency is also challenging grammar. Contrary to the dollar, there is only one Bitcoin.

**Comment by tcharding** [comment]
> One of the reason proposed is that it is not a proper noun. You can say "the dollar".
> 
> However, to me you cannot say "the bitcoin" or "the ether" You say "Bitcoin".

At first I read this and thought 'good points' - then I thought 'enough talk, just give me the bitcoin' ...

> I believe such new currency is also challenging grammar. Contrary to the dollar, there is only one Bitcoin.

There was probably only one dollar when they first named it, there may well be more than one crypto currency in the future with the same name.  I do agree however that in general grammar can change with new things.

**Comment by da-kami** [comment]
Adding my 2 cents (also in concern of https://github.com/comit-network/comit-rs/issues/2070 which requests immediate action):

The problem is not so much the code but the documentation. Distinguishing `Bitcoin` (ledger) and `bitcoin` (asset) would make it easier and more understandable to write documentation. We CAN document that we did that choice. I think it is a valid choice and we should go for it, so it easier to notice what we are talking about in e.g. documentation. If we opt for this in the documentation the code would naturally have to be adapted as well (my opinion...).

**Comment by D4nte** [comment]
Note:
https://english.stackexchange.com/questions/194653/does-bitcoin-need-to-be-capitalized
https://www.btcnn.com/should-bitcoin-be-capitalized/
https://bitcoin.stackexchange.com/questions/20901/correct-use-of-the-word-bitcoin
https://www.quora.com/When-should-the-word-bitcoin-be-capitalized?share=1

**Comment by tcharding** [comment]
So, for clarification we have reached consensus - we should aim to use 'Bitcoin' for the protocol and 'bitcoin' for the currency/asset.  @D4nte is that what you meant by posting those links above?

**Comment by tcharding** [comment]
We have reached consensus on this, closing.
