### ISSUE TITLE
Add skeleton routes for Lightning swaps

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#2038]
## Problem

For cnd to support LN swaps, we need to provide an API. The current API model of the `/swaps/rfc003` endpoint is fairly complex because it used nested objects and the fields in the payload are not static; they depend on _values_ of other fields (the type of `alpha_ledger_redeem_identity` depends on the value of `alpha_ledger.name`).
Extending the current endpoint with support for LN will only make this more complicated.

## Goal

- Add support for LN to cnd
- Not make stuff more complicated

## Recommendation

1. Add routes as proposed in the spike (https://github.com/comit-network/spikes/blob/master/0022-lnd-plan-of-attack.adoc#215-our-current-rest-api-endpoints-are-not-capable-of-expressing-the-concept-of-a-protocol-per-ledger) to cnd.
1. Return a 400 BAD REQUEST with an error that says it is not supported at the moment.
1. Write e2e tests that assert this error.

Note: The current `rfc003` route will exist temporarily even with the new `han` and `herc20` routes to be added in a different issue.
Note: This is blocked on comit-network/comit-js-sdk#117 as it needs to be tested but it's not possible until the SDK is extended.
Note: Keep the body empty at this stage.

**Comment by thomaseizinger** [comment]
This is blocked by https://github.com/comit-network/comit-js-sdk/issues/117 because we cannot create swaps otherwise.

**Comment by bonomat** [comment]
@thomaseizinger : I think the block should be the other way around, i.e. first create the API in cnd and then extend the interface in the sdk.

**Comment by thomaseizinger** [comment]
> @thomaseizinger : I think the block should be the other way around, i.e. first create the API in cnd and then extend the interface in the sdk.

I was thinking about that but then hit a wall when it comes to testing.
How are you going to the test the endpoints if the SDK doesn't support it?

We could opt for not using the SDK for these tests but I am not sure how useful that is.

**Comment by bonomat** [comment]
True, I see. That means we need to release a new version of the SDK in between though. 
Thanks for explaining your reasoning.
