### ISSUE TITLE
Dry tests use non-unixy names

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2050]
## Problem

The `api_tests/log/tests/` directory contains files with non-unixy names.

```
make e2e
$ ls api_tests/log/tests
[Alice] Response for GET _swaps_rfc003_{} contains a link to the protocol spec.log
[Alice] Response for GET _swaps is a valid siren document.log
[Alice] Response for GET _ with accept header set as application_vnd.siren+json is a valid siren document.log
[Alice] Returns 400 invalid body for an unsupported combination of parameters.log
[Alice] Returns 400 invalid body for malformed requests.log
[Alice] Returns 404 when you try and GET a non-existent swap.log
[Alice] Returns its peer ID and the addresses it listens on when you GET _.log
[Alice] Returns its peer ID and the addresses it listens on when you GET _ with accept header set as application_vnd.siren+json.log
[Alice] Returns the links for _swaps and _swaps_rfc003 when you GET _ with accept header set as application_vnd.siren+json.log
[Alice] Should be able to make a swap request via HTTP api to Charlie using his peer ID and his ip address.log
[Alice] Should be able to make a swap request via HTTP api using a random peer id and Bob's ip address.log
[Alice] Should be able to make first swap request via HTTP api.log
[Alice] Should be able to send a swap request to Bob and Charlie.log
[Alice] Should have no peers before making a swap request.log
[Alice] Should not yet see Bob's peer id in her list of peers.log
[Bob] Decline one swap.log
Response for GET _swaps_rfc003_{} is a valid siren document and properties match the json schema.log
Returns an empty list when calling GET _swaps when there are no swaps.log
rfc003-btc-eth-alice-overfunds-bob-aborts.log
rfc003-btc-eth-alice-redeems-bob-redeems.log
rfc003-btc-eth-alice-refunds-bob-refunds.log
rfc003-btc-eth-alice-underfunds-bob-aborts.log
rfc003-btc-eth-bob-overfunds-both-refund.log
rfc003-btc-eth-bob-refunds-alice-refunds.log
rfc003-btc-eth-bob-underfunds-both-refund.log
rfc003-btc-eth-cnd-can-be-restarted.log
rfc003-btc-eth-erc20-alice-redeems-bob-redeems.log
rfc003-btc-eth-erc20-bob-refunds-alice-refunds.log
rfc003-btc-eth-resume-alice-down-bob-funds.log
rfc003-btc-eth-resume-alice-down-bob-redeems.log
rfc003-btc-eth-resume-bob-down-alice-funds.log
rfc003-btc-eth-resume-bob-down-alice-redeems.log
rfc003-eth-btc-alice-redeems-bob-redeems.log
rfc003-eth-btc-alpha-deploy-fails.log
rfc003-eth-btc-bob-refunds-alice-refunds.log
rfc003-eth-erc20_btc-alice-redeems-bob-redeems.log
rfc003-eth-erc20_btc-bob-refunds-alice-refunds.log
sanity-lnd-alice-pays-bob.log
```

## Goal

Have only nice test file names in the `log/tests` directory i.e., remove things like `[Alice] Should not yet see Bob's peer id in her list of peers.log` in favour of things like `rfc003-eth-btc-bob-refunds-alice-refunds.log`.

## Recommendation

Update the name of the tests in the `*Actor[s]Test` function call to be kebab-case as it is what is used for the filename. Note that the test names need to be unique.

**Comment by tcharding** [comment]
So it turns out this is not a bug, but that the new dry tests [mis]-use the `name` field of `twoActorTest`.  This field is supposed to be used like this
```
twoActorTest("rfc003-eth-btc-bob-refunds-alice-refunds", async function({
```

But in the dry tests is being used like this (this is the way we named _old_ tests):
```
twoActorTest(
     "[Alice] Response for GET /swaps/rfc003/{} contains a link to the protocol spec",
     async function({ alice, bob }) {
```

**Comment by D4nte** [comment]
We did a fix to replace `/` with `.`! Didn't we?

**Comment by tcharding** [comment]
Yes, the file names are showing up as
```
[Alice] Response for GET _swaps_rfc003_{} contains a link to the protocol spec.log
```
Clearly we did not investigate enough :)  I raised [an](https://github.com/comit-network/comit-rs/issues/2050) issue so this can get fixed.

**Comment by D4nte** [comment]
> Yes, the file names are showing up as
> 
> ```
> [Alice] Response for GET _swaps_rfc003_{} contains a link to the protocol spec.log
> ```
> 
> Clearly we did not investigate enough :) I raised [an issue](https://github.com/comit-network/comit-rs/issues/2050) so this can get fixed.

I would just do a PR, I think prioritising and grooming the issue would take more total time than just fixing the name,

**Comment by tcharding** [comment]
> I would just do a PR, I think prioritising and grooming the issue would take more total time than just fixing the names.

Ha ha this is funny, we come a full circle back around to my gut feeling when I first discovered this and why I posted it on Basecamp and did not raise an issue, hilarious.  (Although I had the reason behind the bug wrong.)

**Comment by thomaseizinger** [comment]
> So it turns out this is not a bug, but that the new dry tests [mis]-use the `name` field of `twoActorTest`. This field is supposed to be used like this
> 
> ```
> twoActorTest("rfc003-eth-btc-bob-refunds-alice-refunds", async function({
> ```
> 
> But in the dry tests is being used like this (this is the way we named _old_ tests):
> 
> ```
> twoActorTest(
>      "[Alice] Response for GET /swaps/rfc003/{} contains a link to the protocol spec",
>      async function({ alice, bob }) {
> ```


> We did a fix to replace `/` from the test name with `.` in the filename, didn't we?

I would recommend to just change the test name. We log things differently now because each actor has it's own logger where the name is prefixed.

Good discovery though @tcharding :)

Regarding process: GitHub is IMO a good place for async technical discussions. Once we settle on a solution and the change is not too big, you can just sneak the ticket into the sprint (esp. if it is something annoying like this).

Obviously, if you find a solution by yourself, you can just send a PR. Not everything needs to strictly go into an issue but if in doubt, open one ;)

**Comment by tcharding** [comment]
> Regarding process: GitHub is IMO a good place for async technical discussions. Once we settle on a solution and the change is not too big, you can just sneak the ticket into the sprint (esp. if it is something annoying like this).
>
> Obviously, if you find a solution by yourself, you can just send a PR. Not everything needs to strictly go into an issue but if in doubt, open one ;)

Got it, thanks.
