### ISSUE TITLE
TODO/FIXME rule too strict for draft PR

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2051]
## Problem

TODO/FIXME words in patches causes CI to fail.

It would be useful to be able to see the test suite run on CI for draft PRs however the TODO/FIXME rule causes CI to fail early.  

## Goal

It would be nice if we could have TODO/FIXME left in draft PR and still have CI run the test suite.

**Comment by thomaseizinger** [comment]
As a pragmatic solution, we could move the check to the end of the CI pipeline?

**Comment by tcharding** [comment]
> As a pragmatic solution, we could move the check to the end of the CI pipeline?

Clever fella!  That works for me.
