### ISSUE TITLE
Re-design transaction matching for Bitcoin

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2083]
## Problem

PR https://github.com/comit-network/comit-rs/pull/2039 re-designed the matching logic for Ethereum, we still need to do the matching logic for Bitcoin.

Original Issue: https://github.com/comit-network/comit-rs/issues/1781

## Goal

Remove the generic `TransactionPattern` and use datastructures, algorithm, and API that accepts what we want to match on and returns what we are interested in.
The Ethereum side was done first because it is more complicated with the receipts and things. It should be fairly trivial to do something similar for Bitcoin given what has been done for the Ethereum side.

**Comment by thomaseizinger** [comment]
Actually, I think we can just do this as part of https://github.com/comit-network/comit-rs/issues/1878. I don't see a reason to do it in two steps.

**Comment by D4nte** [comment]
It looks like this was done as part of the sprint just gone. @thomaseizinger @tcharding please confirm.
