### ISSUE TITLE
Implement the swap digest algorithm

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#2112]
## Problem

The "announce" protocol described in the communication protocol describes an algorithm for computing a swap digest. We need an implementation of this algorithm.

See the related spike: https://github.com/comit-network/spikes/blob/master/0023-communication-protocol.adoc

## Goal

A working and tested implementation of the described algorithm.
We don't yet exactly know, how to things will fall into place, so the implementation should **not** build on existing data structures like `Request` or `ledger::Bitcoin` but instead be independent of the domain.

## Recommendation

Create a generic and Rust-idiomatic implementation of the algorithm using traits and functions. Ideally, in the end we should only need to implement the trait on the types we want to include in the digest and delegate to a function that implements the necessary parts of the algorithm.

### What is in scope of this ticket?

- Implement the interfaces (traits) for the algorithm
- Implement crucial details of the algorithm like the lexical sorting and hashing
- Define a way by giving examples in tests for how the implemented algorithm is used on:

1. structs with several fields
2. structs with a single field
3. enums

We are going to encounter all of the above when we are using the implementation on the actual structs so the implementation created in this ticket should be prepared to handle them.

The code will be isolated and not used at this stage. Rust tests should be here to prove it is working of course.

It is a good candidate for TDD or design/API first development.

### What is not in scope of this ticket?

- **Implementing** the conversion of a specific swap-related item like a Ledger to binary as the input for the algorithm.

**Comment by D4nte** [comment]
Actually not yet done as enums are missing and nested structs should be added.
