### ISSUE TITLE
Support LN swaps in the database component

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#2134]
Scope: The "SQLite DB" component of this diagram:

![Diagram](http://www.plantuml.com/plantuml/png/RPB1JiCm38RFpLDOEy5X23ZkK6biGve40jQzW9kODQ9DAiTZmDEJf1qRY5la_u_z_Kx4IaimMJ2XMBS314S720Vi9qgX5iymRwqcm03xGAng_m7Q6LNKVkyCyYTCDgjg2_FdzIIP67kh2ksTi6zZu-7G4cTL2xUg82TMuiN5q-Dw2zep3QBlhAZ2e62D8L9LBmzM29PtMJRrMT_gWDpbSaYdSvoXwv579nvo1YAuKYd2j4oCCyYPAMTLgJATbWdljv0gqzBKCwZm_MWcsRE3fpSrocLccC7SkKYXQQmV1qNZs3-Ddy7jzGqiDglvThLKolauYksk4V2l0ssnXhG98GF1TnGtGeAs3T0G4rYd2gOTiWaW7gIXj9QkspkhunjwTvNZfhvAPR0KB8CS-Vx4k8ZBx66zl3pvnmjLwXH8Hoiq69f_TMloUreAV-Lxwx2rNpySfptsoDYH48VpROwkCd-4wEpnu0RMRm00)

**Comment by D4nte** [comment]
Discussion: @thomaseizinger @D4nte 

0. Define REST API Payload
1. (🛑 by 0) Create `struct CreateSwap` in controller, generate the UUID
2. (🛑 by 1) Define DB schema
3. (🛑 by 2) `impl Save for CreateSwap`
0.a (🛑 by 0) Define a schema for REST API swaps list, implement its handling in SDK
0.b (🛑 by 0.a & 2) Allow retrieval of 1 swap from DB
0.b.i (🛑 by 0.b) Implement get 1 swap on REST API
0.c (🛑 by 0.b) Allow retrieval of n swaps from DB
0.c.i (🛑 by 0.c) Implement get swaps on REST API

**Comment by thomaseizinger** [comment]
@D4nte I created some initial tickets from the above concerning the REST API. I left the ones for the database to you :)

**Comment by thomaseizinger** [comment]
We completed this already!
