### ISSUE TITLE
Remove chai from end2end tests

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#2139]
This is a follow-up ticket from https://github.com/comit-network/comit-rs/pull/2106

# Problem

After moving to jest we should only use jest matchers and no chai matchers

# Goal

Don't have any chai matchers and remove chai from package.json

# Recommendation

Remove https://github.com/comit-network/comit-rs/blob/a9aa5720fedc297cb7005b9461d727f97911b7ba/api_tests/package.json#L59-L66 (including the types a few lines up) and fix the e2e tests.

Note: straightforward replace, don't refactor everything.

**Comment by D4nte** [comment]
Note: json schema validation with jest looks hard.

I tried using https://github.com/epoberezkin/ajv/releases/tag/5.0.0

But our schema is `draft-04` and the steps in the migration section of the release above threw an error.

**Comment by D4nte** [comment]
@thomaseizinger is it fine if we update our json schema to draft-06?

**Comment by thomaseizinger** [comment]
> @thomaseizinger is it fine if we update our json schema to draft-06?

Yes,
