### ISSUE TITLE
Define the payloads of the API endpoints for LN swaps

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#2154]
## Problem

To trigger LN swaps, users will need to send some information to cnd. We have not yet fleshed out, what exactly this data this.

## Goals

- Define the payloads of all 4 LN routes.
- Aim for a flat JSON design (i.e. no nested objects).
- Aim for a static JSON design (i.e. the payload is the same under all circumstances

## Out of scope

Implementing the payloads in the routes.
This ticket blocks several others so in the spirit of max parallelization of work, the implementation of these payloads is defined in another ticket.

Note that those routes take a different approach to our current ones because some of the data is now represented in the URL.

## Recommendation

Document your findings as a comment on this ticket.
Please make an effort to properly flesh out the exact data we are going to need.

**Comment by thomaseizinger** [comment]
I am blocking this on https://github.com/comit-network/comit-js-sdk/issues/122 because it is currently impossible to properly assert on errors returned by cnd and this ticket requires you to differentiate between two different errors.

**Comment by D4nte** [comment]
I am still working on another issue, no need to hog this.
