### ISSUE TITLE
Remove web3 from the test dependencies

### ISSUE THREAD

**Issue by rishflab** [comit-network/comit-rs#2156]
Follow on from #1938

## Goal
We want to remove web3 from dev dependencies. 
 
## Recommendation
The web3 dependency is currently used to conduct the ethereum transaction matching smoke test. 
Recreate the functionality provided by web3 crate using web3connector and use that that send transactions to the node.

**Comment by rishflab** [comment]
This ticket seems to fall under general refactoring so I am not sure which epic this would go under

**Comment by thomaseizinger** [comment]
> Recreate the functionality provided by web3 crate using web3connector and use that that send transactions to the node.

Note that for the smoke test, we need a special RPC call from the "personal" namespace of parity.
We shouldn't extend the functionality of our production code (Web3Connector) only for test purposes.

I would recommend to solve this by creating a layer between `Web3Connector` and the actual requests. Something that works on the level of the `JsonRpcRequest` types that we created. A client working with those should be good enough for the smoke test!
