### ISSUE TITLE
Replace types provided by primitive-types and ethbloom with our own types

### ISSUE THREAD

**Issue by rishflab** [comit-network/comit-rs#2157]
Follow on from #1938 

## Problem

`web3` brings a lot of dependencies which are a pain to handle.

## Goal

Remove primitive types from dependencies 

## Recommendation

Recreate H256, H160, U256 etc.. and the functionality require (conversions, serialisation etc...).

Define all new types in the `ethereum` module for now. We can move the new types to where they are used at a later stage.

**Comment by rishflab** [comment]
This ticket seems to fall under general refactoring so I am not sure which epic this would go under

**Comment by D4nte** [comment]
> This ticket seems to fall under general refactoring so I am not sure which epic this would go under

It's a follow-up of https://github.com/comit-network/comit-rs/issues/1938 so I'd put it under the same epic.

**Comment by thomaseizinger** [comment]
I think the `ethbloom` dependency is fine to keep btw, we don't need to implement our own bloom filter matching :)

**Comment by da-kami** [comment]
@thomaseizinger is the goal to get rid of the `primitive_types` library?
