### ISSUE TITLE
Define a new response schema for listing all swaps with respect to the newly added LN swaps

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#2159]
## Problem

Currently, the response of fetching all swaps (and also for fetching a single swap) use basically the same schema (the `/swaps` endpoint just omits the "state" field). This schema is very polymorphic within its structure to allow for all the different possible combinations of `alpha_ledger`, `beta_ledger` etc. This has the advantage that the actual keys of the JSON are fixed regardless of the swap which makes parsing for clients relatively easy. On the other hand, it makes working with the data harder because the _types_ of the individual fields depend on values of others. It is the same story we have on every one of our APIs :sweat_smile: 

With the addition of LN swaps, continuing this structure would become more complex because not all the fields are necessary for LN. LN doesn't use addresses for example, so those would always be null. This defeats the advantage listed above where all the fields are always there, just with different types.

The general problem we have is that we obviously need to somehow ship data to the client.

## Goals

Conceptually define, how we ship data about swaps to the client.

Take into account that:

- the client should be able to get a list of swaps
- the client should be able to get a single swap

Consider the following design ideas/goals:

### Minimize optional fields

Allowing the client to parse the response into a structure with non-optional fields makes working with the data very easy as it avoids conditional checks further down the line.

### Prefer a static JSON

Static in this case means, the keys don't change and the types of their values are always the same. At the moment, this is not the case for fields like `alpha_ledger_redeem_identity`: the type of this field is sometimes a Bitcoin public key and sometimes an Ethereum address.

### Consider omitting data in certain responses

If the client receives a list of some sort, having each element in the list be the same structure makes parsing very easy. So you might want to omit data that is different between swaps from the list of swaps.

**Output should be comments on this issue or draft PR on e2e tests**

## Recommendation

Experiment with drafting Typescript interfaces to validate your ideas.

**Comment by thomaseizinger** [comment]
This is blocked by https://github.com/comit-network/comit-rs/issues/2154 because we need to first figure out, what exactly the information is we are passing around.

**Comment by bonomat** [comment]
@thomaseizinger : what's the progress on refining this issue?

**Comment by thomaseizinger** [comment]
> @thomaseizinger : what's the progress on refining this issue?

Whoops, completely forgot about it :grimacing: On it!
