### ISSUE TITLE
Design new `Swap` data structure 

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2169]
Note: After talking with @D4nte this ticket is probably covered by the controller designing a data structure for 'partial swap' and 'full swap'.

## Problem

We currently represent a swap with alpha and beta in single data structures.  In order to move to having separate protocols (han/herc20) we need a data structure to represent a swap.  Creating an issue for this because since we are doing a lot of work in parallel this will be needed by many other issues.

## Goal

Have a data structure that each owner of the 4 LN integration epics can use to pass around swaps.

This issue might get done during: https://github.com/comit-network/comit-rs/issues/1953

**Comment by thomaseizinger** [comment]
Closed because we are aiming to not have a god struct that is passed to every function.
