### ISSUE TITLE
Remove code duplication in swap creation 

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#2175]
## Problem

When working on #1878 we noticed, that it causes problems to join the futures for watching alpha and beta ledgers. We opted for spawning them separately, duplicating the code for alpha and beta ledger in `create_swap.rs`. 

From a comment from @thomaseizinger on https://github.com/comit-network/comit-rs/pull/2142 :
> The split is possible but I think not trivial because of the SwapEvent type still requiring AL, BL, AA, BA and its use in StateStore.
> This is a nice step towards #1953, where we are going to need such functions, albeit they have to be ledger independent for that.

## Goal

Less code-duplication (but keeping alpha and beta ledger spawn separately).

## Proposed Solution

Not exactly sure what is the best way to achieve this and how far we should go with this. 
The code that is currently duplicated is the Generator-loop; this should definitely be harmonised somehow. 
From the looks at the whole `create_swaps` we could also go further and kill it with a macro (the only difference in `watch_alpha_ledger` and `watch_beta_ledger` is yielding different states specific to Alpha and Beta...; there is no difference in logic, so I feel this could be harmonised as well).

**Comment by thomaseizinger** [comment]
@luckysori I added this to your epic as it concerns the core of COMIT.

**Comment by thomaseizinger** [comment]
Done in https://github.com/comit-network/comit-rs/pull/2266.
