### ISSUE TITLE
Fix LND-based sanity tests

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#2192]
_Follow-up ticket of https://github.com/comit-network/comit-rs/pull/2106_

## Problem

This PR introduces skips LND sanity issues. This should not be the case.
It currently timeout at `genSeed` phase, sometimes it works.

- lnd is slow to catch-up with blocks from wallet initialisation
- 2 steps to init wallet: `genSeed` (to generate seed words) and then `initWallet` using the previous seed.
- `genSeed` accepts a byte array as entropy, this can be pseudo random to not use as much entropy on the local machine.

## Goal
Have a stable and preferable fast (parallelizable) LN e2e test setup. 

## Recommendation
- Start LND nodes in the test setup not within the tests so that they can be shared between tests.

**Comment by bonomat** [comment]
Different idea: 

I looked into this issue and I find it really hard to debug. Given we want to move to a complete different setup (start blockchain nodes before the tests #2191) I would propose to ditch the current lnd setup in our e2e tests and start from scratch. 

To simplify the setup, we could also move to a simple docker setup, e.g. use the provided containers from here: https://github.com/lightningnetwork/lnd/tree/master/docker

We don't necessarily have to use the same bitcoin nodes for other e2e tests and the lnd-based e2e tests.

@D4nte : what do you think?

**Comment by D4nte** [comment]
> Different idea:
> 
> I looked into this issue and I find it really hard to debug. Given we want to move to a complete different setup (start blockchain nodes before the tests #2191) I would propose to ditch the current lnd setup in our e2e tests and start from scratch.
> 
> To simplify the setup, we could also move to a simple docker setup, e.g. use the provided containers from here: [lightningnetwork/lnd:docker@`master`](https://github.com/lightningnetwork/lnd/tree/master/docker) [](/lightningnetwork/lnd/tree/HEAD@{2020-03-11T05:51:01Z}/docker)
> 
> We don't necessarily have to use the same bitcoin nodes for other e2e tests and the lnd-based e2e tests.
> 
> @D4nte : what do you think?

Yes I support move to docker for lnd & bitcoind just for lnd tests.

**Comment by thomaseizinger** [comment]
> > Different idea:
> > I looked into this issue and I find it really hard to debug. Given we want to move to a complete different setup (start blockchain nodes before the tests #2191) I would propose to ditch the current lnd setup in our e2e tests and start from scratch.
> > To simplify the setup, we could also move to a simple docker setup, e.g. use the provided containers from here: [lightningnetwork/lnd:docker@`master`](https://github.com/lightningnetwork/lnd/tree/master/docker) [](/lightningnetwork/lnd/tree/HEAD@{2020-03-11T23:53:00Z}/docker) 
> > We don't necessarily have to use the same bitcoin nodes for other e2e tests and the lnd-based e2e tests.
> > @D4nte : what do you think?
> 
> Yes I support move to docker for lnd & bitcoind just for lnd tests.

How is that going to make a difference?
We are not experiencing problems in the interaction between bitcoind and lnd right?

**Comment by thomaseizinger** [comment]
Do you want me to put this issue on hold and we define a different approach?

**Comment by bonomat** [comment]
> How is that going to make a difference?

it simplifies the setup and maybe it's time to admit that running bare-metal nodes was not the best move.

> We are not experiencing problems in the interaction between bitcoind and lnd right?

I'm not sure about this. That's what I meant with the first part: 
>  I would propose to ditch the current lnd setup 

because I really don't have an idea where the problem is.

**Comment by thomaseizinger** [comment]
Okay, I understand.

I did not yet spend any time on it today. I will time-box the rest of the day to see if I can get it working. If not, I am happy to go for a different approach / drop the ticket.
