### ISSUE TITLE
Rename e2e tests

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#2193]
_Follow-up ticket of https://github.com/comit-network/comit-rs/pull/2106_

## Problem

We use the name of each test case as the name for the log file. This make the test names hard to read.
E.g. `rfc003-btc-eth-erc20-alice-redeems-bob-redeems` makes sense for the log file while something like `[RFC003/BTC-ERC20] Alice funds and Bob redeems` makes more sense for the test name. 

## Goal

1. Make it easy to open a log file from a failing test
1. Have speaking test names and logical dependent log file names.

## Recommendation

Come up with a test name pattern and use string replace to remove non-unix characters to produce a valid log file name. 

Also print the log file name when a test is failing (it is currently caught).

**Comment by luckysori** [comment]
Pinging as "reviewers": @bonomat @thomaseizinger 

I have spent some time investigating how to do this, but I haven't found a solution that pleases me, so I would recommend to **keep the current behaviour**.

> 1. Make it easy to open a log file from a failing test

Firstly, there is more than one log file per test and some log files are shared across tests (blockchain node log files). At least I would like to see a list of all the logfiles specific to a test right next to Jest's test fail report:

```
 FAIL  tests/dry/sanity.ts (10.912s)
  ● Sanity › returns-listen-addresses-on-root-document

    testing 1

      106 |         "returns-listen-addresses-on-root-document",
      107 |         oneActorTest(async ({ alice }) => {
    > 108 |             throw new Error("testing 1");
          |                   ^
      109 | 
      110 |             const res = await request(alice.cndHttpApiUrl()).get("/");
      111 | 

      at tests/dry/sanity.ts:108:19
      at tests/dry/sanity.ts:11:71
      at __awaiter (tests/dry/sanity.ts:7:12)
      at tests/dry/sanity.ts:107:42
      at src/actor_test.ts:27:28
      at fulfilled (src/actor_test.ts:5:58)

  [LOG-FILE]: /home/luckysori/work/comit-network/comit-rs/api_tests/log/dry/sanity/tests/returns-listen-addresses-on-root-document/cnd-alice.log
  [LOG-FILE]: /home/luckysori/work/comit-network/comit-rs/api_tests/log/dry/sanity/tests/returns-listen-addresses-on-root-document/cnd-bob.log
  [LOG-FILE]: /home/luckysori/work/comit-network/comit-rs/api_tests/log/dry/sanity/test_environment.log

```

To do this I tried to work with Jest reporters, Jasmine reporters and even good old `console.log`, but everything I tried could not be aligned with Jest's actual output, meaning that it would be very confusing to know what log file corresponds to what error message.

> 2. Have speaking test names and logical dependent log file names.

Without (1) I think this would be detrimental as it would make it even harder to know where the log files are. At least at the moment we can rely on the test name.

---

Maybe I am tunnelling too much on this one solution and there's a much easier way. In any case, I don't want to spend more time on this given that I see it as low priority and we are not supposed to put a lot of effort into it.

I do think that it can be done with a better understanding of reporters, but it would be time consuming.

**Comment by bonomat** [comment]
Thanks @luckysori for the writeup. I'm happy with keeping it as is and agree on the low priority.
