### ISSUE TITLE
Split up rfc003 implementation of StateStore into alpha and beta

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#2195]
## Problem
The core of `cnd` uses the `StateStore` trait to push updates on the state of the two ledgers involved in a swap, so that another layer (in our case `cnd`'s HTTP API) can access it on demand. Since the `StateStore` was only ever implemented for the soon-to-be-gone `rfc003` protocol, it is tightly coupled to its requirements, to the point where it is actually defined inside the `rfc003` module.

Assuming that we still want to use this `StateStore` abstraction with `HAN`, `HErc20` and `HALight`, the way it's defined and implemented needs to change.

## Goal
To update the way the core provides updates on the state of a swap, accounting for single-ledger protocols.

## Recommendation
Some work has been done in this direction with #2200 already.

Instead of introducing the new protocols straight away, I would suggest to split up `rfc003`'s implementation of `StateStore` into alpha and beta ledger. Introducing the new protocols is **out of the scope** of this ticket and will be done with #1953.

This will involve splitting up `SwapEvents` and `ActorState` accordingly; pushing updates to two different state stores from `create_swap.rs`; combining these states at a higher level in order to derive actions from them.

Don't get scared by the type parameters 🤡

**Comment by D4nte** [comment]
New ticket -> The `StateStore` is currently a trait with multiple functions/methods. You may want to split up the trait in single-function traits first. @luckysori to create a new ticket with major reno label.

**Comment by da-kami** [comment]
@luckysori I would be keen on picking this one - would you be up for pair programming on it? 

> New ticket -> The StateStore is currently a trait with multiple functions/methods. You may want to split up the trait in single-function traits first. @luckysori to create a new ticket with major reno label.

seems this was not done yet...?

**Comment by luckysori** [comment]
> @luckysori to create a new ticket with major reno label.

New ticket: https://github.com/comit-network/comit-rs/issues/2213

**Comment by luckysori** [comment]
> @luckysori I would be keen on picking this one - would you be up for pair programming on it?

Yes!

**Comment by da-kami** [comment]
Handing this over to @luckysori for now - the solution is outlined and we agreed that the actual coding task does not need pairing at the moment. If you feel I can help again please ping me :)
