### ISSUE TITLE
Watch for single-ledger protocol events

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#2198]
## Problem
We still watch for `rfc003` events, even if they are split up into alpha and beta.

## Goal
- Introduce `HAN` and `HErc20` into the codebase.
- Remove unnecessary steps from a protocol, i.e. deploying HTLC for HAN.

## Recommendation

In `create_swap.rs`, replace `create_alpha_watcher`, `create_beta_watcher`, `watch_alpha_ledger`, `watch_beta_ledger` with single-ledger protocol specific functions: one for `HAN` (generic over the asset) and one for `HErc20`. 

`create_alpha_watcher` and `create_beta_watcher` are only called by `init_accepted_swap` in `init_swap.rs`, which is implemented for multiple generic type parameters. In order to be able to know which of the new single-ledger protocol specific functions (e.g. `watch_herc20`) needs to be called, some of these generic type parameters need to be specified. For example, instead of

```rust
pub fn init_accepted_swap<D, AL, BL, AA, BA, AH, BH, AI, BI, AT, BT>(
    dependencies: &D,
    accepted: AcceptedSwap<AL, BL, AA, BA, AI, BI>,
    role: Role,
) -> anyhow::Result<()>
where
// omitted for simplicity
{
// create_alpha_watcher()
// create_beta_watcher()
}
```

try

```rust
pub fn init_accepted_swap<D>(
    dependencies: &D,
    accepted: AcceptedSwap<bitcoin::Regtest, Ethereum, asset::Bitcoin, asset::Erc20, identity::Bitcoin, identity::Ethereum>,
    role: Role,
) -> anyhow::Result<()>
where
// omitted for simplicity
{
// create_han_watcher::<bitcoin::Regtest>()
// create_herc20_watcher()
}
```

---

We expect #2175 to be naturally resolved when doing this ticket.

Current thought is to have one generic watcher per protocol (e.g. `create_han_watcher`) but if it is too hard it's ok to have duplications for now and remove down the line.

**Comment by tcharding** [comment]
I spent a day and a half on this before putting it back in the sprint backlog in favour of working with the HALight squand.  Pused a non-functioning branch with what I did: `2198-watch-han-herc20`.  Feel free to ping me whomever picks this up if you want to.

**Comment by D4nte** [comment]
@thomaseizinger @tcharding Is this still relevant?

**Comment by thomaseizinger** [comment]
Yes it is relevant but I would close this and open a different one instead: Introducing `herc20` to the codebase so we can do a halight-herc20 swap!

**Comment by thomaseizinger** [comment]
Follow-up ticket here: https://github.com/comit-network/comit-rs/issues/2422
