### ISSUE TITLE
Investigate e2e test error `worker process has failed to exit gracefully`

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#2211]
## Problem

The new e2e test setup prints this `error` upon execution on some machines ( @D4nte and me had this issue on Mac):

```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --runInBand --detectOpenHandles to find leaks.
```

The tests still pass, but it seems there is some problem.

## Goal

No error message.

## Proposed solution

1. Investigation (check on jest side)
2. Fix (could be done in a separate issue if big)

**Comment by bonomat** [comment]
This was indeed identified during the development and there was no obvious process that kept running. My assumption is that it is either ethers or bcoin that are still running.
