### ISSUE TITLE
Status for (bitcoin_ethereum) e2e tests

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#2212]
## Problem

With the new e2e test setup the `bitcoin_ethereum` tests run really long (9+ mins) without getting any feedback.
When running the tests it feels that they are just "stuck".

## Goal

Get some feedback if the tests are already running.

## Proposed solution

Best would be to see which test is currently running, but in general, any indicator would help.

**Comment by bonomat** [comment]
I hope this gets better once we #2191
