### ISSUE TITLE
Define COMIT core's API for initiating a swap involving HALight

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#2241]
## Problem

No interface exists to initiate a swap that involves HALight inside the core of COMIT.

## Goal

To be able to initiate swaps that involve HALight as one of the ledger-specific protocols inside the core of COMIT.

## Recommendation

- Figure out what parameters will be needed inside the core of COMIT to watch lnd during a swap involving HALight. These parameters will need to be **loaded from the database** after the communication layer has instructed COMIT's core to initiate a swap involving HALight.
- Define a function much like [`init_accepted_swap`](https://github.com/comit-network/comit-rs/blob/e3a8122cfc1865277c680160fa509b045d918602/cnd/src/init_swap.rs#L17-L98) which will initiate **a single HALight watcher** using the parameters defined above and some functionality provided by the facade. Keep in mind that this function is expected to be called by the communication layer.

**Comment by D4nte** [comment]
There is no API To define actually so closing this.

See discussions in https://github.com/comit-network/comit-rs/issues/1954
