### ISSUE TITLE
Test docker image build as part of the CI

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#2242]
## Problem

We build a docker image for cnd as part of the release process. This is then used in create-comit-app.

The image build process is failing because we never test it and only do it at release time.

## Goal

- Use CI to ensure that the docker image build is never broken.
- Verification should include that cnd runs: Start container and do a curl `GET /`

## Recommendation

Build the docker image as part of the regular PR runs in GitHub actions.

Note: Preferably do this as part of the release script. we should build it for the release, start it up, start cnd and only commence with releasing if cnd starts up.

**Comment by bonomat** [comment]
@D4nte : please refine this issue.
