### ISSUE TITLE
cnd always fails to validate Ethereum node config on start-up

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#2256]
## Problem

This log message is always emitted when `cnd` is started for e2e tests:

```
Could not validate Ethereum node config: connection error
```

The warning indicates that something has gone wrong, yet the tests never seem to be affected by it.

## Goal

Useful, correct logs.

## Recommendation

Replace the `jsonrpc::client` call with a normal http request as what is returned is a just a string, not a json object.
You can still use `jsonrpc::Request` to serialize the request body.

---

Whatever we do to validate the Bitcoin node config works, because the logs don't show a warning for it, so the overall approach seems to be correct.

**Comment by rishflab** [comment]
cnd can not succesfully request the config from the ethereum node which is causing it to log this warning. The config is most likely correct as the test is passing, the request to get the chain_id is failing.
Might be due to an incorrect Url, ill have a look.

**Comment by rishflab** [comment]
Our web3connector uses the jsonrpc::Client which expects a json value but the ethereum node returns a raw string https://github.com/ethereum/wiki/wiki/JSON-RPC#net_version

**Comment by thomaseizinger** [comment]
> Our web3connector uses the jsonrpc::Client which expects a json value but the ethereum node returns a raw string [ethereum/wiki/wiki/JSON-RPC#net_version](https://github.com/ethereum/wiki/wiki/JSON-RPC#net_version)

Argh :angry: 
Why can't people make consistent APIs, what a mess :joy:

**Comment by rishflab** [comment]
> > Our web3connector uses the jsonrpc::Client which expects a json value but the ethereum node returns a raw string [ethereum/wiki/wiki/JSON-RPC#net_version](https://github.com/ethereum/wiki/wiki/JSON-RPC#net_version)
> 
> Argh 😠
> Why can't people make consistent APIs, what a mess 😂

I have no idea.

Not sure the best way of going about solving this. Will jsonrpc::Client have to changed or is there away to deserialise the returned (non-json) string without modifying the jsonrpc::Client? Also should we change our ChainId(u32) to ChainId(String)? (if we do this we will have to make changes all the way down to the state store)

**Comment by thomaseizinger** [comment]
> Also should we change our ChainId(u32) to ChainId(String)? (if we do this we will have to make changes all the way down to the state store)

I would make the parsing into a number a part of the deserialization when we get the response. It is supposed to be a number, so if it is not, something is wrong :)

> Will jsonrpc::Client have to changed or is there away to deserialise the returned (non-json) string without modifying the jsonrpc::Client?

We can provide a lower-level API that does not assume that the response is a JSON-RPC response but thinking about it more, it probably makes more sense to just use a plain HTTP client and only use the `jsonrpc::Request` object to send the request and deserialize the response the way we want.
I am not aware that just returning a string is a conforming to the jsonrpc spec so we don't need to build escape hatches for other people's mistakes.
