### ISSUE TITLE
Repetition across ledgers for HTLC funding verification

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#2271]
## Problem

The logic for checking if a contract has been funded correctly is the same for all ledgers i.e. `funded_amount == expected_amount`. But it's duplicated across all ledgers.

## Goal

Reduce duplication of knowledge in code.

## Recommendation

Leverage the `Ord` trait like we did before.

**Comment by bonomat** [comment]
Hi @luckysori : this ticket has been on to-refine for a while now. What's the status here please?

**Comment by luckysori** [comment]
> Hi @luckysori : this ticket has been on to-refine for a while now. What's the status here please?

Thanks for the reminder. Done.

**Comment by luckysori** [comment]
Don't know if it belongs to an epic, so I just labelled it as `technical-debt`.

**Comment by thomaseizinger** [comment]
@da-kami I am gonna remove `good-first-issue` because I think this requires anything but trivial refactorings.

**Comment by thomaseizinger** [comment]
I think, with the move to individual locking protocols, this is actually no longer a problem. I'd say it is the concern of each locking protocol to assert that the money was locked correctly.
