### ISSUE TITLE
Merge libp2p-comit crate into comit-rs

### ISSUE THREAD

**Issue by rishflab** [comit-network/comit-rs#2304]
## Problem
The libp2p-comit crate provides libp2p trait implementations that are in a different to place to other libp2p trait implementations in our code base which is a bit confusing.

## Goals
Remove the libp2p-comit crate and move its functionality to the comit-rs

**Comment by tcharding** [comment]
This was done on purpose to make it explicit as we move from rfc003 to han/herc20/halight which code is for what.  The libp2p-comit crate is the old rfc003 stuff.

**Comment by rishflab** [comment]
> This was done on purpose to make it explicit as we move from rfc003 to han/herc20/halight which code is for what. The libp2p-comit crate is the old rfc003 stuff.

Yeh thomas mentioned it. Is this issue still blocked or can we go ahead and consolidate the crates?

**Comment by tcharding** [comment]
In my opinion we should _not_ move the rfc003 libp2p stuff from where it is and continue with the separation until we get rid of rfc003.
