### ISSUE TITLE
Queues are mixed up

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2306]
## Problem

We [recently added](https://github.com/comit-network/comit-rs/pull/2283) the announce protocol.  In doing so we inadvertently mixed up the usage of standard queue data structures.  There are two issues here, both in `cnd/src/network/protocols/announce/handler.rs`:

- We use a `Vec` for `events`.  We then proceed to add to the back and remove from the front i.e., a FILO.  This is not how a `Vec` should be used.
- we use a `VecDequeue` for `dial_queue`.  We add to the front and remove from the front i.e., a stack or FIFO, this can be achieved more simply by using a `Vec`.

## Goal

Investigate the correct behaviour we want from these two queues, do we want FIFO or FILO queues?  Once the behaviour is found use the correct data structure (preferably the simplest one that does the job).

**Comment by thomaseizinger** [comment]
What is the difference if we use FILO or FIFO? I think we are talking about implementation details here that nothing on the outside should rely on or do I just not see the problem here?
