### ISSUE TITLE
Real world config parsing inconsistent with unit test

### ISSUE THREAD

**Issue by rishflab** [comit-network/comit-rs#2324]
## Problem
When I run`cnd -c config.toml` with a config.toml that defines `http_api` the same way as the `full_config_deserializes_correctly()` unit test in cnd/src/config/file/.rs:
https://github.com/comit-network/comit-rs/blob/b738eacccdbb08e3e15a10600dd00e8e0b07dcd7/cnd/src/config/file.rs#L197-L199

```
[http_api]
socket = "127.0.0.1:8001"
```
I get the following error:
```
Error: failed to read config file config2.toml
Caused by:
    invalid type: string "0.0.0.0:8001", expected struct Socket
```
If I change the config.toml to:
```
[http_api.socket]
address = "127.0.0.1"
port = 8001
```
`cnd -c config.toml` works fine

## Goals

1. Figure out why the unit test is inconsistent with real world use
2. Fix the issue/inconsistency (if there is an issue)

**Comment by tcharding** [comment]
This issue is out of date.  Running `cnd` as described with 
```
[http_api]
socket = "127.0.0.1:8001"
```
works just fine now.

**Comment by tcharding** [comment]
Bump @rishflab just in case you want to check my findings.
