### ISSUE TITLE
GitHub Action CI: Fix make file

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#2338]
# Problem

With https://github.com/comit-network/comit-rs/pull/2321 we make use of GitHub Actions for building comit-rs. 
At the beginning we wanted to support CircleCI and GitHub Action in parallel, hence we have added an unneeded additional target in the make file

# Goal

Once we are happy with GitHub Actions, we should remove CircleCI and remove the unneeded make file target

**Comment by da-kami** [comment]
@D4nte are you working on that?

**Comment by D4nte** [comment]
I have no clue what is this ticket about. What is the "unneeded target" in the makefile?

**Comment by bonomat** [comment]
This has been resolved by @D4nte when removing CircleCI.
