### ISSUE TITLE
Remove ts-ignores introduced by #2330

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#2352]
## Problem

Every API test produces a log file which needs to be named after the test. Unfortunately, with Jest this is not straightforward. In the past we used a tiny, hacky JS library to deal with this problem. After PR #2330, we instead instruct Jasmine, the testing framework Jest builds on top of, to give us the name.

That was an improvement, but we had to introduce `ts-ignore`s to silence the compiler here

https://github.com/comit-network/comit-rs/blob/9523f7bf4d00dbc02ceb1bc5873f706dd2d810aa/api_tests/src/configure_jasmine.ts#L1-L5

and here

https://github.com/comit-network/comit-rs/blob/9523f7bf4d00dbc02ceb1bc5873f706dd2d810aa/api_tests/src/actor_test.ts#L10-L24

## Goal

To listen to the compiler. Remove the `ts-ignore`s and deal with the problem.

**Comment by luckysori** [comment]
@thomaseizinger I finally refined this one. You may want to add it to an epic :smile:

**Comment by thomaseizinger** [comment]
Thanks @luckysori, I applied `good-first-issue` to this.
Anyone with TS knowledge should be able to deal with that, it is not a huge priority to us though :)

**Comment by thomaseizinger** [comment]
Removing `no-activity` to keep this around for people who want to pick low hanging fruit :)
