### ISSUE TITLE
Optimize CI workflow in Github Actions

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#2353]
## Problem

The new GH actions workflow can be optimized to finish faster. Actually running the e2e tests takes 640 seconds, that is 10m and 40seconds. The overall job shouldn't take much longer but currently takes 21m.

Here is a list of in-efficiencies I found:

1. We unnecessarily install Rust toolchains as part of the e2e_test job.
2. The e2e_test job doesn't cache `node_modules`
3. We download the blockchain nodes with every test run

## Goal

Make CI as fast as possible.

## Recommendation

1. The Makefile also downloads several Rust toolchains before it runs the e2e test, however, the e2e tests don't need Rust actually, they should just execute the binary.

Fixing this will require some modifications to the Makefile and our package.json because currently, we always compile `cnd` before we run the tests. It is nice for local development to have `cargo build -p cnd` in the `pretest` but for CI, it is unnecessary. We could move this compilation step to the `globalSetup` script and check for the `CI` env variable there. If that is set, we could assume that we don't have to compile `cnd`.

This would also fix a problem that I am currently experiencing where running a test from the IDE does not compile `cnd` because CLion executes `jest` directly and hence skips the `pretest` script.

Installing toolchains and building `cnd` currently takes 7m and 05 seconds.

2. Add a caching step for the `node_modules` folder inside `api_tests` to avoid the dependencies being downloaded again. This should shave off 60 seconds of the run.

3. Nothing to be done: Avoiding re-download of blockchain nodes will be fixed with https://github.com/comit-network/comit-rs/pull/2307 and caching of `node_modules`.

**Comment by bonomat** [comment]
> 1) The e2e_test job unnecessarily builds the cnd binary again.

That's not the case. We upload the binary and download it again. There is also an extra make file goal to ensure this. 

https://github.com/comit-network/comit-rs/blob/94b8f54e0880c9276ff4646ee4fe285847774a99/Makefile#L88-L89

and 

https://github.com/comit-network/comit-rs/blob/94b8f54e0880c9276ff4646ee4fe285847774a99/api_tests/package.json#L12

You might have noticed this because of the PR: #2191 : I think there was a rebase error, let me fix it there.

**Comment by thomaseizinger** [comment]
> That's not the case. We upload the binary and download it again. There is also an extra make target and yarn target to not run pretest :

Good news! I did see the CI configuration but looking at the logs it looked like that didn't work properly. Seems to be fixed when looking at the latest logs :)
