### ISSUE TITLE
Download `lnd` binary from GitHub releases instead of building them in CI

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#2369]
## Problem

Currently, we build the `lnd` binary during CI and locally we assume it is in the path.
This:

a) increases CI time unnecessarily
b) makes it harder to run the tests locally

## Goal

- Our e2e test suite should not have implicit dependencies.
- Provide a fast way for developer to get ready in the readme by mentioning the binary availability.

## Recommendation

The binaries on the `lnd` release page are built with the `invoicesrpc` tag. (It says there and I also confirmed by downloading one of the binaries and checking for the hold-invoice functionality.)
Hence, we can just download the desired release from their instead of building it locally.

I would recommend to wait until https://github.com/comit-network/comit-rs/pull/2307 is merged, as it makes it a breeze to do the same thing for lnd that I've done for bitcoind and parity there.

Use the latest beta version of lnd.

**Comment by D4nte** [comment]
I think something which is implied here and not explicitly stated: By downloading the lnd binary the same way we do it for bitcoind and parity, it means that a dev will not have to install lnd locally before running the test anymore.
I just want to be sure that this is the outcome of this ticket and not something that is only happening in the CI.
