### ISSUE TITLE
Remove dependency on `multihash`

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2381]
Use `libp2p::multihash` instead.

**Comment by D4nte** [comment]
@thomaseizinger where do we track the libp2p update? is it done?

**Comment by thomaseizinger** [comment]
libp2p is already updated in dev and `lnd-mob` is also up to date with `dev`.

**Comment by thomaseizinger** [comment]
This can be done on the `lnd-mob` branch already.

**Comment by thomaseizinger** [comment]
@tcharding did this already!
