### ISSUE TITLE
e2e tests: Use swap factory

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#2384]
## Problem

`swap_factory.ts` is use to create the body to create a swap on the new REST API routes.
However, some of the functions to default values for the body swap are present in `default.ts` and used by `actor.ts`.

Note that `swap_factory.ts` already support han-ethereum-ether-halight-lightning-bitcoin pair. Similar logic needs to be written for the other pairs.

## Goal

- Consolidate all functions to generate the body for the new cnd REST API routes in `swap_factory.ts`.
- Ensure all LN tests (e.g. dry tests and lnd sanity) use `SwapFactory`.
- This means the halight dry tests need to be converted to 2 actor tests.
- The expiries (and other info) to use for a swap are decided within the swap factory for all actors (and not each actor generate the expiry) as both actor need to inject the exact same in the create swap request to cnd REST API.

**Comment by bonomat** [comment]
@D4nte: I assume this is in progress?
