### ISSUE TITLE
ComitLN interface for creating new swaps is tied to a single combination

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2390]
Currently we use a struct called `CreateSwapParams` struct to pass data (POST request body) from the REST API to the swarm.  The design of this struct limits, which swaps can be passed to the `ComitLN` network behaviour as it statically encodes the parameters for the only combination that is currently supported: HanEthereum <-> Halight.

This was done because it was the simplest solution at that time. It should be fine for now but will become a problem if we start to support more combinations as the the current obvious way of extending this is to create a new struct for each combination.

**Comment by thomaseizinger** [comment]
Fixes in https://github.com/comit-network/comit-rs/pull/2689.
