### ISSUE TITLE
HALight does not report failed swaps

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2394]
## Problem

Currently we do not keep track that a halight swap failed.

## Goal

Keep track of failed swaps, so we can eventually report that on the API.

## Recomendation

Consider how we do this for Han using the `InsertFailedSwap` trait.

**Comment by D4nte** [comment]
Similar to #2404, can we confirm this is needed and not just a blind following for the rfc003 design?

**Comment by tcharding** [comment]
I've no clue, I just created the tickets from `TODO`s in our ln-mob branch :)

**Comment by thomaseizinger** [comment]
Replaced with https://github.com/comit-network/comit-rs/issues/2423.
