### ISSUE TITLE
Remove conversion between `NodeLocalSwapId` and `SwapId`

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2398]
## Problem

We currently have two identifiers for swaps:
1. A local swap identifier: generated by each node when a swap is posted to the REST API and used in the REST API route.
2. Synced/shared swap identifier, created by Bob and shared with Alice.

This leads to potentially buggy code if/when we mix these up.  We currently have two types but the usage is clunky.  `NodeLocalSwapId` and `SwapId`.

## Goal

Make good use of the type system to be safe.

Have a nice clean abstraction and data types that correctly model our desired usage.  On top of this, make it hard to write buggy code.

We should remove any possible conversion between both swaps (and remove `pub` on inner field if present).
We should only have a mapping between a given `NodeLocalSwapId` and a given `SwapId` (from memory/db).

## Recommendation

Don't changes types across the whole codebase, duplicate some code from rfc003 if necessary.
Consider making the inner field of `SwapId` private to avoid further misusage.

**Comment by D4nte** [comment]
After giving more thought on this issue after the grooming, I'd like to invite the dev (and possibly @thomaseizinger) who grabs this issue to consider the following:

The REST API uses the `local swap id`, meaning the controler needs to be able to find a given swap using the local id.

The COMIT API uses the `shared swap id`, meaning the network behaviour/swap needs to be able to find a given swap using the shared id.

We currently use the same `Uuid` to get the shared id from the local id: 

https://github.com/comit-network/comit-rs/blob/70e9010198c7f6d0ee75a1d31d8c093ffc8c1836/cnd/src/http_api/routes.rs#L48

This can only be incorrect as the local id for Alice is totally unrelated to the shared id (generated by Bob).

The relation between local and shared ids needs to be saved in the DB as, again, they are not correlated for Alice. Hence, this should be part of the DB design spike (@thomaseizinger what is the tracking issue for the spike). The fact that it is store in the DB *might* be considered as part of this ticket.

The way I see it is that in memory, there must be 2 hashmaps:
- `id1 -> id2`
- `id2 -> swap`

id1 and id2 are shared id and local id, either way is fine, I would favor id2 to be local id as I expect more call on the HTTP API than on the network, giving a very slight performance advantage.

In the DB, there are various ways to store this information so I'll let the dev doing the spike reason about it.

**Comment by tcharding** [comment]
Putting this back in 'groomed' because not confident I can get this done and merged before sprint closes tomorrow.
