### ISSUE TITLE
200 is returned for any swap id on `GET /swap/:id`

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2399]
## Problem

Currently we always return 200 OK for any swap id that is passed to us when a user hits the HALight endpoint to get a particular swap.

## Goal

Do the right thing here: https://github.com/comit-network/comit-rs/blob/814467ec1a4c2a3319b59eb4566156f194122926/cnd/src/http_api/routes.rs#L55

We are manipulating `Option`s such as `finalized_swap`. It is fine for 200 to be returned if `finalized_swap` is not present for example.
Also, if the swap does not exist at all then 404 should be returned.
If an actual error is encountered, then it should actually be bubbled up, today we just have `None` from the option.

if the swap is in the database then return 200, else, return 404.

## Recommendation

Read from the database to verify the swap exists, assumes there is a database entry for HALight swaps.

**Comment by thomaseizinger** [comment]
Removed `good-first-issue` because this is blocked and hence cannot be picked up.
