### ISSUE TITLE
POST Body is tied to HanEthereumEther-HALightLightningBitcoin

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2401]
## Problem

Currently the body of the POST request used by the REST API to post a halight swap is modelled with a struct (`Body`) that is tied to the protocol pair.

https://github.com/comit-network/comit-rs/blob/d6e1d3499941f69fbf39e4f0d658896f98d4ae22/cnd/src/http_api/routes/index.rs#L102-L108

## Goal

Be able to deserialize all incoming swaps on the REST API without code duplication.

## Recommendation

There are currently one handler function per lightning route. All these function should use the same generic body struct (with different type parameters). As of today, only han-ethereum-ether-halight-lightning-bitcoin route should call `ComitLn` (which would still be specialised to han-eth-eth-halight-ln-btc.

Note: Make sure to keep the deserialisation in `serde_json::Value` and deserialize the body using a reference of the result.

**Comment by thomaseizinger** [comment]
I am removing the dependencies from this one because I think it doesn't matter in which order we do this. We can for now continue using the `Body` struct in other layers even if it is generic.
