### ISSUE TITLE
`swap_protocols/han.rs` only implements Ethereum

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2403]
## Problem

When we created `swap_protocols/han.rs` we only implemented stuff for Ether.

## Goal

Support Bitcoin in the new `han.rs` module.

**Comment by D4nte** [comment]
@tcharding @thomaseizinger I believe this is already tracked with #1953 please confirm.

**Comment by thomaseizinger** [comment]
Yes I think so. We don't plan to support LNBTC<->BTC swaps initially so I don't think this is of high priority.
