### ISSUE TITLE
insert_failed_swap is not implemented in han module

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2404]
## Problem

`han.rs` generator does not implement `InsertFailedSwap`.

## Goal

Handle swap insertion errors correctly.

Related to: https://github.com/comit-network/comit-rs/issues/2394

**Comment by D4nte** [comment]
Do we actually need this trait?

**Comment by thomaseizinger** [comment]
Replaced with https://github.com/comit-network/comit-rs/issues/2423.
