### ISSUE TITLE
Make `Topic` implementation generic over Ethereum `Hash` and `Address`

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#2411]
This a follow up ticket for #2157

## Problem

There is a weird conversion from `Address` to `Hash` in our Ethereum types code:

https://github.com/comit-network/comit-rs/blob/1ceaa33ee93ac80d465a90001d21a0c96079ce6a/cnd/src/ethereum.rs#L49-L55

This is because the `Topic` struct (used for searching in `Event`s) takes a `Hash` but we also use it to search for `Address`es. In order to achieve this we currently just convert the `Address` to `Hash`.

## Goal

Remove the conversion from `Address` to `Hash` and fix this problem in the `Topic` implementation.

## Proposal

I would start with making the `Topic` generic instead of just accepting `Hash`.

**Comment by thomaseizinger** [comment]
Gonna re-open this because it is still a valid good first issue.

**Comment by thomaseizinger** [comment]
FFS stale bot! :D
