### ISSUE TITLE
Optimise `Display` for Ethereum `Hash` and `Address` structs

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#2413]
This is a follow up issue for #2157

## Problem

We currently implement `LowerHex` and `Display` for the Ethereum `Hash` struct which can be optimised. 

## Goal

Optimise the code and get rid of the `LowerHex` implementation by integrating it into `Display` for `Hash`.
You might want to adapt the implementation for `Address` accordingly.

**Comment by thomaseizinger** [comment]
Gonna re-open this because it is still a valid good first issue.

**Comment by thomaseizinger** [comment]
Resolved in #2904.
