### ISSUE TITLE
Remove `Option` for `Hash` in Ethereum `Block` struct

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#2414]
## Problem

The Ethereum `Block` currently has an `Option<Hash>` field, this should just be `Hash` - the `Web3Connector` should deal with this. 

https://github.com/comit-network/comit-rs/blob/b93cd01c57620579ab9703555c98622df83d3b96/cnd/src/ethereum.rs#L181-L183

Most of those `Option`-wrappers were already removed, let's also remove that one. 

## Goal

```
pub struct Block {
    /// Hash of the block
    pub hash: Hash,
...
}
```

**Comment by thomaseizinger** [comment]
Resolved in https://github.com/comit-network/comit-rs/pull/2582.
