### ISSUE TITLE
Replace Ethereum `U256` with own type and finally remove the `primitive_types` dependency

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#2415]
This is a follow-up ticket for #2157

## Problem 

When working on #2157 we ran into the problem that neither `serde-hex` nor our low-level `hex` library can properly handle the Etheruem value as represented by `primitive_types::U256`.
This is due to the fact that the `U256` [value in Ethereum is not fixed hex but compacted](https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding) (although it actually is of fixed size, namely `[u8, 32]`). 

## Goal

Own our code, remove dependency on `primitive_types`.

## Proposal

Given what is currently our there in rust `hex` libraries we will have to write our own serde De-/Serializer to properly deal with the Ethereum hex value.

When doing #2157 I started tackling this by trying to boil down the code from the `primitive_types` [serialization and deserialization code from the parity codebase](https://github.com/paritytech/parity-common/blob/master/primitive-types/impls/serde/src/serialize.rs), but it was so much code that I had to pull in that I decided to create this follow-up ticket instead of fixing it right away. 

Keep in mind that, when owning this code, we will also have to provide a proper amount of tests to ensure it works.

**Comment by da-kami** [comment]
if you don't agree @thomaseizinger feel free to remove from technical debt again :)

**Comment by thomaseizinger** [comment]
Superseded by #2922.

**Comment by thomaseizinger** [comment]
Actually, not really superseded. It is just that the remodeled type would depend on the serialization provided by #2922.
