### ISSUE TITLE
Merged log files of e2e tests for better experience

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#2421]
## Problem

It is often hard to find a problem in the different log files of the e2e tests and follow the flow between actors and test execution. Opening multiple files and comparing time stamps to understand what is going on is unnecessarily cumbersome. 
It would help to have a combined log-file so one can follow the flow more easily. 

## Goal

Have one combined log-file per e2e test that combines all actor and system-logs into one file sorted by time-stamp. 
Note: When it comes to merging the node logs in we might have to filter so the log file does not get to cluttered. 

## Proposed Solution

Start with combining all `[actor].log` files and all `[actor]-cnd.log` files into one merged log. Then decide if it helps to include blockchain-node logs and what is actually relevant from them.

When it comes to just combining multiple log-files into a merged log-file it seems most people use bash-commands or scripts for this.
There are some [discussions on stackoverflow](https://stackoverflow.com/questions/15866772/merging-multiple-log-files-by-date-including-multilines) [and tutorials](https://www.scalyr.com/blog/how-to-merge-log-files) concerning the topic. 

An alternative are more sophisticated tools that come with a UI like ELK-Stack, Graylog (...), as outlined by blogposts about [log-analysis solutions](https://opensource.com/article/19/4/log-analysis-tools). I feel that is an overkill for us and would not recommend it atm.

Also took a quick look at capabilities of javascript logging solutions like [winston](https://www.npmjs.com/package/winston), but logging solutions don't seem to be the right way, as they don't deal with log files from different systems but rather create log-files themselves. [Asked a question on stackoverflow though.](https://stackoverflow.com/questions/61092860/can-winston-be-used-to-merge-existing-log-files) (Note: log4js is what we use for logging in the typescript tests, but it does not seems capable of combining log files from different systems.)

**Comment by thomaseizinger** [comment]
I think `fluentd` is what we need :)

**Comment by thomaseizinger** [comment]
We probably need to replace our logger with this:

https://github.com/fluent/fluent-logger-node

**Comment by thomaseizinger** [comment]
And use the `file` plugin to read the logs of other processes:

https://docs.fluentd.org/input/tail

Parsing will require the use of the regex plugin:

https://docs.fluentd.org/parser/regexp

**Comment by thomaseizinger** [comment]
This could also be useful: https://vector.dev/
