### ISSUE TITLE
Failed swaps are not reported on the API

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#2423]
## Problem

For now, failed (halight) swaps are just logged, meaning we cannot tell the client that a swap failed.

## Goal

Tell clients when a swap failed.

## Notes

A ledger status is included as part of #2159 so we should not expect any change in the response format at this stage.
We do not expect to include the reason of an error at this stage.

**Comment by da-kami** [comment]
am tempted to add `good-first-issue` here, what do you think @thomaseizinger ?

**Comment by thomaseizinger** [comment]
I disagree very much :see_no_evil: 

Mainly because the design of how we want to do this is not clear.

**Comment by da-kami** [comment]
> I disagree very much 🙈
> 
> Mainly because the design of how we want to do this is not clear.

Good that I asked then 😁
You might want to review the tickets I added the label too at some point.

**Comment by D4nte** [comment]
@thomaseizinger Is there a ticket that handle implementing the swap response for the new route once they are designed with #2159? I can't find it and I think this would be the first step.

Also, I would expect to return successful and failed swaps as part of said first step, why doing the inclusion of failed swap in the response in a separate ticket?

Set to "to-refine" to answer question above.

**Comment by thomaseizinger** [comment]
The ticket might be wrongly phrased. We don't exclude failed swaps, the problem here is that we never report them as failed so we can't tell the user that they failed.

This issue is just written very user-centric to not care about the internals :)
