### ISSUE TITLE
LN problem: certificate invalid

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#2464]
I observed the following error on our e2e tests.

```bash
FAIL tests/ether_halight.ts (46.283s)
  ● han-ethereum-ether-halight-lightning-bitcoin-alice-redeems-bob-redeems

    timed out after 20000ms

      at Timeout.<anonymous> (node_modules/comit-sdk/src/util/timeout_promise.ts:18:14)
```

Log excerpt: 
```

[2mApr 16 00:45:41.460[0m [31mERROR[0m [1mbeta_ledger[0m[1m{[0mswap_id=416e01ce-8eb8-4d60-9506-7ad73bda1211 role=Bob[1m}[0m: cnd::network::comit_ln: swap failed with error sending request for url (https://localhost:51225/v1/payments?include_incomplete=true): error trying to connect: The certificate was not trusted.

Caused by:
    0: error trying to connect: The certificate was not trusted.
    1: The certificate was not trusted.
[2mApr 16 00:45:41.463[0m [32m INFO[0m [1mbeta_ledger[0m[1m{[0mswap_id=416e01ce-8eb8-4d60-9506-7ad73bda1211 role=Bob[1m}[0m: cnd::network::comit_ln: swap finished
```

[alice.log](https://github.com/comit-network/comit-rs/files/4484467/alice.log)
[cnd-alice.log](https://github.com/comit-network/comit-rs/files/4484469/cnd-alice.log)
[bob.log](https://github.com/comit-network/comit-rs/files/4484470/bob.log)
[cnd-bob.log](https://github.com/comit-network/comit-rs/files/4484471/cnd-bob.log)
[test_environment.log](https://github.com/comit-network/comit-rs/files/4484472/test_environment.log)
[parity.log](https://github.com/comit-network/comit-rs/files/4484473/parity.log)
[alice-lnd.log](https://github.com/comit-network/comit-rs/files/4484479/lnd.log)
[bob-lnd.log](https://github.com/comit-network/comit-rs/files/4484482/lnd.log)

**Comment by bonomat** [comment]
Pinging @D4nte as the master of thunder and lightning :)

**Comment by D4nte** [comment]
@da-kami has the same issue locally and spent the day debugging it. I double checked myself and no problem. What version of Mac do you have @bonomat?

**Comment by D4nte** [comment]
I have Mojave and no problem, @da-kami seems to think he has the error since he upgraded his macbook.

We use `reqwest` and add the lnd tls cert to our requests (that's how it works).

The default feature flag of reqwest for TLS is `default-tls`. I asked @da-kami to pass `native-tls` or `rustls-tls` and see if it helps.

**Comment by da-kami** [comment]
> I have Mojave and no problem, @da-kami seems to think he has the error since he upgraded his macbook.
> 
> We use `reqwest` and add the lnd tls cert to our requests (that's how it works).
> 
> The default feature flag of reqwest for TLS is `default-tls`. I asked @da-kami to pass `native-tls` or `rustls-tls` and see if it helps.

Correction:
We have it set to `native-tls` in the `Cargo.toml`.Am trying `default-tls`and `rustls-tls` and see if it helps.

**Comment by da-kami** [comment]
Note: 
I validated that the path to the certificate is correctly passed in (logged the path and the certificate).
`lnd` version is correct at `lnd version 0.9.1-beta commit=v0.9.1-beta`
(even reinstalled it after a go clean and system restart)

**Comment by da-kami** [comment]
When running with `rustls-tls` I get a different error:

```
[2mApr 16 17:54:11.275[0m [32m INFO[0m [1mbeta_ledger[0m[1m{[0mswap_id=d9435252-3cb5-478c-8f17-22b4a6507c18 role=Bob[1m}[0m: cnd::network::comit_ln: yielded event Started
[2mApr 16 17:54:11.275[0m [32m INFO[0m [1mbeta_ledger[0m[1m{[0mswap_id=d9435252-3cb5-478c-8f17-22b4a6507c18 role=Bob[1m}[0m: cnd::network::comit_ln: yielded event Opened
[2mApr 16 17:54:11.275[0m [32m INFO[0m [1mbeta_ledger[0m[1m{[0mswap_id=d9435252-3cb5-478c-8f17-22b4a6507c18 role=Bob[1m}[0m: cnd::swap_protocols::halight::connector: Certificate: Certificate
[2mApr 16 17:54:11.291[0m [35mTRACE[0m [1malpha_ledger[0m[1m{[0mswap_id=d9435252-3cb5-478c-8f17-22b4a6507c18 role=Bob[1m}[0m:[1mhtlc_deployed[0m[1m{[0mexpected_bytecode=61012861000f6000396101286000f3361561007957602036141561004f57602060006000376020602160206000600060026048f17fa73aad9c163d6f9cac31016558326921d43303e2af1a8587bf1ccd91cbfc78da60215114166100ae575b7f696e76616c69645365637265740000000000000000000000000000000000000060005260206000fd5b42635e980f1d106100eb577f746f6f4561726c7900000000000000000000000000000000000000000000000060005260206000fd5b7f72656465656d656400000000000000000000000000000000000000000000000060206000a173c6723a5fd978121fc227d42f99dbb29257976d67ff5b7f726566756e64656400000000000000000000000000000000000000000000000060006000a1736aeb4d81488d4574082303326595300c4875545bff[1m}[0m: cnd::btsieve::ethereum::web3_connector: Fetched block from web3: a4af6c34831629b0f8bb00cad14c8fcb17b0b381297a8d7669e86dba761f989f
[2mApr 16 17:54:11.292[0m [35mTRACE[0m [1malpha_ledger[0m[1m{[0mswap_id=d9435252-3cb5-478c-8f17-22b4a6507c18 role=Bob[1m}[0m:[1mhtlc_deployed[0m[1m{[0mexpected_bytecode=61012861000f6000396101286000f3361561007957602036141561004f57602060006000376020602160206000600060026048f17fa73aad9c163d6f9cac31016558326921d43303e2af1a8587bf1ccd91cbfc78da60215114166100ae575b7f696e76616c69645365637265740000000000000000000000000000000000000060005260206000fd5b42635e980f1d106100eb577f746f6f4561726c7900000000000000000000000000000000000000000000000060005260206000fd5b7f72656465656d656400000000000000000000000000000000000000000000000060206000a173c6723a5fd978121fc227d42f99dbb29257976d67ff5b7f726566756e64656400000000000000000000000000000000000000000000000060006000a1736aeb4d81488d4574082303326595300c4875545bff[1m}[0m:[1mnew_block[0m[1m{[0mblockhash=a4af6c34831629b0f8bb00cad14c8fcb17b0b381297a8d7669e86dba761f989f[1m}[0m: cnd::btsieve::ethereum: checking 0 transactions
[2mApr 16 17:54:11.323[0m [33m WARN[0m [1mbeta_ledger[0m[1m{[0mswap_id=d9435252-3cb5-478c-8f17-22b4a6507c18 role=Bob[1m}[0m: rustls::session: Sending fatal alert BadCertificate    
[2mApr 16 17:54:11.323[0m [35mTRACE[0m [1malpha_ledger[0m[1m{[0mswap_id=d9435252-3cb5-478c-8f17-22b4a6507c18 role=Bob[1m}[0m:[1mhtlc_deployed[0m[1m{[0mexpected_bytecode=61012861000f6000396101286000f3361561007957602036141561004f57602060006000376020602160206000600060026048f17fa73aad9c163d6f9cac31016558326921d43303e2af1a8587bf1ccd91cbfc78da60215114166100ae575b7f696e76616c69645365637265740000000000000000000000000000000000000060005260206000fd5b42635e980f1d106100eb577f746f6f4561726c7900000000000000000000000000000000000000000000000060005260206000fd5b7f72656465656d656400000000000000000000000000000000000000000000000060206000a173c6723a5fd978121fc227d42f99dbb29257976d67ff5b7f726566756e64656400000000000000000000000000000000000000000000000060006000a1736aeb4d81488d4574082303326595300c4875545bff[1m}[0m: cnd::btsieve::ethereum::web3_connector: Fetched block from web3: 2a609893ea4596bc0fafd37761c77fffbd491d7ee65344c231752e2b53549f4b
[2mApr 16 17:54:11.323[0m [31mERROR[0m [1mbeta_ledger[0m[1m{[0mswap_id=d9435252-3cb5-478c-8f17-22b4a6507c18 role=Bob[1m}[0m: cnd::network::comit_ln: swap failed with error sending request for url (https://localhost:57551/v1/payments?include_incomplete=true): error trying to connect: invalid certificate: CAUsedAsEndEntity

Caused by:
    0: error trying to connect: invalid certificate: CAUsedAsEndEntity
    1: invalid certificate: CAUsedAsEndEntity
```

**Comment by bonomat** [comment]
> @da-kami has the same issue locally and spent the day debugging it. I double checked myself and no problem. What version of Mac do you have @bonomat?

The error occurred on GitHub CI for the macos build.

**Comment by da-kami** [comment]
The error when using `rustls-tls` is interesting, but I am not sure how to go on: 

https://briansmith.org/rustdoc/webpki/enum.Error.html#variant.CAUsedAsEndEntity

```
A CA certificate is veing used as an end-entity certificate.
```

**Comment by da-kami** [comment]
Might be related: https://github.com/sfackler/rust-native-tls/issues/151

**Comment by da-kami** [comment]
Found a workaround using `native-tls`:

https://github.com/seanmonstar/reqwest/issues/182

**Comment by thomaseizinger** [comment]
Given the information [here](https://support.apple.com/en-us/HT210176), the ideal fix is probably to ping the `lnd` guys and tell them to generate a valid certificate on startup :)

**Comment by da-kami** [comment]
> Given the information [here](https://support.apple.com/en-us/HT210176), the ideal fix is probably to ping the `lnd` guys and tell them to generate a valid certificate on startup :)

Created an issue: https://github.com/lightningnetwork/lnd/issues/4201
Hope it is described in an understandable manner.
