### ISSUE TITLE
Handle multiple, concurrent swaps with the same peer properly

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#2490]
## Problem

Currently, the announce protocol emits the following event once a swap was confirmed:

https://github.com/comit-network/comit-rs/blob/5a7b9af1e304dab3b0c54b6404a769237fed8dd6/cnd/src/network/protocols/announce/behaviour.rs#L285-L292

Now imagine a party announcing the same swap again before the first one is finalized. We cannot distinguish which of those swaps get confirmed and which ones get declined because the event only returns peer-id, swap-id and the digest. Announcing the same swap to the same peer means peer and digest are equal and hence you cannot distinguish.

## Goal

Handle this situation better so that this ambiguity doesn't happen.

## Recommendation

Remove the concurrency aspect of the current behaviour.

**Comment by D4nte** [comment]
Please mark as `added-mid-sprint` and add the milestone.

**Comment by tcharding** [comment]
> Please mark as `added-mid-sprint` and add the milestone.

Done, thanks for the reminder.

**Comment by thomaseizinger** [comment]
We seem to have lost this functionality as discovered in #2718.
