### ISSUE TITLE
The requested combination of ledgers and assets is not supported.

### ISSUE THREAD

**Issue by yosriady** [comit-network/comit-rs#2498]
## Problem

On the rfc003 routes, errors returned for deserialisation issues are unhelpful

--- 

This is an odd one, but **for some inputs** the cnd HTTP API returns an error when you `sendSwap`:
```
HTTP_URL_CND_1 http://127.0.0.1:51378/swaps/rfc003

{"status":400,"title":"Swap not supported.","detail":"The requested combination of ledgers and assets is not supported."}
```

Here is the swap that triggers the error (this is the request payload passed to the `/swaps/rfc003`endpoint):

```
{
	"alpha_ledger": {
		"name": "ethereum",
		"chain_id": 17
	},
	"beta_ledger": {
		"name": "bitcoin",
		"network": "regtest"
	},
	"alpha_asset": {
		"name": "erc20",
		"token_contract": "0x62d69f6867a0a084c6d313943dc22023bc263691",
		"quantity": "27000000000000000000"
	},
	"beta_asset": {
		"name": "bitcoin",
		"quantity": "376433.99999999994"
	},
	"alpha_ledger_refund_identity": "0xf8960e4BB96108aBD63910A3aC7BCdCd3d53696F",
	"alpha_expiry": 1586409200,
	"beta_expiry": 1586405600,
	"peer": {
		"peer_id": "QmcWiij22RbVB1goi1DR6fz61xRRu1FiXC4Ue6dbiK6E6V",
		"address_hint": "/ip4/127.0.0.1/tcp/9939"
	}
}
```

The error message isn't saying anything about what went wrong with the payload.

## Goal

As we are migrated to new routes, we should prioritise those new routes and ensure that the handling of deserialisation is more verbose by returning the actual deser error (what field cannot be deserialized).

**Do not touch the old routes.**

Ensure (or make it) that the errors send back if there is a deserialisation issue are verbose enough to allow the dev to know what field is malformed (.e.g float amount in satoshi or wei field).
Please note more broad error tests are already present `create-*-returns-invalid-body`.

**Comment by D4nte** [comment]
Should this go back to grooming then?

**Comment by tcharding** [comment]
There is only one new endpoint implemented so far.  The error handling for this endpoint _does_ return the serde error.  I believe this issue is resolved already. (initial issue description was for the rfc003 endpoints and during grooming we decided to only do the new endpoints, we missed the fact that these were correctly handled already.)

Could @thomaseizinger or @4nte please double check I'm correct on this?

``` index.rs
#[allow(clippy::needless_pass_by_value)]
pub async fn post_han_ethereum_halight_bitcoin(
    body: serde_json::Value,
    facade: Facade,
) -> Result<impl Reply, Rejection> {
    let body = Body::<HanEthereumEther, HalightLightningBitcoin>::deserialize(&body)
        .map_err(anyhow::Error::new)
        .map_err(problem::from_anyhow)
        .map_err(warp::reject::custom)?;
        ...
```

**Comment by thomaseizinger** [comment]
> Could we can implement client-side validations on the SDK?. For example:
> 
> ```js
> const swap = new Swap(<parameters>);
> const { valid, errors } = swap.valid?() // Returns true or false, and validation errors.
> ```
> 
> This way, app developers don't have to worry about rolling out their own validation of ledger data, which should be the responsibility of the SDK anyway.

I would like to not duplicate this kind of stuff as long as we can somehow avoid it. The new endpoints should return reasonably good errors for now, although they are not machine-readable yet.

Once we have all the new endpoints ready, we can add JSON schemas and return them as part of the error so the SDK can figure out in an automated and stable way, what is wrong with the request.
