### ISSUE TITLE
Make role part of the route so we can validate role specific `body`

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#2520]
## Problem

With the new announce protocol Bob has to know Alice's peer-id (to be able that an incoming swap announcement comes from the peer-id agreed on with Alice during negotiation), but Bob does not need to know Alice's `address_hint`. 

As part of #2389 we discussed that there should actually an error on Bob's side if he provides an `address_hint`.
The error would have been introduced in #2507 but we noticed that a better way of solving this would be to move the role to the URL, based on that, we can have dedicated structs of each side and let serde handle this error.

## Goal

Role-dependent swap-body serialization in the HTTP API.
When Bob provides an `address_hint` he gets an Error.

## Proposal

Moving the role to the URL is not trivial and will need some thought, nevertheless I'd propose to just give this ticket a go and figure the details out on the way.

**Comment by D4nte** [comment]
Not a priority at the moment. We will probably have to introduce a way to connect to other peers for the "decentralised orderbook" which could lead to totally remove the address hint.
To revise once we have a better picture of the network stack once the "decentralised orderbook" is on board.
