### ISSUE TITLE
FK may not be enabled for Sqlite

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2603]
## Problem

We just added foreign key relationships to the SQLite database.  However, according to the docs SQLite does not include FK by default.

## Goal

Ensure that foreign keys are enabled and write a test to ensure it is enabled.

ref: https://sqlite.org/foreignkeys.html#fk_enable
ref:  https://www.reddit.com/r/rust/comments/9lvepk/dieselrs_how_to_enable_foreign_keys/

**Comment by tcharding** [comment]
Question: Do we really need this? We have a unit test that inserts a swap, inserts a secret hash (setting the FK link to the swap), and then retrieves the secret hash using the FK relationship.

If this works do we need anything else to prove this?

**Comment by da-kami** [comment]
I ran an initial `connection.execute("PRAGMA foreign_keys = ON")` on the connection and that did not yield errors at that time. I'd keep this ticket.
