### ISSUE TITLE
New database code uses cryptic type names

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2604]
## Problem

The new database code uses types named with a prefix `I` for the diesel insertable database types. This can be confusing because the `I` notation is used for interfaces in other languages/styles.

## Goal

Do not use abbreviations, be explicit.

## Recommendation

Re-name all the `IFoo` types to `InsertableFoo`.

**Comment by da-kami** [comment]
Was already changed to `Insertable` instead if `I`, closing this.
