### ISSUE TITLE
New database code is not fully tested

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2605]
## Problem

We recently added a bunch of new database code. The individual table save/load methods were unit tested.

## Goal

It would be nice to have an 'integration' test of sorts, a test that uses the db API as we expect to use it i.e.:
- Save a created swap
- Save all the finalization data (communication protocol message data)
- Retrieve the in progress swap and verify all the data is present.

**Comment by da-kami** [comment]
was alrady done in the current version, closing this.
