### ISSUE TITLE
db code is not uniform in pass by reference/value 

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2612]
## Problem

The database code sometimes passes by reference and sometimes by value in implementations of the `Save` trait (probably other places also). We should think this through fully and be uniform.

## Goal

Have uniform code, think things through fully and don't just code to the compiler.

**Comment by thomaseizinger** [comment]
@tcharding Is this still relevant with the recent changes to the database code?

If not, can you either update or close it?

**Comment by tcharding** [comment]
This is stale now that we almost entirely re-wrote the db module.
