### ISSUE TITLE
Evaluate `hash_function` field in protocol db tables

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#2616]
## Problem

The [database spike](https://github.com/comit-network/spikes/blob/master/0025-an-extensible-db-design.adoc) adds a `hash_function` field to all the protocol tables. This might not be functionality that we currently want to be configurable.

In an effort to get unblock other DB tickets we decided to create a ticket for this instead of fixing it right away.

## Goal

Evaluate if we want to have the `hash_function` configurable in the database and decide to keep/remove it.

## Recommendation

Just remove it and be done with it.

**Comment by bonomat** [comment]
I like the recommendation:

> Just remove it and be done with it.
