### ISSUE TITLE
Creating test types is too verbose

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2617]
## Problem

When unit testing cnd we often end up with code like this
```
    let alpha_redeem_identity =
        EthereumAddress::from_str("2222e8be41b21f651a71aaB1A85c6813b8bBcCf8")
            .expect("valid redeem identity");
    let alpha_refund_identity =
        EthereumAddress::from_str("3333e8be41b21f651a71aaB1A85c6813b8bBcCf8")
            .expect("valid refund identity");
```
This code is too verbose, we do not actually are _what_ the values are just that they are valid and unique.

## Goal

Have a nicer way to create test types.  Inspire yourself from the lightning module which provides `random()`

```
    let beta_refund_identity = identity::Lightning::random();
    let beta_redeem_identity = identity::Lightning::random();
```

**Comment by thomaseizinger** [comment]
A better alternative to randomness is to use a property-based testing framework: https://github.com/AltSysrq/proptest
