### ISSUE TITLE
db: `tables` module exposes Queryable/Insertable 

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2635]
## Problem

The database uses diesel attributes which rely on having two structs, one with `Queryable` and one with `Insertable`.  Currently these are public even though they should only be used by the db.

We can vastly improve the situation by adding an additional type that is `pub` and making the two insertable/queryable ones private. We can then have public methods that deal only with these public types. This has the added advantage that all the wrapper code can be confined to the `tables` module, this makes the rest of the db code a lot easier to read, write, and maintain.

**Comment by thomaseizinger** [comment]
I think this is obsolete with using taking a more holistic approach when it comes to saveing / loading from the DB.
