### ISSUE TITLE
CoBloX Public Key missing from website

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#2715]
[Contributing guide](https://github.com/comit-network/comit-rs/blob/dev/CONTRIBUTING.md) says our public key is present at https://coblox.tech/security_coblox_tech_pubkey.gpg.asc however it is now gone.

**Comment by thomaseizinger** [comment]
Just checked the link, seems to be there again. Closing this.

**Comment by D4nte** [comment]
> Just checked the link, seems to be there again. Closing this.

Magic
