### ISSUE TITLE
Add assertions to ensure we retrieve the expected data when loading from the database

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#2722]
## Problem

When loading from the database we cannot have type-safety. This can lead to unexpected behaviour when constructing structs with similar fields and types.

Concrete problem that we encountered when adding `halight-herc20` (to add more context to this description):

At the moment  the only difference between`AliceSwap<...>` and `BobSwap<...>` is how the `secret_hash` is set (and the secret). When we assemble the `AliceSwap` we never actually ensure that the data we retrieve from the database is for role `Alice`. We had the case where we actually loaded `Bob` data but returned it as `AliceSwap`. It did not cause any error because for the role `Alice` we derive the `secret_hash` from the seed. (and cnd does not care about `Alice` or `Bob` when it comes to the root seed.

## Goal

Prevent unexpected behaviour by properly asserting that the data loaded is what is expected by the given parameters.

From the top of my head this is only relevant for the role at the moment. There might be more cases where this is relevant though. Use your brain :)

**Comment by thomaseizinger** [comment]
I think this was covered in #2818.
