### ISSUE TITLE
API for actions uses an array of 0 or 1 items

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2753]
## Problem

We used to return a bunch of actions, as such this was modelled using an array. We now only ever return a single action if there is one or no action at all. The current API model does not make this explicit.

This was discussed during the RUA work ([v1 PR](https://github.com/comit-network/comit-rs/pull/2736)), which was completed in [this PR](https://github.com/comit-network/comit-rs/pull/2752). 

## Goal

Our API should be explicit. If it is not it should be clearly tested so that the invariant (array always contains 0 or 1 item) is upheld.

Left to the devs discretion whether to fix this properly or to patch it up with e2e tests.

**Comment by D4nte** [comment]
@thomaseizinger @bonomat as per our discussion + https://meet.google.com/iig-nqay-nao?authuser=1 I think we should update the SDK to the new API and update the e2e tests to use that. Would you agree with such scope change?

I believe it would still fit in the appetite :)

**Comment by thomaseizinger** [comment]
> Our API should be explicit.

I just want to mention here that this is not just a matter of making `actions` not an array. It would be good if we could stay within the bounds of the Siren mediatype and not have to diverge from that model.

> @thomaseizinger @bonomat as per our discussion + #2736 (comment) I think we should update the SDK to the new API and update the e2e tests to use that. Would you agree with such scope change?

I am fine with such a scope change but to me it is orthogonal to an e2e test that asserts the number of actions in the array.

Given that the first user are the e2e tests, I would recommend to make the change in the e2e tests first and only once we have the Actor class and everything ported move the code to the SDK.
My guess is that it is going to be non-trivial to guess what API you want in the e2e tests to balance between being able to assert what you want to assert and still being able to load-off some code to the SDK.

**Comment by thomaseizinger** [comment]
I don't think there is an immediate task here that warrants having an open issue about this.

As per shape-up mentality, I am gonna keep this idea in my personal TODO/idea list.

In addition, before we settle on such an API change, we would need another / more projects that are heavy users of the current API to justify an improvement. For now, there are only annoyances in terms of an additional, unnecessary roundtrip.
