### ISSUE TITLE
Assert side when loading HTLC parameters

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#2781]
Can we have a ticket for deciding on:

- Either loading these individually but with an expectation of which "side" we expect this to be
- Or only loading params in pairs where we assert that what we find matches the side the user requested it on

_Originally posted by @thomaseizinger in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDIzMzg2MjU1/pull_request_reviews/more_threads_

**Comment by luckysori** [comment]
Was this already done with #2818 or a follow-up to that one? @tcharding

**Comment by thomaseizinger** [comment]
Yes, this was done in #2818.
