### ISSUE TITLE
Re-consider model of RemoteData vs LocalData

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#2812]
The bigger problem here is that we model `RemoteData` vs `LocalData` whereas - I think - what we should actually be doing is modelling this similar to the DB: `WhatAliceSharesWithBob` and `WhatBobSharesWithAlice`.

Interestingly, `WhatAliceLearnedFromBob` == `WhatBobSharesWithAlice` :smile: 
So there is some interesting modelling work to be done here :)

I attempted this refactoring already once but the `Swaps` struct is too entangled with the current model to do this quickly unfortunately.

_Originally posted by @thomaseizinger in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDIzMzg2MjU1/pull_request_reviews/more_threads_

**Comment by thomaseizinger** [comment]
Closing this for now, can revisit once we untangled the NetworkBehaviours from each other.
