### ISSUE TITLE
Use the failure crate for error handling

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#287]
https://boats.gitlab.io/failure/intro.html

This is a nice refactoring task that can hopefully be done incrementally. In a nutshell, it allows you to always use the same `Error` type as a return value (`failure::Error`) as long as all your custom errors implement `failure::Fail`. This should get rid of all your `From` implementations of the errors.

**Comment by D4nte** [comment]
Deprecated:

> Heads up, `failure` crate users, especially library authors! The `failure` crate is starting to fall by the wayside, since `std::error::Error` is being fixed to provide the same benefits of `failure::Fail`, so its usage is being increasingly discouraged in the Rust ecosystem. See this issue for details: https://github.com/rust-lang/rust/issues/53487
