### ISSUE TITLE
Find a way to run Rust tests on MacOS and Windows

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#2927]
## Problem

At the moment, we are only compiling the code on MacOS and Windows. Tests are only run under Linux due to the docker dependency of `testcontainers`.

## Goal

Find a way to do as many checks as possible on MacOS and Windows during CI.

Motivated by: https://github.com/comit-network/comit-rs/pull/2928

**Comment by thomaseizinger** [comment]
Fixed by https://github.com/comit-network/comit-rs/commit/24d5a1b02d5b826b9e234f8476f27ce0433e69b8.

**Comment by thomaseizinger** [comment]
Ah, we never merged that :D

**Comment by D4nte** [comment]
@thomaseizinger are we running tests or not now?

**Comment by thomaseizinger** [comment]
Nope, we are just running them on Linux atm.
