### ISSUE TITLE
try_lock_exclusive() on data dir, causes stable Access denied (os error 5) on Windows 10

### ISSUE THREAD

**Issue by llilakoblock** [comit-network/comit-rs#3008]
Windows 10, latest updates.
It's an winapi error, so compiler, rust toolchain, etc, does not really matter.

Error tag: 0.7.3, and all above.

Reproduce: build tag 0.7.3 or above, with either release or debug cfg. and start cnd.exe. 
Reproducible on clean virtual box machine with Windows 10, without any other software.

**Comment by thomaseizinger** [comment]
Hi @llilakoblock,

sorry for the late reply!

Unfortunately, I don't have a Windows box around to debug this. However, I found this: https://github.com/danburkert/fs2-rs/issues/26

Is that the issue you are facing? If so, we may be able to fix that by opening the lock file with different flags.
