### ISSUE TITLE
Enable more clippy lints

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#304]
There are a couple of interesting lints in clippy that are `allow` by default but might be useful for us:

Wrong integer arithmetic:

- https://rust-lang-nursery.github.io/rust-clippy/master/index.html#cast_possible_truncation
- https://rust-lang-nursery.github.io/rust-clippy/master/index.html#cast_possible_wrap
- https://rust-lang-nursery.github.io/rust-clippy/master/index.html#cast_precision_loss
- https://rust-lang-nursery.github.io/rust-clippy/master/index.html#cast_sign_loss

Invalid `From` implementation:

- https://rust-lang-nursery.github.io/rust-clippy/master/index.html#fallible_impl_from

Println statements:

- https://rust-lang-nursery.github.io/rust-clippy/master/index.html#print_stdout
There should be no println statements in the code base but only logger statements.

~~Use of `clone` for `Arc`s and `Rc`s:~~
~~- https://rust-lang-nursery.github.io/rust-clippy/master/index.html#clone_on_ref_ptr~~

**Comment by D4nte** [comment]
Agreed for all.
Please note, type inference does not work as well with `Arc::clone()` and hence we may need to deactivate the warning locally in some places.

**Comment by bonomat** [comment]
It seems like clippy does not support a proper config file right now and we need to fall back to passing extra lints as arguments ala:
`clippy -- -W clippy::clone_on_ref_ptr -D warnings`

More to read: https://github.com/rust-lang/rust-clippy/issues/3164

**Comment by bonomat** [comment]
I opt for not using `clone_on_ref_ptr` as we would need to make too many exceptions.
