### ISSUE TITLE
Uniquely identify the redeem and refund transactions for Ether/ERC20 HTLC

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#316]
**Summary** 
It is not that easy to ensure that the correct transaction has been found to redeem the htlc. Indeed, the funds in the htlc can only be found at block level, if 2 transactions are sent to the htlc, one with the correct secret, another with a wrong secret, in the same block, then there is no way to know which transaction redeemed and which is the correct secret.

The ETH (and ERC20, can be done here or new issue) HTLC need to be updated to log `REDEEM` or `REFUND` when such action is triggered. The logs are then kept in the transaction and can be used to ensure that the correct secret is extracted.

Take this opportunity to ensure that the transaction sent by Ethereum Ledger Query target the correct contract.

**Task List**
- [x] Update ETH HTLC to log `REDEEM` or `REFUND` when the event occurs
- [x] Do the same for ERC20
Child of #399.
Child of #405.

**Comment by D4nte** [comment]
@bonomat is it done for ERC20?

**Comment by bonomat** [comment]
yes, done for both.
