### ISSUE TITLE
⚗️ Test coverage in Travis 

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#32]
Spike:
- Check if it is easy to see whether new lines (from PR diff) are tested or not
- Check if test coverage can be ran on the e2e tests.

Notes:
Use cargo make
Add badge to readme
See https://testing.googleblog.com/2014/07/measuring-coverage-at-google.html?m=1

**Comment by D4nte** [comment]
You can see better coverage with:
1. Install Sourcegraph for Chrome or Sourcegraph for Firefox
2. Enable the Codecov extension on Sourcegraph (little dot)

However, the code coverage is not shown in the diff (which is what I want), ie, need to open the new version of the file standalone.

**Comment by D4nte** [comment]
Need to check codacy and coverall

**Comment by D4nte** [comment]
coveralls: no coverage per line for diff. back to codecov.

**Comment by D4nte** [comment]
Key part I find interesting: https://docs.codecov.io/docs/viewing-source-code
Usage would be:
1. Do code review
2. Spot a complex piece of code/change, open codecoverage
3. Check that the new code is properly covered or that coverage was not lost

**Comment by thomaseizinger** [comment]
Apparently, there is browser plugin for viewing code coverage in the code review on GitHub.

Check the last screenshot here: https://github.com/marketplace/codecov

**Comment by D4nte** [comment]
Tarpaulin does not work on mac os x: https://github.com/xd009642/tarpaulin/issues/152
So either Docker or travis only.

**Comment by D4nte** [comment]
@thomaseizinger yes, sourcegraph. I installed it and tried last week but was not great. You still go to an external site to see the per line coverage. It does give you more info like coverage per file. Then you click on the button which shows the percent and you get to the external website.
I think going to the codecov diff report is as good.

**Comment by D4nte** [comment]
Creating docker image to play around with tarpaulin on mac os x...

**Comment by thomaseizinger** [comment]
> Tarpaulin does not work on mac os x: [xd009642/tarpaulin#152](https://github.com/xd009642/tarpaulin/issues/152)
> So either Docker or travis only.

IMO, code coverage is something you don't do locally because it is usually a more complicated setup. (+ you need historical data for it do be useful)

> @thomaseizinger yes, sourcegraph. I installed it and tried last week but was not great.

It doesn't work like in the video demonstrated here? https://docs.codecov.io/docs/browser-extension

Looks like you can see the line-coverage inline in the PR. I don't think we need anything more than that since at this point, I think we should only use code coverage to easily detect untested code.

**Comment by thomaseizinger** [comment]
The extension changed apparently since the video was made. It no longer has the `%` button. That is a shame :(

**Comment by D4nte** [comment]
Ah, thanks for the explanation, I was going to reinstall the extension :)

Re. Local installation, actually it can be something interesting. Maybe not on our small software but when it gets bigger, the following local flow can be useful:
- write code
- run e2e
- double check new code is tested

**Comment by D4nte** [comment]
As per #675 I ran into many issues. At the end, it looks like tarpaulin could not compile with zmq (rust bindings). After discussion, we decided not too investigate further and drop this issue.

Code coverage can be reconsidered at a later stage when comit-rs is split into libraries.
