### ISSUE TITLE
Introduce new states & events for refund action

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#384]
Update the state machine to split states that have conditional actions between States without action and states with action (unimplemented transitions)

Notes:
The `refund` action should not be presented to the user until it is actually possible to refund (as per the network) as the refund transaction maybe be dropped if done too early (e.g. Bitcoin consensus would consider the transaction as invalid).

Pre-Work:
List all the new states that needs implementation and what transition are triggered by LQS height query and discussion with @LLFourn 

Child of #405.

**Comment by D4nte** [comment]
@LLFourn to cleanup, blocked by #576

**Comment by LLFourn** [comment]
I'm closing this now as we won't be using block height and are unlikely to need new states.
