### ISSUE TITLE
Automatically delete queries after a `time-to-live`

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#401]
Add a `time-to-live` property to btsieve queries to ensure that old queries are cleaned-up.

The `time-to-live` should be defaulted, with a configuration option.

DoD:
- [ ] Query does not exist anymore after ttl

**Comment by thomaseizinger** [comment]
Move to "New" to re-discuss if we want this.

**Comment by thomaseizinger** [comment]
TTL expired.
