### ISSUE TITLE
Implement transition for "Refundable" states

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#410]
Implement transition to "Refundable" State.

DoD:
- [ ] Transition the state when the LQS block height query future resolves

Pre-work:
Think how to keep `DefaultEvents` generic and avoid code duplication.

Child of #405.
Blocked by #384.

**Comment by D4nte** [comment]
@LLFourn to possibly cleanup. Blocked by #576

**Comment by LLFourn** [comment]
We're no longer going to add refundable states to the state machine but rather produce the actions without creating new states.
