### ISSUE TITLE
When refund is possible...

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#411]
.. the http API will return the `refund` actions. See #384 and #410.
Alice & Bob should be able to proceed with the refund.

Dod:
- [x] Implement the refund action route `GET swaps/rfc003/:id/refund`
- [x] Returns details as soon as technically possible (ie, funding has happened)
- [x] Return data to allow user to proceed with refund
- [x] Remove `#allow[dead_code]` here: https://github.com/comit-network/comit-rs/blob/6cc6ea0b1eb9018c256cfb7d5c498098ff53c2ed/application/comit_node/src/http_api/rfc003/handlers/get_swap.rs#L126-L133

Pre-work:
- Decide on the data to be returned per blockchain
- Decide on how to acquire data to build response from the state
- Maybe do #467 first

Child of #405.
Blocked by #767.
Blocked by #576.
Blocked by #679
Blocked by #693
Blocked by coblox/COMIT-RFCs#7

**Comment by LLFourn** [comment]
Blocked by https://github.com/coblox/COMIT-RFCs/issues/7
