### ISSUE TITLE
Rename bitcoin/ethereum/secp256k1 crates

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#463]
At the moment we have crates like `bitcoin_support` and `ethereum_support`.

We should rename them either upon import (`extern crate bitcoin_support as bitcoin`) or just rename them altogether.

Would make the code much nicer to import :)

- `bitcoin::Address`
- `ethereum::Address`

etc.

**Comment by D4nte** [comment]
@LLFourn & @thomaseizinger to argue it out.

**Comment by thomaseizinger** [comment]
Superseded by #626.
