### ISSUE TITLE
Do not restart blockchain dockers between 2 e2e

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#467]
Note:
`harness.js` now handles start of all dockers
However, the trigger is done from the Makefile, it decides what tests to run. May need to make `harness.js` decide on the tests (btc_eth, eth_btc) to run.

Blocked by #446
Blocked by #681

**Comment by D4nte** [comment]
@LLFourn to clarify what needs to happen and possible open/link a second issue

**Comment by LLFourn** [comment]
@D4nte edited the issue

**Comment by luckysori** [comment]
Done with #805.
