### ISSUE TITLE
Come up with logging strategy/guidelines

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#487]
At the moment, there is no consistency in what is logged where and with what level of detail.

This spike is about investigating, how the current logs could be improved and proposing an overall logging strategy that makes the logs actually useful.
This includes looking into the following topics:

- Logs should include context (SwapId)
- Log level of logs should make sense (balance between noise and useful information)
- Formatting of variables in log messages should make sense (no {:?} of [u8] !!!) (maybe be tested?)
- How to control log level from the outside
- Identify high value logging areas and share them with the team
- Making use of the `target` parameter for log-messages to have consistent modules for log messages (https://docs.rs/log/0.4.6/log/macro.error.html)

Potentially useful links:

- https://github.com/rustasync/async-log
- https://github.com/tokio-rs/tracing

Related issue: https://github.com/comit-network/comit-rs/issues/1582

**Comment by thomaseizinger** [comment]
I propose to ditch this spike and use `tracing` directly. Here is a talk that is very convincing IMO:

https://www.youtube.com/watch?v=JjItsfqFIdo

**Comment by D4nte** [comment]
Include tracing as part of the scope of the spike.

**Comment by thomaseizinger** [comment]
> Include tracing as part of the scope of the spike.

It was always there ;)
I am just suggesting that the need for a spike is probably very small and hence the barrier for starting to adopt tracing is also smaller.
Our log files are practically useless, that is why I would like to push for this :)

**Comment by D4nte** [comment]
I don't see the harm of a small spike that explains what tracing is and how it is relevant to us.

**Comment by tcharding** [comment]
Some useful links on log levels
- https://reflectoring.io/logging-levels/
