### ISSUE TITLE
⚗️ More (debug) information returned by HTTP API GET swap/:id

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#497]
Motivations:
- debugging: debug blockchain without having to dig tx id, addresses in logs
- transparency: allow user to check the tx, contract etc on the blockchain

Expose the following information in the http api:
- transaction id
- reject/decline reason
- internal failure cause if known
- addresses (HTLC)
- identities

Hints:
- The implementor should consider changing what is retrieved from the storage layer as per #576 .

Omit:
- secret (could be added as a verbose feature at a later stage)
- transient keys

Pre-work:
Grab a colleague and decide on the output format

DoD:
- [ ] Information above (if known) is returned at each state of a swap
- [ ] Make LQS go offline and create relevant info
- [ ] Decline reasons are displayed

Child of #405.
Child of #399.
Blocked by #576.
Blocked by coblox/COMIT-RFCs#6.

**Comment by D4nte** [comment]
To be reviewed once #576 is done.

**Comment by D4nte** [comment]
At first: put as much as possible in the http output
Then, can add a configuration option to protect sensitive data such as transit keys and secret.

**Comment by luckysori** [comment]
As part of #590 Bob can decline a swap request providing a reason, but this information is currently not displayed in the response to a `GET /swap/rfc003/:id` request.

Suggestion:

Make the state an object instead of a string. This object can hold the name of the state and a set of extra fields which will vary depending on the state (for `Rejected` the reason would be one of them).

**Comment by thomaseizinger** [comment]
I did some brainstorming on what this could look like. The previous AlphaRedeemedBetaFunded state could be modeled like this:

```json
{
	"state": {
  	"alpha_ledger": {
  		"current_state": "Redeemed",
  		"htlc_location": "37Ju7oTbPfe5qNAHYiAKfdTtVvCSP3TTdL",
  		"redeem_identity": "62E907B15CBF27D5425399EBF6F0FB50EBB88F18",
  		"refund_identity": "f3f2655c6de2a4c2cc00e58102252e940cc88772",
  		"funding_tx": "0x3027661dcac1a70e1ee19a20561b7e304698e52a1eae93fa340e2a1af4afd176",
  		"redeem_tx": "0x52dc163c5fbb1eef1921c21140008860558842c074eb79d3317d194fe0b773fb"
  	},
  	"beta_ledger": {
  		"current_state": "Funded",
  		"htlc_location": "0xccb882aa9d339b1af3ba01db82cf8ebb443c914c",
  		"funding_tx": "0xca7d9d05f474565dcc6f5fef0d8878d6d4e19d2cd8ba9e634e60d6658b879a9c"
  	}
  },
}
```

A couple of things to note:

- alpha_ledger is Bitcoin
- beta_ledger is Ethereum

- identities are only included if they are transient
- both objects use the same terminology (htlc_location, current_state, etc...)
- the terminology is specific to RFC003, which I think is fine. Other swap protocols may return completely different data
- state accumulates, i.e. the `funding_tx` is still there even though the state progressed to `Redeemed`

Is this roughly what you had in mind?

**Comment by LLFourn** [comment]
My mental picture was a bit different but I want to see where this one goes. I had `request` and `response` and then only have blockchain state related stuff in the `alpha_ledger` (perhaps nested in a `setup` object which tracks the state of the RFC003 setup phase).

Try and extend this description to include the assets. I'm wondering why some HTLC parameters are in the `alpha_ledger` thing but the alpha asset is not in there too. I guess these are RFC002 parameters so you include them on another layer.

**Comment by D4nte** [comment]
@thomaseizinger who did you Brainstorm with?

**Comment by thomaseizinger** [comment]
Me, myself and I!

**Comment by D4nte** [comment]
I'd suggest @thomaseizinger and @LLFourn have a chat and agree on the API :)

**Comment by thomaseizinger** [comment]
> My mental picture was a bit different but I want to see where this one goes. I had `request` and `response` and then only have blockchain state related stuff in the `alpha_ledger` (perhaps nested in a `setup` object which tracks the state of the RFC003 setup phase).
> 
> Try and extend this description to include the assets. I'm wondering why some HTLC parameters are in the `alpha_ledger` thing but the alpha asset is not in there too. I guess these are RFC002 parameters so you include them on another layer.

Yes, please note that this is just the relevant part that *changes* to the current output. Here is a full response:

```json
{
  "_links": {
    "redeem": {
      "href": "/swaps/rfc003/ba111c00-672f-4710-9a0c-199abe26b9f3/redeem"
    }
  },
  "role": "Bob",
  "state": {
    "alpha_ledger": {
      "current_state": "Redeemed",
      "htlc_location": "37Ju7oTbPfe5qNAHYiAKfdTtVvCSP3TTdL",
      "redeem_identity": "62E907B15CBF27D5425399EBF6F0FB50EBB88F18",
      "refund_identity": "f3f2655c6de2a4c2cc00e58102252e940cc88772",
      "funding": {
        "tx": "0x3027661dcac1a70e1ee19a20561b7e304698e52a1eae93fa340e2a1af4afd176"
      },
      "redeem": {
        "tx": "0x52dc163c5fbb1eef1921c21140008860558842c074eb79d3317d194fe0b773fb"
      }
    },
    "beta_ledger": {
      "current_state": "Funded",
      "htlc_location": "0xccb882aa9d339b1af3ba01db82cf8ebb443c914c",
      "funding": {
        "tx": "0xca7d9d05f474565dcc6f5fef0d8878d6d4e19d2cd8ba9e634e60d6658b879a9c"
      }
    }
  },
  "swap": {
    "alpha_asset": {
      "name": "Bitcoin",
      "quantity": "100000000"
    },
    "alpha_ledger": {
      "name": "Bitcoin",
      "network": "regtest"
    },
    "alpha_lock_duration": {
      "type": "blocks",
      "value": 144
    },
    "beta_asset": {
      "name": "Ether",
      "quantity": "10000000000000000000"
    },
    "beta_ledger": {
      "name": "Ethereum"
    },
    "beta_lock_duration": {
      "type": "seconds",
      "value": 43200
    }
  }
}
```

**Comment by thomaseizinger** [comment]
After some further discussion, @LLFourn and I settled on the following design:

```json
{
    "_links": {
        "redeem": {
            "href": "/swaps/rfc003/ba111c00-672f-4710-9a0c-199abe26b9f3/redeem"
        }
    },
    "role": "Bob",
    "swap": {
        "alpha_asset": {
            "name": "Bitcoin",
            "quantity": "100000000"
        },
        "alpha_ledger": {
            "name": "Bitcoin",
            "network": "regtest"
        },
        "beta_asset": {
            "name": "Ether",
            "quantity": "10000000000000000000"
        },
        "beta_ledger": {
            "name": "Ethereum"
        }
    },
    "state": {
        "outcome": "IN_PROGRESS | SWAPPED | NOT_SWAPPED | INTERNAL_FAILURE",
        "communication": {
            "current_state": "accepted",
            "alpha_refund_identity": "62E907B15CBF27D5425399EBF6F0FB50EBB88F18",
            "alpha_expiry": {
                "type": "blocks",
                "value": 144
            },
            "beta_redeem_identity": "f3f2655c6de2a4c2cc00e58102252e940cc88772",
            "alpha_redeem_identity": "292b0736e7e11d8fc2194563472ccd42d56deac4",
            "beta_expiry": {
                "type": "seconds",
                "value": 43200
            },
            "beta_refund_identity": "dfd278be493c83828b8845fe292b0736e7e11d8fc2"
        },
        "alpha_ledger": {
            "current_state": "redeemed",
            "htlc_location": "37Ju7oTbPfe5qNAHYiAKfdTtVvCSP3TTdL",
            "redeem_identity": "62E907B15CBF27D5425399EBF6F0FB50EBB88F18",
            "refund_identity": "f3f2655c6de2a4c2cc00e58102252e940cc88772",
            "funding_tx": "0x3027661dcac1a70e1ee19a20561b7e304698e52a1eae93fa340e2a1af4afd176",
            "redeem_tx": "0x52dc163c5fbb1eef1921c21140008860558842c074eb79d3317d194fe0b773fb"
        },
        "beta_ledger": {
            "current_state": "funded",
            "htlc_location": "0xccb882aa9d339b1af3ba01db82cf8ebb443c914c",
            "funding_tx": "0xca7d9d05f474565dcc6f5fef0d8878d6d4e19d2cd8ba9e634e60d6658b879a9c"
        }
    }
}
```

Notable changes:

1. The lock-duration move to the `communication`-state.
2. There is an overall `outcome` property that is the single-source of truth for determining the `outcome` of the swap.
3. Properties in the individual `states` accumulate as the states progress, i.e. as the `alpha_ledger` state progresses from `funded` to `redeemed`, the `funding_tx` is still listed.
4. At the moment, we don't list an internal failure reason *on purpose*. Leaking information like that through the API is not really desirable IMO. Internal failures are usually impossible to resolve in an automated fashion. Therefore, you might as well look them up in the log file (for now). As soon as we have the need from an application to show something like that, we can always extend the API.
5. Due to [possible changes](https://github.com/comit-network/comit-rs/issues/640) to the whole `reason` thing, I omitted that for now as well.

**Comment by D4nte** [comment]
Looks Good To Me. Nicely done.

**Comment by LLFourn** [comment]
@thomaseizinger shouldn't the alpha_ledger no longer contain the identities? Otherwise LGTM please create issue to implement this.

**Comment by thomaseizinger** [comment]
> @thomaseizinger shouldn't the alpha_ledger no longer contain the identities? Otherwise LGTM please create issue to implement this.

Because they are negotiated in the communication? If we are talking about the *final* identities yes. Those in the ledger state would be the transient ones though.

I just saw in the issue body that does should be omitted for now.

Let's remove them then.

**Comment by thomaseizinger** [comment]
Closed because spike is done.
