### ISSUE TITLE
Service health HTTP call 

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#522]
Implement a "service check" http endpoint to allow the user to know to what services is the comit_node connected.
- btsieve: return IP/port/status
- LND: return Pubkey/status

Best if this is done matching this RFC: https://inadarei.github.io/rfc-healthcheck/

**Comment by thomaseizinger** [comment]
Moved to "New" to be re-discussed as part of https://app.zenhub.com/workspaces/coblox-scrum-5be4c2ea4b5806bc2bf2d351/issues/comit-network/comit-rs/1122.

**Comment by thomaseizinger** [comment]
Closed because there is no need for now.
