### ISSUE TITLE
btsieve to support one ledger a time

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#557]
Make ledger configuration optional. For example btsieve should be able to start with only having bitcoin configured.

In any case, all routes of all ledgers should be registered but return errors if they are invoked and the ledger is not configured.

**Comment by thomaseizinger** [comment]
Instead of conditionally registering router, we probably want to dynamically discover, which routes are available and return a dedicated error so that users know what is going on.

This also applies to the changes that were made in #817.
