### ISSUE TITLE
Include TxId of blockchain transactions in states

### ISSUE THREAD

**Issue by LLFourn** [comit-network/comit-rs#566]
When the state progresses via a transaction being included in a blockchain we should return the txid in the HTTP api for the state (and for future states).

DOD:
- [ ] test for this in btc-eth e2e
-  [ ] stop using bitcoind's wallet to do checks but rather simply check that the txid returned from the HTTP api exist, have the correct value and are going to the correct address.

**Comment by D4nte** [comment]
superseded by #693
