### ISSUE TITLE
Split test_lib.js

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#575]
Split the test_lib.js in topic files:
- Ethereum wallet
- Bitcoin wallet
- Comit Node Conf
- LQS Conf

Note:
Keep in mind that we may want to re-use these libraries for a proper client/GUI

**Comment by elpiel** [comment]
I want to pick this up if possible. I started separating them, but not sure how exactly it's required to split them.
For example: should the WalletConf be split in such a way that `btc` and `eth` have their own implementation of the Wallet and then the CommitConf should have 2 wallets instantiated there?

**Comment by bonomat** [comment]
Hey @elpiel,

happy new year and thanks for your interest in contributing to COMIT :) 

Regarding your question: the idea is that the file `test_lib.js` is split up according different functionalities, i.e. 
* a file for ethereum wallet 
* a file for bitcoin wallet 
* a file for COMIT node conf
* a file for lqs (LedgerQueryService) conf

Note: it can be that it makes sense to split it up even more :)
