### ISSUE TITLE
Allow comit_node to specify reason of reject or decline over BAM

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#583]
To make Reject/Decline more verbose over BAM, following changes are proposed:
- allow user to pass a number of pre-defined reason when declining a swap
- use different reject reasons internally

Proposal:
```
pub enum SwapReject {
    Declined {
        pub enum Reason {
            Liquidity,
            Rate,
            Unspecified,
            AlphaTimeout,
            BetaTimeout,
        }
    },
    Rejected {
        pub enum Reason {
            UnsupportedLedger,
            InternalError,
        }
    }
}
```

Note:
BAM allow SE20 and above errors to be used by the application.

DoD:
- do it
- update the COMIT RFC

**Comment by thomaseizinger** [comment]
Outdated.

**Comment by D4nte** [comment]
Not outdated but replaced with comit-network/RFCs#23
