### ISSUE TITLE
⚗️ Storage interface

### ISSUE THREAD

**Issue by LLFourn** [comit-network/comit-rs#592]
Motivation:  Make the saving of data atomic across both stores to guarantee consistency of the data (ie, not have something in one store but not in the other)

Right now we have `state_store` and `metadata_store`. We should not have two "stores" but one thing which remains internally consistent and guarantees gives us guarantees (callers should not have to deal with getting metadata out and then failing to get the state somehow).

Note:
Closures may be the easiest way to proceed.
(pass the swap metadata in the closure)

DoD:
- [ ] Present a possible solution

Blocked by #497

**Comment by LLFourn** [comment]
I'm blocking this by #497 because it will likely change how storage works in some way.

Blocked by #497

**Comment by D4nte** [comment]
Close this as yes, it could happen but it is very unlikely to happen (crash mid-right).
Also, it may get solved by ensuring the writing sequence is correct (write metadata first) and the use of a DB (that provide atomic writes).
