### ISSUE TITLE
cargo make build fails

### ISSUE THREAD

**Issue by selvatica** [comit-network/comit-rs#601]
Compiling ledger_query_service v0.1.0 fails.

I used "cargo update" prior to "make build".

[make_build.log](https://github.com/comit-network/comit-rs/files/2701128/make_build.log)

Maybe the issues has got to do something with a missing zmq_ffi library?

**Environment:**
 - OS: [ Ubuntu 16.04.5 LTS 64bit ]
 - Rust version [rustc 1.32.0-nightly (14997d56a 2018-12-05)]
cargo 1.32.0-nightly (5e85ba14a 2018-12-02)
 - CoBloX Version []

**Comment by thomaseizinger** [comment]
Zmq needs to be installed on your machine. For Ubuntu, you can install it via the apt-package `libzmq3-dev`.
