### ISSUE TITLE
No unwrap policy 

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#604]
Review code and ensure we have no unwrap nor expect anywhere. 

Note: you can use `?` in tests and main.

Pre-work:
- [ ] See if no unwrap/expect lint exist

DoD
- [ ] use it

**Comment by bonomat** [comment]
This is not a single-task ticket but more a developer mentality.

**Comment by D4nte** [comment]
@bonomat it is a single task ticket: check if link exists and activate it.

**Comment by thomaseizinger** [comment]
> @bonomat it is a single task ticket: check if link exists and activate it.

That part is a single task but the issue also says

> Review code and ensure we have no unwrap nor expect anywhere.

which is, and we agreed on that in the grooming yesterday, impossible to do, hence our comment.

**Comment by D4nte** [comment]
@comit-network/rust-devs is anyone keen on the clippy lint?
