### ISSUE TITLE
`cargo make` requires `libssl-dev`

### ISSUE THREAD

**Issue by elpiel** [comit-network/comit-rs#610]
**Describe the bug**

I have relatively new installation of Ubuntu and I didn't have OpenSSL and it failed to build.

Maybe it should be mentioned in the README as dependency?

Also running `cargo make` for first time, I needed `nvm` as well as `yarn` for `cargo make`, otherwise it was failing to build.

**To Reproduce**

1. `cargo make`

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - rustc 1.32.0-nightly (14997d56a 2018-12-05)
 - CoBloX Version 5a2eeff1ef8cc5aa8521b659cf8eb0ed7a14fc4b 
 
**Logs, Screenshots**

![screenshot from 2018-12-31 16-45-16](https://user-images.githubusercontent.com/8925621/50563256-89483680-0d1b-11e9-97da-3071ace441a0.png)

**Comment by D4nte** [comment]
Hi @elpiel,

Thank you for the report! We have on our todo list to build/run comit-rs from a fresh install so in the meantime your issue is very useful.

We will update the README shortly with your suggestions!
