### ISSUE TITLE
Use tomlfmt

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#634]
https://github.com/tbrand/cargo-tomlfmt to fmt Cargo.toml files

Blocked by tbrand/cargo-tomlfmt#12.

**Comment by bonomat** [comment]
The corresponding branch #771 has been closed due to inactivity of the tool. This ticket is to be revisited in the future as soon brand/cargo-tomlfmt#12 has been fixed.

**Comment by D4nte** [comment]
Superseeded by #1083
