### ISSUE TITLE
ERC20/ETH Htlc log needs to emit secret

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#638]
While doing #412 a security issue was found: 

We cannot rely on the fact that the transaction redeeming an HTLC:
a) was sent to our HTLC
b) nor contains the secret in the data field

For example, one could create another contract (contract A), which `calls` the HTLC contract (contract B) in order to redeem it. The transaction invoking contract A might not have the secret as data, and the `call()` to contract B is not tracked in the transaction receipt. 

Hence, our HTLCs need to log the secret when it was successfully redeemed.

Blocked by #756

**Comment by bonomat** [comment]
Please note the scope of this ticket has changed: 

* [ ] ERC20/ETH contracts are emitting the secret when redeemed
* [ ] LQS needs to return `TransactionReceipt` instead of `Transaction` when `?expand_results=true` is requested
* [ ] LQS client needs to handle the `TransactionReceipt` and extract the secret from its logs

Doing this ticket without #639 probably does not make much sense.

**Comment by LLFourn** [comment]
With #756  this is how you should go about doing this ticket:
Make LQS return BOTH the TransactionReceipt AND the Transaction when `?expand_results=true` (note preferably just make two `show_transaction=true&show_receipt=true`)

You should start here: https://github.com/comit-network/comit-rs/tree/638-emit-secret-in-htlc (and rebase on to master).

**Comment by D4nte** [comment]
@LLFourn I don't agree re token amount. The smart contract emitting "redeemed" should be enough to know that all token were transferred as we know that the smart contract code is correct.
We trust the smart contract code and we trust LQS to find the correct one.
We should not need to double check the token amount on comit_node side.

**Comment by bonomat** [comment]
If we are fine with having this trust in our system then we don't need it. 
I would opt for a `verify don't trust` approach though. 
It's not so complicated to do verify the amount, the data is in the receipt and it does not cost us any performance as it's a simple equal check.

**Comment by D4nte** [comment]
Ok, I did not read properly. Yes, agreed to have the amount as part of the `funding` future. I thought we wanted it as part of the `redeem` event as this issue is about redeeming...

**Comment by thomaseizinger** [comment]
Fixed in #784.
