### ISSUE TITLE
Extract secret from transaction receipt

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#639]
This ticket relates to #638 and needs to be implemented for the COMIT node : 

For Ethereum we need to extract the secret from the log of a transaction which can be retrieved from a transaction receipt and not from the data of a transaction. 

Impl advice:
* LQS returns a tx hash
* Get transaction receipt for that tx
* Extract the secret from the logs 

Blocked by #638

**Comment by thomaseizinger** [comment]
Fixed in #784.
