### ISSUE TITLE
Find a better way for handling mergify

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#641]
Currently, there is a mergify rule that checks for a selected checkbox with the label **Ready to merge** to actually trigger the automatic merging:

https://github.com/comit-network/comit-rs/blob/f482a956a15f45be325f32889b6889e775b04a62/.mergify.yml#L8

I'd consider this to be a hack around the way it is supposed to work and would like to find a way on how we not have to rely on this.

As far as I understand, the problem is that without a label "work-in-progress", mergify will just merge as soon as the PR is approved, even though the owner might still have some work locally that they would want to include.

Let's discuss other ways on how we can prevent this from happening :)

**Comment by D4nte** [comment]
`ready-to-merge` label

**Comment by thomaseizinger** [comment]
Indeed, such a label would solve the problem. I wonder if there is more ergonomic way though, without an additional user interaction.

**Comment by D4nte** [comment]
@thomaseizinger do you mind doing a separate chat with that? I have 0 opinion on the matter.

**Comment by bonomat** [comment]
Kribaros!

**Comment by D4nte** [comment]
`automagically-mergify-this`

I trust in you @thomaseizinger you have my vote

**Comment by thomaseizinger** [comment]
Ah, I like the name pun! I am sold :)
