### ISSUE TITLE
Add Network support as per RFC-002

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#644]
As per [RFC-002](https://github.com/coblox/COMIT-RFCs/blob/master/RFC-002-SWAP.md) and [COMIT-registry](https://github.com/coblox/COMIT-RFCs/blob/master/COMIT-registry.md), the following changes should be done to COMIT-rs:
- [x] Add support of `network` parameter for Ethereum (Done with #687)
- [x] Use `mainnet` for Bitcoin mainnet (instead of `Bitcoin`) (Done with #806)

Related to #376

**Comment by D4nte** [comment]
@luckysori with what pull request did you tick the Ethereum box?

**Comment by luckysori** [comment]
> @luckysori with what pull request did you tick the Ethereum box?

Good question. It's #687. I'll add it to the issue body.

**Comment by D4nte** [comment]
Looks good.

**Comment by luckysori** [comment]
Closed with #806.
