### ISSUE TITLE
⚗️ Decentralised orderbook - tech investigation

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#654]
Find the technology to exchanges offers.

Investigate several choices and present top candidate(s).
Research can be done in parallel (update the issue with assignee):
- [x] dht-bittorrent (@D4nte)
- [x] libp2p (@thomaseizinger)
- [x] ipfs (@bonomat )
- [x] webrtc (@luckysori)

Note:
The implementation will need to be modularised (ie, can swap for another tech).
When investigation a tech, keep in mind how they solve (and whether we can re-use) the following:
- seeding (how to get initial peers)
- peer discovery (how to get more peer once connected to initial peers)
- usable in a webapp?
- how does authentication/identification work?
- Are metadata/data/messages authenticated?

1 sprint of research max

DoD:
- [x] Proposal of several candidates & debate & decision meeting
- [x] May need to do further research or seeding and peer discovery (or may not)

Child of #649

**Comment by D4nte** [comment]
@D4nte to create a meta page in the wiki to point to sub-pages per tech

**Comment by bonomat** [comment]
Something we should have a look at as well: https://tendermint.com/

**Comment by D4nte** [comment]
Next: #728
