### ISSUE TITLE
⚗️ Write-up step by step description of "forward a swap request"

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#656]
Given an incoming SWAP request, it should be possible to create a new one based on the parameters of the incoming one, which results in a "three-way atomic swap".

For example:

1. Alice sends a SWAP Request to Bob for swapping x BTC to y XMR.
_Bob doesn't have XMR but he has ETH and knows that Charlie has XMR._
2. Bob sends a SWAP Request to Charlie for swapping z ETH to y XMR.

The goal of this spike is to answer the following questions:

- What are valid parameter combinations for such a three-way atomic swap?
- Do we need a re-negotiation of some parameters for such a three-way swap? (Which extensions to the COMIT protocol are required for that?)
- Where will this functionality be implemented? (application vs. COMIT node)

Child of #653.

**Comment by bonomat** [comment]
Closed because low priority.
