### ISSUE TITLE
Fill addresses with Metamask (integration)

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#659]
Traders can use metamask to load addresses using the UI.

The component has to be created with #18

DoD:
- [ ] Use metamask to get address to send in swap request (landing page)
- [ ] Use metamask to get address to send in swap request (manual form)

Blocked by #18
Blocked by #16
Blocked by #11
Child of comit-network/comit-rs#658

**Comment by thomaseizinger** [comment]
This one is a duplicate and doesn't belong in comit-rs.
