### ISSUE TITLE
⚗️How to realize same chain trades on Bitcoin 👹

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#666]
Similar to #665, same chain trades on Bitcoin are also possible when using the omni layer [1] or other colored coins. 

Focus should be on trading on Bitcoin e.g. Bitcoin <-> Omni Layer, Lightning <- > Omni Layer

DoD:
- [ ] Presentation of the protocol with light documentation
- [ ] Issue created to write RFC

[1] [Omni Layer](https://www.omnilayer.org/)

Child of #663 
Child of 🔥👺🔥

**Comment by D4nte** [comment]
https://github.com/OmniLayer/spec

**Comment by D4nte** [comment]
[unorganized notes](https://github.com/coblox/docs/wiki/Omnilayer)

Quick meeting to be done.

**Comment by D4nte** [comment]
See notes: https://github.com/coblox/docs/wiki/Omnilayer

This issue will be closed in favour of a new issue where we create an HTLC on testnet and check whether ominlayer wallets recognized the transfer of omnicoin ownership throught P2WSH script.

**Comment by D4nte** [comment]
#691 created as followup.
