### ISSUE TITLE
⚗️Key derivation and secret seed storage

### ISSUE THREAD

**Issue by LLFourn** [comit-network/comit-rs#672]
The purpose of this spike is answer the following:

How should we take some secret data and use it to derive:

- transient keys within the various protocols 
- the node identifying key

How should we store this secret?
How should the generation happen? Automated or Manual?
Should we provide backup strategies (ie, mnemonic)

hint: look at other projects an summarise the best approaches

Child of #744

**Comment by thomaseizinger** [comment]
Cross referencing an idea here on how to extend the `Seed` type:

https://github.com/comit-network/comit-rs/pull/878#discussion_r279615646
