### ISSUE TITLE
⚗️ Minimalistic UI

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#694]
Expected outcomes of the spike:

- Define level of technical expertise of expected user.
- Produce a list of minimal UI features, such as:
  * Connect app to your COMIT node.
  * Post an order.
  * Cancel an order.
  * List your open orders.
  * List others' orders.
  * Take someone else's order.
  * Filter orders.
  * Hide orders.
- Determine whether it should be a web app and if we should provide an alternative way to run locally.

Hint: draw inspiration from exchanges such as Bittrex.

DoD:
- [ ] Pen and paper design

Child of #726.

**Comment by D4nte** [comment]
Can we have an Epic for the OKR please?
