### ISSUE TITLE
LQS client test is not testing correctly

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#727]
The test in `application/comit_node/src/ledger_query_service/client.rs` should be improved as it contains outdated fields right now and the test it self does not detect it.

**Comment by D4nte** [comment]
Related to #638

**Comment by D4nte** [comment]
I don't think this is a valid concern. `comit_node` should not fail if LQS sends back unknown fields.
Allowing unknown fields gives us backward compatibility, forbidding gives us pain.
