### ISSUE TITLE
Update comit.network website

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#731]
The website of COMIT.network is super boring and only links to the outdated whitepaper and github. We should update it with a new design or at least link COMIT RFCs in addition to the white paper.

We cannot access the website so:
A. Propose suggestions to Paul
B. OR get access

**Comment by D4nte** [comment]
Also need to replace the address with S&C or remove it entirely.

**Comment by thomaseizinger** [comment]
Why is this in the comit-rs repository? :O 
This doesn't really seem to concern the comit-rs implementation.
