### ISSUE TITLE
Travis doesn't run Rust Doc-tests

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#734]
When running `cargo test` locally `Doc-tests` are run, but on Travis that is not the case.

Hint: check the Makefile

**Comment by thomaseizinger** [comment]
The issue is that we are using `cargo test --all --all-targets` which [doesn't run the doc tests](https://github.com/rust-lang/cargo/issues/6669).

I am investigating ways on we can change the Makefile to still run them.
