### ISSUE TITLE
Fix ConnectionPool race condition

### ISSUE THREAD

**Issue by LLFourn** [comit-network/comit-rs#735]
Right now If two nodes try to connect to each other at the same time something nasty can happen.

node A  -------------> node B
node A <------------- node B

node A will ignore node B's connection because it is already trying to connect and node B will ignore node A's connction because it is always trying to connect. Both connections will be dropped and so there will be no connection. Swap requests sent down any of these temporary connection will just die.

We need a design that doesn't have these problems but also doesn't allow nodes to spam other nodes with connections.

hint: Don't just drop incoming connections because you're connected or connecting. It's fine to allow a single incoming connection from a given node id. 

Blocked by #739

**Comment by thomaseizinger** [comment]
We could design a `BAM` message that allows nodes to inform the other that a certain connection should be dropped in favor of a different one. For this we would maybe need session identifiers though.

**Comment by thomaseizinger** [comment]
Obsolete as per decision in #779 to use libp2p.
