### ISSUE TITLE
⚗️ Find a good name for LQS

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#747]
Maybe LQS is fine and we can find a [Backronym](https://en.wikipedia.org/wiki/Backronym)?

**Comment by D4nte** [comment]
where_is_my_money
money_watcher
watchmen
watchoblocko
watchit

**Comment by D4nte** [comment]
ledger_sieve

**Comment by D4nte** [comment]
block_sieve

**Comment by D4nte** [comment]
btsieve wins!
