### ISSUE TITLE
Replace `ItemCache` with `futures::shared`

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#751]
The functionality provided by the [`ItemCache`](https://github.com/comit-network/comit-rs/blob/master/application/comit_node/src/item_cache.rs) is actually already provided by the `futures` library.

It is called [`.shared`](https://docs.rs/futures/0.1/futures/future/trait.Future.html#method.shared).

Pre-work: maybe `ItemCache` is not used anymore and it is just a question of removing it from the codebase.

**Comment by D4nte** [comment]
Done!

**Comment by D4nte** [comment]
`ItemCache` is still here but unused.
