### ISSUE TITLE
Use dependabot

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#753]
In order to keep our dependencies up-to-date, we should install dependabot at some point.

- it can be instructed to not open more than X PRs at the same time (in order to avoid spamming)
- dependabot can merge and rebase PRs on its own
- I am pretty confident that our testsuite would uncover any problem during the upgrade

**Comment by D4nte** [comment]
Didn't we recently said that we would just update all dependencies before releasing? @LLFourn

**Comment by bonomat** [comment]
> Didn't we recently said that we would just update all dependencies before releasing? @LLFourn

Yes we did :)

**Comment by thomaseizinger** [comment]
> Didn't we recently said that we would just update all dependencies before releasing? @LLFourn

Sorry, I wasn't aware of such a decision.

But even if, the point of a bot like dependabot is to discover issues early and being up-to-date constantly (like breaking API changes) instead of building on old versions for ages and then updating everything in one go.
It is just to make our lives easier and having one thing less that we need to do manually and care about.

**Comment by bonomat** [comment]
Can we run dependabot on demand? Meaning, just before release we say: `update all dependencies`

**Comment by thomaseizinger** [comment]
Yes you can trigger a dependabot run from the dashboard.
However, I'd still like to have it done automatically so that we can just release at any time without having to do major pre-work. We also don't wait for our PRs to be merged until we release. To me, updating dependencies is similar to that.

An issue I can see is that dependabot might keep our CI busy while we are trying to merge stuff in but there is a solution to this:

1. Dependabot can be configured to run daily, weekly or monthly.
2. It can be configured to run at any time of the day (like 1am)
3. You can opt-out of *immediate* auto-rebasing of PRs
4. Open PRs will still be rebased at the next scanning time (like 1am)
5. The number of open PRs can be limited

The combination of these settings should give us the following:
1. Our CI is only busy with building dependency updates while we are *not* working
2. Every morning, we can immediately merge one PR. Doing that doesn't trigger any builds since auto-rebase is off. If we want to merge more dependency updates, we can manually trigger it using `@dependabot rebase` (or just wait for the next day!)

**Comment by bonomat** [comment]
> An issue I can see is that dependabot might keep our CI busy while we are trying to merge stuff in but there is a solution to this:

That in addition to having too many PRs opened are the things I would like to avoid. 

> The combination of these settings should give us the following:
> 
> 1. Our CI is only busy with building dependency updates while we are _not_ working
> 2. Every morning, we can immediately merge one PR. Doing that doesn't trigger any builds since auto-rebase is off. If we want to merge more dependency updates, we can manually trigger it using `@dependabot rebase` (or just wait for the next day!)

What if we just do this once a week? Let this thing do its job over the weekend, and on Monday (or if someone is eager during the weekend) we merge all PRs.

**Comment by thomaseizinger** [comment]
> That in addition to having too many PRs opened are the things I would like to avoid.

As mentioned, the settings can be tweaked in various ways to basically prevent dependabot from using our CI if we don't want it to. In addition, mergify should also help us in not having to care so much of when things are merged once they are reviewed and approved.

> What if we just do this once a week? Let this thing do its job over the weekend, and on Monday (or if someone is eager during the weekend) we merge all PRs.

I think, finding the ideal timeslot/update frequency that works best for is a matter of simply trying it out. The reason I'd prefer daily checks of weekly once is that it would probably end up in having x dependabot PRs open every morning up until all the dependencies are up-to-date. If we only do weekly checks, this will take a long time. The maintainer also just implemented a cool feature recently that fits into this context: https://github.com/dependabot/feedback/issues/365

> Is it possible to exclude certain libraries? I could imagine that we might not want to jump onto a new version of critical libraries and rather stay with older well-tested one, e.g. rust-bitcoin?

Yes. If you close a dependabot PR, you won't get any updates for this version. You can also choose to ignore updates up until to a new version in a specific version range e.g. ignore all patch updates up until to the next minor version.

On the note of `well-tested`, this blog post might of interest: https://dependabot.com/blog/the-latest-dependency-version-is-probably-the-most-secure/

**Comment by bonomat** [comment]
> On the note of `well-tested`, this blog post might of interest: https://dependabot.com/blog/the-latest-dependency-version-is-probably-the-most-secure/
Quoting from the blogpost:
>
>> Put another way, if your dependencies are totally up-to-date you’re just as secure as someone pursuing a late adopter strategy, but have the additional advantage that you can respond to new disclosures more easily.
>> Finally, it's surprising to see the “reactive” strategy perform so badly. It’s twice as likely to be vulnerable as the “always up-to-date” strategy, and the “fix by upgrading” flow is likely to be just as difficult as for the “late adopter”.

There is one thing missing in this blog post which I am more concerned about due to the bleeding edge space we are living in: 
If a new bug is only introduced with a new version, the `always up-to-date` will perform worse.

Obviously, if a library update fixes some vulnerabilities then we should upgrade, if it only does minor changes, improve performance or maybe add new features, we probably can wait.

**Comment by D4nte** [comment]
If we were to choose a frequency I'd go for _monthly_. This means that only every other sprint would be impacted by "checking the deps that cannot be merged by themselves".
It'll also leave a bit of leeway to not jump of fresh new (broken/vulnerable) versions.

**Comment by thomaseizinger** [comment]
> If a new bug is only introduced with a new version, the `always up-to-date` will perform worse.

I don't quite get what you are saying here. Bugs are always introduced with new versions, no? I think the study is also meant to show that even if you run into a bug by always being up-to-date, you are still better off because you will also receive the bugfix faster.

> if it only does minor changes, improve performance or maybe add new features, we probably can wait.

but why wait? To do massive upgrades every 2 months that stop development for a day or two?

> If we were to choose a frequency I'd go for _monthly_.

Monthly checks will mean it takes us basically *forever* to update all deps unless you want to allow dependabot to open 15 or more pull requests at once.

Maybe the intention why I brought this up is not clear: I want to eliminate the need for thinking about the topic of updating dependencies by having it automated as much as possible.
It is about establishing trust into the test infrastructure and enforcing that all essential things are automatically tested.
Updating a dependency should be a breeze and possibly even automated if the build passes.

Also, we shouldn't forget that it is *just* the master branch. There is no automatic deployment to anywhere (and I don't see a reason why it ever would be given the nature of our software).

Here are the advantages I see:
- we incorporate breaking API changes as early as possible instead of building ontop of the old API
- people who try out our "nightly" build, i.e. fresh off master, can report problems much earlier if a dependency causes a problem on their machine
- security fixes in libraries are automatically delivered
- updating dependencies is no longer a manual concerns, it just happens as part of daily admin work (once we are over the first wave of PRs, I'd even do daily checks depending on the number actual PRs that arrive)

**Comment by bonomat** [comment]
> Maybe the intention why I brought this up is not clear: I want to eliminate the need for thinking about the topic of updating dependencies by having it automated as much as possible.

Yes, I get that. I just think we use some critical libraries here which we should not blindly update. 
There was actually one statement in one of today's talks at Financial Crypto where they mentioned exactly this. A library for generating keys introduced a new bug where the random generator was broken. Lots of people updated immediately and lots of faulty keys were generated. 
I have to admit that they also said that this bug was fixed within a couple of days with a new version. Weirdly though was that it took about a year for everyone to update to the fixed version :D 

> Also, we shouldn't forget that it is _just_ the master branch. There is no automatic deployment to anywhere (and I don't see a reason why it ever would be given the nature of our software).

This is actually a good point and would probably have a similar effect: If we update immediately but only release biweekly (or anything else, just not continuously) then the released version has passed its `testing` period.

**Comment by D4nte** [comment]
I am keen to try out @thomaseizinger 's proposal and then learn from it and if it becomes too much overheard then rediscuss.

**Comment by D4nte** [comment]
Weekend run. 5/6 PRs per week.

**Comment by D4nte** [comment]
Setup done:
- Weekly trigger Saturday 1am
- 5 "Limit of open pull requests per repo/language (blank for unlimited)"
- auto rebase

**Comment by D4nte** [comment]
@bonomat please whitelist dependabot in https://cla-assistant.io/

**Comment by thomaseizinger** [comment]
> auto rebase

I think this is a bad idea. This will make dependabot rebase everytime the master branch changes, which will trigger X builds on Travis with X being the number of open dependabot PRs.

**Comment by D4nte** [comment]
> > auto rebase
> 
> I think this is a bad idea. This will make dependabot rebase everytime the master branch changes, which will trigger X builds on Travis with X being the number of open dependabot PRs.

And mergify handles rebase anyway. Now corrected.

**Comment by bonomat** [comment]
Done.

**Comment by thomaseizinger** [comment]
I just was about to comment here, that it would be nice if we could make use of the dependabot configuration file and not having this stuff tracked in their settings. Can we re-open and make this the DoD of this ticket?

**Comment by bonomat** [comment]
> I just was about to comment here, that it would be nice if we could make use of the dependabot configuration file and not having this stuff tracked in their settings. Can we re-open and make this the DoD of this ticket?

I wouldn't mind, but since this ticket had already quite some discussions, maybe just open a new one?
