### ISSUE TITLE
Remove dbg! macros from master (and prevent it)

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#760]
Those macros should either be removed or replaced with proper log statements (hint: they are in the noise handshake crate).

If I am not mistaken, `dbg` macros are not meant to be present in production code

Activate [new clippy warn](https://github.com/rust-lang/rust-clippy/pull/3723) as part of this issue (will need a toolchain update)

**Comment by D4nte** [comment]
is there an available clippy warning similar to `println` ?

**Comment by thomaseizinger** [comment]
Given that `dbg` is still pretty new, I don't think so :(
