### ISSUE TITLE
Deployment and funding transactions not always available

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#763]
We want to store the IDs of the deployment and funding transactions, but currently `LedgerEvents::htlc_deployed` returns `htlc_location` and `LedgerEvents::htlc_funded` an `Option<FundTransaction>`.

**Comment by D4nte** [comment]
Where do we want to store that? logs?

**Comment by luckysori** [comment]
The same way we store redeem and refund transactions, in the state store.

**Comment by D4nte** [comment]
But then is the software suppose to use them?

**Comment by luckysori** [comment]
> But then is the software suppose to use them?

The intention is to return them as part of a `GET /swaps/rfc003/:id` request.
