### ISSUE TITLE
Don't unwrap in constructor of `SwapDescription`

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#765]
Currently, we are unwrapping the constructor of `SwapDescription` after the `to_http_ledger` and `to_http_asset` call:

https://github.com/comit-network/comit-rs/blob/6cc6ea0b1eb9018c256cfb7d5c498098ff53c2ed/application/comit_node/src/http_api/rfc003/handlers/get_swap.rs#L136-L147

Even though the error is quite rare, we should not do this.

Passing on the error is tricky since there are different ones for `HttpLedger` and `HttpAsset`.
Some investigation on serialization uncovered that there might actually be a better way to achieve contextual serialization, which is the reason why `HttpLedger` and `HttpAsset` were introduced.

A different approach would be to create a generic wrapper struct `Http<T>` that is used in all payloads where a different serialization for a type is needed, for example:

```rust
#[derive(Clone, Debug, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct SwapRequestBody<AL: Ledger, BL: Ledger, AA: Asset, BA: Asset, PartialIdentities> {
    alpha_asset: Http<AA>,
    beta_asset: Http<BA>,
    alpha_ledger: Http<AL>,
    beta_ledger: Http<BL>,
    alpha_expiry: Timestamp,
    beta_expiry: Timestamp,
    #[serde(flatten)]
    partial_identities: PartialIdentities,
    #[serde(with = "http_api::rfc003::socket_addr")]
    peer: SocketAddr,
}
```

Since `Http<T>` is a local type, one can `impl Serialize for Http<Bitcoin>` to define a serialization for this context. Doing so would remove the need for `HttpLedger` and `HttpAsset` which would also simply get rid of the code that contains the `unwrap` that is mentioned at the beginning of this ticket.

As part of doing this, you will probably need [custom trait bounds for serde](https://serde.rs/container-attrs.html#bound).

**Comment by luckysori** [comment]
Resolved with #785.
