### ISSUE TITLE
Test the serialization of primitive types used in HTTP API

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#766]
Test the format of primitive types used in HTTP API.
E.g: Test that an Ethereum address is serialized as expected against a string.

DoD:
- [ ] Format test (ie, serialization of specific types) should go to Rust tests.

**Comment by D4nte** [comment]
Are you talking about Rust test? because in term of http API test we have the `dry` folder.

**Comment by luckysori** [comment]
Yeah, you are right. This just means that the dry tests should be expanded to check that _all_ the different HTTP API endpoints are working correctly.

**Comment by thomaseizinger** [comment]
To clarify this further, this ticket is about testing the _information_ that is returned by the API, e.g.:

- correct shape
- correct data types
- correct formatting (leading `0x`)
- etc

I am not sure if all of this should go into `api_tests/dry`.

**Comment by D4nte** [comment]
Actually, now we have a test against JSON schema in the `api_tests` dry of comit-rs replies.

Here, I think we should only add Rust test to check the format of JSON strings.

**Comment by D4nte** [comment]
@luckysori, @tcharding is going to comment on the direction he is going on. Please let us know whether it's correct.

**Comment by tcharding** [comment]
Proposed direction:  grep the HTTP API directory for implementations of `Serialize` then write a passing unit test for each one.  The purpose of this is that the tests will make the serialization explicit.  If the current serialization is incorrect it may be caught during review.  Additional purpose; if/when the code changes later the tests will break.

**Comment by tcharding** [comment]
Perhaps linking of PRs to issues does not work for draft PRs?  Please see PR #1052

**Comment by D4nte** [comment]
> Perhaps linking of PRs to issues does not work for draft PRs? Please see PR #1052

You forgot `#` in front of the issue number + you have to manually link for ZenHub by installing the ZenHub extension.

**Comment by tcharding** [comment]
> Proposed direction: grep the HTTP API directory for implementations of `Serialize` then write a passing unit test for each one. The purpose of this is that the tests will make the serialization explicit. If the current serialization is incorrect it may be caught during review. Additional purpose; if/when the code changes later the tests will break.
> 
> ```
> $ git grep 'impl Serialize for' mod.rs
> mod.rs:impl Serialize for Http<bitcoin_support::Transaction> {
> mod.rs:impl Serialize for Http<bitcoin_support::PubkeyHash> {
> mod.rs:impl Serialize for Http<ethereum_support::Transaction> {
> mod.rs:impl Serialize for Http<ethereum_support::H160> {
> mod.rs:impl Serialize for Http<bitcoin_support::OutPoint> {
> mod.rs:impl Serialize for Http<SwapProtocol> {
> mod.rs:impl Serialize for Http<PeerId> {
> mod.rs:impl Serialize for Http<SwapId> {
> ```

Turns out most of these are tested already.  The only ones left to do are `SwapProtocol` and `PeerId`.
