### ISSUE TITLE
Consolidate e2e tests

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#767]
There is excessive code repetition in e2e tests. These tests should be generalised since for every pair of ledgers we follow pretty much the same steps. This should make it much easier to modify them in the future or add more ledger pair combinations.

Additionally, consider adding test logs.

**Comment by D4nte** [comment]
Can you provide some code block examples on the repetition and what you are aiming to delete?

**Comment by luckysori** [comment]
> Can you provide some code block examples on the repetition and what you are aiming to delete?

I think @thomaseizinger may be able to better explain his vision, since he suggested this ticket.

In terms of examples, putting [btc_eth/test.js](https://github.com/comit-network/comit-rs/blob/c797f951726b6fc032c1e426cfbb8686aa05ffda/api_tests/e2e/rfc003/btc_eth/test.js) and  [eth_btc/test.js](https://github.com/comit-network/comit-rs/blob/master/api_tests/e2e/rfc003/eth_btc/test.js) side by side makes this issue quite obvious, because they're pretty much identical except for things like Bob's response, which could be stored in variables.

**Comment by thomaseizinger** [comment]
> In terms of examples, putting [btc_eth/test.js](https://github.com/comit-network/comit-rs/blob/c797f951726b6fc032c1e426cfbb8686aa05ffda/api_tests/e2e/rfc003/btc_eth/test.js) and [eth_btc/test.js](https://github.com/comit-network/comit-rs/blob/master/api_tests/e2e/rfc003/eth_btc/test.js) side by side makes this issue quite obvious, because they're pretty much identical except for things like Bob's response, which could be stored in variables.

Yes this is basically it.
The tests only test the workflow of doing a swap, which is the same for all swaps since
- the flow is defined by `rfc003`
- the actions are self-descriptive and the tests don't care
- the parameters are set in the request by Alice and in the response of Bob, both could be dynamically fetched from the _instance_ of the actors (Alice and bob)

**Comment by LLFourn** [comment]
quick note about what this looks like in my mind. I want to be able to specify a test generically:

```
alice_choices = ["fund", "redeem"];
bob_choices = ["fund", "redeem"];

let result = await test_executor.execute(alice_choices, bob_choices);
// check the correct balances at the end
```

There area few ways we could arrange this but the important part is that we can declare Alice and Bob's behaviour and test the result. We would also probably want a callback for each action so you could do some particular tests that are run at that particular stage.

**Comment by thomaseizinger** [comment]
Interesting idea, thank you for the input @LLFourn !

**Comment by D4nte** [comment]
@LLFourn I am startng to work on that and not totally sold by the idea of passing actions as we only test the happy path.

Is the intent to add more test for scenarios where a party declines or does not proceed with an action?

**Comment by LLFourn** [comment]
@D4nte yes.
