### ISSUE TITLE
Fix up "WIP" for mergify/wafflebot

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#770]
Waffle bot adds "review" labels for PRs, even if they have a WIP label/in title.

With the new "draft" PR from github. We should remove "WIP in title hooks" and probably check with waffle support so that:
- Draft PR stay label as "work-in-progress"
- Normal PR are labelled "review"

The "automagically-merge-this" label behaviour should remain unchanged.

**Comment by thomaseizinger** [comment]
You moved this to "review" because of #780 but that is now merged. However, this is apparently blocked by [waffleio/waffle.io#3832](https://github.com/waffleio/waffle.io/issues/3832)?

Please make up your mind :)

**Comment by D4nte** [comment]
Well, I don't consider it blocked :)
