### ISSUE TITLE
Rename GetActions and PostActions to LedgerActions and CommunicationActions

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#773]
At the moment, we have these constructs of `GetAction`:

https://github.com/comit-network/comit-rs/blob/e0aaad77e50f600e56db8cc6f303896a1262477a/application/comit_node/src/http_api/rfc003/handlers/get_action.rs#L61-L67

and `PostAction`:

https://github.com/comit-network/comit-rs/blob/e0aaad77e50f600e56db8cc6f303896a1262477a/application/comit_node/src/http_api/rfc003/handlers/post_action.rs#L104-L108

The current name is driven by the associated HTTP method of the action. I propose that a better name for these might be:

- `LedgerActions` instead of `GetAction` because all the actions represent actions performed on ledgers
- `CommunicationActions` instead of `PostActions` because they represent actions being taken in the communication phase

This would make the wording more in-line with the terminology that we currently build up in the rest of the codebase.

**Comment by thomaseizinger** [comment]
This may need to be reconsidered with the changes done in #783.

**Comment by D4nte** [comment]
Invalid due to #783 changes.
