### ISSUE TITLE
Extend `EmbeddedSwapResource` for GET /swaps with swap parameters and available actions

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#776]
Currently, the `EmbeddedSwapResource` only contains the current state and the protocol.

https://github.com/comit-network/comit-rs/blob/c797f951726b6fc032c1e426cfbb8686aa05ffda/application/comit_node/src/http_api/rfc003/handlers/get_swaps.rs#L17-L21

However, if applications want to provide a list of current swaps (with their parameters inlined), the need to do n+1 requests to the COMIT node.

I propose to add the parameters of the swap + the available actions to the `EmbeddedSwapResource`.

**Comment by D4nte** [comment]
Not that I want to pre-optimise but I guess the question is how much would it cost to fetch this info upfront?
I assume can't really answer that until we have concrete storage.

**Comment by thomaseizinger** [comment]
Pagination is usually used to put an upper bound onto this.

**Comment by thomaseizinger** [comment]
Resolved in #783.
