### ISSUE TITLE
GET /swaps/rfc003/:id does not return transaction IDs

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#777]
`GET /swaps/rfc003/:id` should return transactions IDs but is instead returning transaction objects. This could be solved in several ways:
1. Storing `Ledger::TxId`s instead of `Ledger::Transaction`s in the storage layer.
2. Implementing the serialization of these transactions so that it returns the transaction ID.
3. Implementing `Into<TxId> for Transaction` for all (`Transaction`, `TxId`) pairs and adding the corresponding trait bound on the `Ledger` trait.

**Comment by D4nte** [comment]
Shouldn't this be blocked on #763 ?

**Comment by thomaseizinger** [comment]
> Shouldn't this be blocked on #763 ?

For the TX that are already returned it is not blocked and a solution very likely will just work for the others once #763 is resolved.

**Comment by luckysori** [comment]
Resolved with #785.
