### ISSUE TITLE
Make debugging of JS tests easier

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#791]
1. If you want to run a comit_node yourself (e.g. with debugging breaking point) for a e2e test or dry test then it's a pain.
2. If you only want to run a specific test (ie, one dry test) then it's also a pain

Note:
- Maybe environment variable would be best solution
- Mocha allows you to choose specific tests -> document it
- Somehow relates to #767

DoD:
- [ ] As a developer, I want to be able to run a test against a comit_node/btsieve/docker container that I started myself (e.g. I attached my comit_node to a debugger), without having to change JS code.
- [ ] As a developer, I want to be able to run a specific dry test file/suite of test without doing a JS code change

**Comment by bonomat** [comment]
Closing this in favor of #985 and moving the DoD into the other ticket.
