### ISSUE TITLE
Allow requests from localhost + any port

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#825]
With #821, the comit node only allows requests from `localhost:3000`. This is better than allowing requests from any origin as [pointed out](https://github.com/comit-network/comit-rs/pull/821#pullrequestreview-217066853) by @bonomat, but it would be preferable to allow requests from `localhost` plus any port.

Blocked by seanmonstar/warp#196.

**Comment by D4nte** [comment]
Let's close it for now. May need to look at alternative solutions if appdevs complain.
