### ISSUE TITLE
Improve the API of bitcoin::TransactionQuery for matching against the what is currently called "unlock_script"

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#826]
## Problem

The TransactionQuery for Bitcoin currently accepts an `unlock_script` parameter:

https://github.com/comit-network/comit-rs/blob/97a7d6844184cc570d91e3e52e85f5bb0cabc545/btsieve/src/bitcoin/queries/transaction.rs#L5-L10

This matches the `witness`, or more accurately `txinwitness`, representation in bitcoind and rust-bitcoin. However, it does not fit the purpose for `scriptSig`.

<details>
<summary>Bitcoind txinwitness vs scriptSig</summary>
<pre>
"txinwitness": [
    "304402205fd92596692256d9c96908ec06a044afbe90408def0b840195228186c79eef780220348a68cd837b29792c1286206b004b8f8d306ed4b568f7fe718a48e442a58ff601",
    "03783cad3424ef6533b31f18620913e53e9bf197b18d2d7bfc21b0c3e0cd5f161f",
    "",
    "6382012088a82072eec6b82abefbbfd0e5da7660332ee67ed8527bc76377eb6b71924183ed9e4e8876a914db5492464dcd98dd8ad4e1e4a02e262aa47df47b6704ce3f985cb17576a9149329064a13c76e1d593b37db9c3c966d76ffb7e46888ac"
],
</pre>

<pre>
"scriptSig": {
    "asm": "3046022100b4251ecd63778a3dde0155abe4cd162947620ae9ee45a874353551092325b116022100db307baf4ff3781ec520bd18f387948cedd15dc27bafe17c894b0fe6ffffcafa01 03091137f3ef23f4acfc19a5953a68b2074fae942ad3563ef28c33b0cac9a93adc",
    "hex": "493046022100b4251ecd63778a3dde0155abe4cd162947620ae9ee45a874353551092325b116022100db307baf4ff3781ec520bd18f387948cedd15dc27bafe17c894b0fe6ffffcafa012103091137f3ef23f4acfc19a5953a68b2074fae942ad3563ef28c33b0cac9a93adc"
},
</pre>

</details>

`scriptSig` if flatten whereas `txinwitness` contains an array of data to push (the `PUSH` opcode is implicit).

This means that currently, the matching on `scriptSig` does **not** work.

## Goal

Provide an API that is general enough for all our use cases but also not to narrow.

### 1. Separate the matching of witness script and sigScript in the API.

As both scripts are represented differently in rust-bitcoin and bitcoind, there is no value for btsieve to _homogeneous-ize_ their use. The API should provide different way to specify each script. The `scriptSig` matching should be dropped until needs be. The `unlock_script` should be renamed to `txinwitness`.

### 2. Make the API more restrictive

Currently, the query match go through all elements of the first level array and check that each element is present (in any position) in the `txinwitness` of a candidate transaction.

Instead, the use should provide the full expected `txinwitness` to the API and a full match should be done.
Because not all elements may be known in advance (Such as signature) then the user should be allow to put `null` as an element to express the fact that an element is expected to be there but no matching should be done.

Example:
```
"txinwitness": [
    null,
    null
    "",
	"6382012088a82072eec6b82abefbbfd0e5da7660332ee67ed8527bc76377eb6b71924183ed9e4e8876a914db5492464dcd98dd8ad4e1e4a02e262aa47df47b6704ce3f985cb17576a9149329064a13c76e1d593b37db9c3c966d76ffb7e46888ac"
],
```
Would match a transaction that has the following `txinwitness`:
```
[
    "304402205fd92596692256d9c96908ec06a044afbe90408def0b840195228186c79eef780220348a68cd837b29792c1286206b004b8f8d306ed4b568f7fe718a48e442a58ff601",
    "03783cad3424ef6533b31f18620913e53e9bf197b18d2d7bfc21b0c3e0cd5f161f",
    "",
   "6382012088a82072eec6b82abefbbfd0e5da7660332ee67ed8527bc76377eb6b71924183ed9e4e8876a914db5492464dcd98dd8ad4e1e4a02e262aa47df47b6704ce3f985cb17576a9149329064a13c76e1d593b37db9c3c966d76ffb7e46888ac"
],
```

ie, use `Option<Vec<Option<Vec<u8>>>>` for the `txinwitness`.

**Comment by thomaseizinger** [comment]
Needs to be refined after https://github.com/comit-network/comit-rs/issues/1350.

**Comment by thomaseizinger** [comment]
Should be covered as part of https://github.com/comit-network/comit-rs/issues/1781.
