### ISSUE TITLE
Ethereum `SendTransaction` action should be `CallContract`

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#835]
Our `SendTransaction` action should actually be called `CallContract`.

https://github.com/comit-network/comit-rs/blob/f85842f5ccbfd6348d04275490d838655c416b3a/application/comit_node/src/swap_protocols/rfc003/ethereum/actions.rs#L18-L25

https://github.com/comit-network/comit-rs/blob/f85842f5ccbfd6348d04275490d838655c416b3a/application/comit_node/src/http_api/routes/rfc003/handlers/get_action.rs#L234-L261

As part of that, the `amount` field should be removed since it is always set to zero and then unnecessarily returned to the user. The user should never send any Ether to an HTLC when invoking them. We should prevent that by not even suggesting that there might be an amount.

DoD:
- [ ] rename `SendTransaction` to `CallContract`
- [ ] remove `amount` field from `CallContract`
- [ ] update http API action type from `ethereum-invoke-contract` to `ethereum-call-contract`

**Comment by LLFourn** [comment]
I'm not sure about this. Wouldn't calling an ERC20 function like `transfer` also be "InvokeContract"? But in this case we may like to specify the method they are calling and an array of arguments (rather than a data blob).

**Comment by thomaseizinger** [comment]
> Wouldn't calling an ERC20 function like transfer also be "InvokeContract"?

Maybe.

> But in this case we may like to specify the method they are calling and an array of arguments (rather than a data blob).

At the moment, we specify a data blob.

I think it would be the job of the UI to detect that a transaction invokes a certain function and present it to the user nicely instead of us specifying that and relying on the UI to send the right transaction.

This issue was mainly opened because `amount` is always 0 and I cannot think of a use case where we want the user to invoke a contract and have them send ether to it.
