### ISSUE TITLE
Create new repository for HTLCs

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#839]
Extract HTLC generation from comit-rs into own repository including tests. 

DoD: 
* One private new repository for all HTLCs in coblox
* Tests are running
* Some way to get offsets and full hex for particular HTLC (see table in RFCs)
* Compare with RFCs (and update the latter one if needed)
* Make offsets in RFCs: start index inclusive and end index exclusive

**Comment by D4nte** [comment]
Already tracked with #606
