### ISSUE TITLE
Links should use extension relation type

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#843]
After #842, the body of the response to `GET /swaps` and `GET /swaps/rfc003/:id` contains a link to the specification of the protocol used in the swap (currently only [RFC003](https://github.com/comit-network/RFCs/blob/master/RFC-003-SWAP-Basic.md)):

https://github.com/comit-network/comit-rs/blob/16e59ffd61a8997acb7546f4b34e3734b0a10b0c/application/comit_node/src/http_api/swap_resource.rs#L123-L130

The link relation used, `human-protocol-spec`, is neither a registered relation type, nor an extension relation type. Looking through the list of [registered relation types](https://www.iana.org/assignments/link-relations/link-relations.xhtml), nothing appears to match our use case. We should therefore replace the current link relation with an extension relation type, which should be a valid `URI`, as described in the [Web Linking RFC](https://tools.ietf.org/html/rfc8288#section-2.1.2). This `URI` would have to point to a page where our custom link relation is described.

This applies to all link relations that are used in our API.

Before:
```
{
   "human-protocol-spec": {
      "href": ".../RFC.md"
   }
}
```

After:

```
{
   "http://url-to-documentation/.../human-protocol-spec": {
      "href": ".../RFC.md"
   }
}
```

This can only be done when some API documentation for comit-rs is published.

**Comment by thomaseizinger** [comment]
Could also rename it to something more obvious like "protocol-rfc".

**Comment by thomaseizinger** [comment]
Obsoleted by https://github.com/comit-network/comit-rs/issues/1559.
