### ISSUE TITLE
Improve homogenous naming in comit_node http api

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#845]
~In the HTTP API response we have:~
~- Communication status: `SCREAMING_SNAKE_CASE` (e.g. `ACCEPTED`)~
~- Asset status: `PascalCase` (e.g. `Funded`)~
~- Most field names: `snake_case` (e.g `alpha_asset`)~
~- Action types: `kebab-case` (e.g. `ethereum-invoke-contract`)~

~This is messy I'd suggest to have everything one way: `kebab-case`.~

~Also, may want to consider the GET parameters (e.g. `fee_per_bytes`).~

Change `ledger status` to `SCREAMING_SNAKE_CASE`.

**Comment by thomaseizinger** [comment]
The only inconsistency I can see is in the naming of the status fields. Those should definitely be unified. To me, SCREAMING_SNAKE_CASE is the most appealing for fields that indicate a kind of status.

`snake_case` field names are per Rust convention. We could think of serializing those fields as `camelCase`, which would be more idiomatic for JSON. After all, API consumers should not care which language we are using to develop our COMIT node.

> Action types: kebab-case (e.g. ethereum-invoke-contract)

Changing those I am not so sure about, all other casing looks kinda off IMO.

**Comment by D4nte** [comment]
I love how your comment agrees with this issue while looking like you disagree with the issue.

**Comment by thomaseizinger** [comment]
> I love how your comment agrees with this issue while looking like you disagree with the issue.

😅
I wasn't sure if you were implying that all the different uses of cases should be aligned. It sounded like that, so I expressed my disagreement with that.
I am glad that it just seemed to be a misunderstanding :)
