### ISSUE TITLE
Take direct control of deserialization in HTTP API

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#859]
## Problem

In order to _deserialize_ the incoming SWAP request into generic structs that implement `Ledger` and `Asset`, the HTTP layer makes use of a combination of `#[serde(with ...)]` attributes and the intermediate representations `HttpLedger` and `HttpAsset`.

https://github.com/comit-network/comit-rs/blob/073a335f0cf27d35c7a59305d8f60282aa289329/application/comit_node/src/http_api/routes/rfc003/handlers/post_swap.rs#L84-L99

Not only does this involve a lot of code but the indirection makes it hard to reason about how the deserialization actually works.

## Goal

Simpler code.

## Recommendation

#785 introduced a generic struct `Http<I>(I)` to control the serialization of types in the `Http` context. This works by doing `impl Serialize for Http<FooBar> {}`. Since `Http` is a type local to the crate (comit-rs), we can implement `Serialize` (a foreign trait) for a possibly foreign type (`FooBar`).

The same idea should be applicable to _deserialization_ by doing `impl Deserialize for Http<FooBar>`.

Definition of Done:

- [ ] There are no more `#[serde(with ... )]` attributes for deserializing assets and ledgers
- [ ] `HttpAsset` and `HttpLedger` are gone
- [ ] Deserialization of all `Ledger` and `Asset` types are controlled through implementations of `Deserialize` on `Http<...>`
- [ ] `Ledger` and `Asset` implementations __do not__ implement `Deserialize`.
- [ ] unit tests explicitly show/test all deserialization.

**Comment by bonomat** [comment]
@luckysori : please refine this.

**Comment by thomaseizinger** [comment]
Resolved in https://github.com/comit-network/comit-rs/pull/1723.
