### ISSUE TITLE
Migrate comit-rs to Circle CI

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#863]
Remove Travis configuration file and Make Circle CI successful build a mandatory requirement.

DoD:
- [x] Check Travis subscription model
- [x] Update mergify config
- [x] Remove .travis.yml file
- [ ] Make Circle CI Successful build check mandatory to merge PR in GitHub
- [x] Create issue to track the testcontainer optimisation discussed below
- [ ] Slack integration

**Comment by thomaseizinger** [comment]
Travis cannot test on MacOS because docker is not available there.

**Comment by D4nte** [comment]
What is blocking this ticket? :) "good first issue"?

**Comment by bonomat** [comment]
Nothing really, I have a working version in here #942 .

**Comment by D4nte** [comment]
I thought there was a dependency on a test_containers change. @thomaseizinger could you create an issue to track the testcontainers change.
I suggest we keep this one in mind for the next sprint.

**Comment by thomaseizinger** [comment]
> @thomaseizinger could you create an issue to track the testcontainers change.

Done: https://github.com/testcontainers/testcontainers-rs/issues/89

**Comment by bonomat** [comment]
Even with the non-optimzed setup, CircleCI has a better performance than Travis. 

* https://circleci.com/gh/comit-network: ~12 minutes
* https://travis-ci.com/comit-network/comit-rs/builds: ~20 minutes

I would opt for migrate over to CircleCI now and invest some time into testcontainers/testcontainers-rs#89 to get an even better performance.

**Comment by D4nte** [comment]
Yes go for it.
