### ISSUE TITLE
Create commandline interface for comit-rs and btsieve

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#876]
Create a CLI for the comit-node and btsieve to customize the location of the configuration file. 

The go-to library for creating CLIs in Rust is [structopt](https://crates.io/crates/structopt).

DoD: 
- [x] cli for comit_node
- [x] cli for btsieve

**Comment by D4nte** [comment]
Is that part of an Epic or something?

**Comment by thomaseizinger** [comment]
Nope, it is just an issue by itself. We created it to get rid of a TODO that was in the code for way too long :)

**Comment by bonomat** [comment]
Description updated to reflect the need of a CLI for btsieve as well. 
CLI for comit_node was done in #966.

**Comment by D4nte** [comment]
done with #966 and #973

**Comment by luckysori** [comment]
And here I was thinking that you had added a full-blown CLI for comit_node and btsieve overnight :laughing:

**Comment by D4nte** [comment]
@luckysori full blown it is :)
