### ISSUE TITLE
Allow ip to be specified in swap request

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#883]
Currently, our implementation of libp2p relies on `mDNS` to discover the other node so that we can talk to it. This only works on the local network though. Obviously, we also want to be able to connect to nodes outside of our local network. 

We only provide the peer-ID in the HTTP API, meaning it's the node's responsibility to figure out an address to connect to.
We could add a different endpoint that allows us to connect to a specific peer. It would very likely also be helpful to specify boot-nodes to aid the discovery process.

Further, likely useful information:

- rust-libp2p provides a Kadmelia implementation (which is a DHT)
- substrate has a `NetworkBehaviour` that does random DHT queries to discover peers 
- libp2p provides an `Identify` behaviour that standardizes how nodes identify each other. Through such identifications, nodes exchange the protocols they speak + under which IPs they are reachable. Nodes can also ask each other for information about a 3rd node through this mechanism.
- It seems like WebRTCStar is not yet implemented in rust-libp2p. I think that one would help us a lot in connecting to other nodes.

---
DoD:
Update the POST `swaps` API to allow `id+multiaddress` for the peer property.
The comit_node would then connect to the multiaddress and queue the request for the given id.
If the id of the given address does not match then the swap request will never be sent.
The link format should also be updated to accept the following format: `peer=<id>[@multiaddress]`

- [x] Update POST swaps endpoint to accept both `id` or `{id, address}` (enum) for peer field
- [x] libp2p to connect to peer based on ip
- [x] queue up the swap request against the given id (could be done at the same time than connection)
- [x] peer shows up in `/peers' endpoint
- [x] create comit-i issue to track changes including link update comit-network/comit-i#68

**Comment by D4nte** [comment]
Go for hardware solution for the demo

**Comment by D4nte** [comment]
Resolved with #1002
