### ISSUE TITLE
Self-descriptive API for comit-rs

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#892]
Motivation: minimizing the changes to be done to comit-i when adding (in priority) a new asset, ledger or protocol.

This will of course also impact how easy bobtimus can be implemented.

---

Yet to be tracked/groomed:
- [ ] include ledgerspecs in comit-rs http api and use it in comit-i
- [ ] return protocol parameters that would allow to dynamically generate the form for POST create swap

**Comment by thomaseizinger** [comment]
I'll un-assign myself from this since the initial list is already created and we groomed the tickets.

**Comment by D4nte** [comment]
@D4nte to create the new issues for remaining check boxes to be then discussed in grooming
