### ISSUE TITLE
Test Ethereum contracts built on RFC offset

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#896]
In `blockchain_contracts` crate, the contract hex are generated from assembly code and then tested against full nodes.

Instead, such contracts should be generated using the offset described in the RFC.

See https://github.com/comit-network/comit-rs/pull/887#discussion_r279236004

One crate, soon to be in own repo, (blockchain_contracts) will contain:
- bin to generate offsets (for rfc) dynamically based on placeholders
- lib to generate htlcs from offsets (to be used by comit_node). Offsets are static in the code.
- tests that tests the lib

DoD:
- [ ] Do it for Ether
- [ ] Do it for ERC20

**Comment by da-kami** [comment]
closing because github did not do it automatically
