### ISSUE TITLE
Limit dependabot issues to 3

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#903]
try to limit dependabot issues to 3 via the config file.

**Comment by D4nte** [comment]
It is not available in the config file: https://dependabot.com/docs/config-file/
The config file is per repo. For comit-rs the `.dependabot/config.yml` file is overriding the configuration.
However, this parameter is at organisation level (comit-network) and it is already setup to 3:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/300805/57828687-ac1d4800-77ef-11e9-891b-002097e3c8bf.png">

**Comment by bonomat** [comment]
Well then, I guess we can close this issue.

**Comment by LLFourn** [comment]
I guess I'll close it then!
