### ISSUE TITLE
Move /swaps and /swaps/rfc003/:id from hal to siren

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#904]
https://github.com/kevinswiber/siren

DoD:
- [ ] Move `/swaps` from hal to siren and minimally change the tests
- [ ] Move `/swaps/rfc003/:id` from hal to siren and minimally change the tests
- [ ] Write a test that automatically verify the API against siren schema

Note:
Do not embed the actions in the new API just yet

**Comment by thomaseizinger** [comment]
Resolved in #952.
