### ISSUE TITLE
Typescript definitions for `cnd` REST API payloads

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#906]
Use the `siren` JSON schema and the ones in the e2e test suite to create an npm package that contains typescript definitions for all the payloads we have in our API.

Library name: `cnd-api-types`
Do research on what the best version is to release this under given our situation (API might change).

DoD:
- There is a library on `npmjs.com` that we can import into `comit-i`, `bobtimus` and in the e2e tests.
- Use them in the e2e tests
- Remove typescript definition generation from schema from the build process
- Create issues to use library in `bobtimus` and `comit-i`

**Comment by thomaseizinger** [comment]
Moved back to `New` to re-groom.

**Comment by thomaseizinger** [comment]
Obsolete with the new sdk.
