### ISSUE TITLE
Implement create swap for Lightning on Alice (deser)

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#912]
New endpoint is needed for lightning swaps (alpha ledger only): `/swaps/rfc012`.

To deserialize the polymorphic JSON messages, attempt to not use untagged enum (that does not tells you why a message failed to deserialize).

Focus on deserialization.
Storage is not part of the scope.
No message is sent to Bob at this stage.

DoD:
- [ ] Can create Lightning Swap on Alice (returns `200 OK`, deserialization has happened)

**Comment by bonomat** [comment]
Closing this even though we want it in the long run.
