### ISSUE TITLE
Forward lightning swap request to Bob

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#914]
Lightning Alpha Ledger only.

Alice forwards lightning swap request to Bob over BAM. Bob reject the request (unknown protocol).

Note:
pair program.
Experiment with a different design than state machine for protocol execution.

DoD:
- [ ] Forward swap request to Bob when creating it and Bob reject it (automatic because error)
- [ ] Alice needs to mark the swap as rejected once Bob replies (`/swaps`)

**Comment by bonomat** [comment]
Closing this even though we want it in the long run.
