### ISSUE TITLE
Try to setup up COMIT node from scratch

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#919]
The goal is that comit can be setup "easily".

Installing from source is ok.
This includes full node setup (ethereum and bitcoin), we could provide docker images/docker-compose etc.
This includes btsieve and comit_node.
comit-i should be accessible.
Blockchain network target is regtest.

DoD:
- [ ] Setup comit-rs from scratch including full nodes & create skeleton document of steps
- [ ] Identify what is cumbersome to setup & open tickets
- [ ] Create documentation targeting techie users

**Comment by LLFourn** [comment]
Renamed because it has the same name as the epic which is confusing
