### ISSUE TITLE
Align provisioning of Bitcoin and Ethereum identities

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#920]
## Problem

1. The Ethereum identity has to be provided upfront whereas the Bitcoin identity has to be provided at redeem/refund time: This means some exception has to be handled, see `additionalIdentities` function in #1584.
2. Providing the Bitcoin identity is done via `GET` parameters which is extra code to build such query whereas all other info are encoded JSON when doing the `POST` swap request.

## Goal

Make it faster for a developer to build their own COMIT app.

## Recommendation

Add Bitcoin identities to the `POST` swap request API, remove them from the GET API.

----
~Do not embed final identities in Ethereum HTLCs~
~Using the findings of comit-network/RFCs#40~

DoD:
- [ ] ~When creating a SWAP request, final Ethereum identities are not needed~
- [ ] ~When redeeming/refunding Ethereum swap, identity must be passed~
- [ ] ~Update the Ether and ERC20 HTLC as per the spike~
- [ ] ~Create issue to update comit-i~

~Note:~
~Expect lots of code removal.~

**Comment by luckysori** [comment]
To-refine: is this still needed given the changes to the SDK, @D4nte?

**Comment by D4nte** [comment]
> To-refine: is this still needed given the changes to the SDK, @D4nte?

Why refine? Yes, still needed.

**Comment by luckysori** [comment]
Closed for now since the SDK does actually relieve this pain.
