### ISSUE TITLE
Revise libp2p implementation to use one substream per message

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#923]
Currently, the implementation of libp2p added in #800 only uses one substream for the whole communication. This is [advised against](https://github.com/libp2p/rust-libp2p/issues/1058#issuecomment-483244002) by the rust-libp2p team.

Instead, we should open one substream per request that is sent. It is at this stage unclear, on how we would actually implement that. Here are some thoughts though:

- Instead of _replacing_ the current substream with a new one upon injection, we need to store it (probably an unbounded channel)
- When we want to send something, try to get a substream from the channel current streams and use it to send a single item. If we can't get one, send out a new SubstreamRequest
- Always poll on all streams until they are closed (?)

Implementing this might resolve the issue described in #922.

This should also clean up the race condition present here:

https://github.com/comit-network/comit-rs/blob/e832d9cc3b90aa79dadb65f782f80d2f722cfed4/application/comit_node/src/libp2p_bam/handler.rs#L201-L209

where, as soon as the connection ends, both nodes will try to reconnect to each other.

**Comment by thomaseizinger** [comment]
I had a closer look at how substrate does things + how the `OneshotHandler` in `libp2p-core` works. Here are my findings:

- Substrate currently doesn't use on substream per message BUT it keeps all substreams it received and tracks which of them are active. As soon as there are no more active ones, the state changes to `Disconnected`. The ProtocolHandler always uses the __first__ substream for sending events.
- The `OneshotHandler` is interesting! Through the trait bounds given on the `ProtocolHandler` implementation, I could deduce that the `InboundUpgrade` and `OutboundUpgrade` implementations are expected to only send one message and then close the substream (the link shows the `Ping` protocol, which uses the `OneshotHandler`)

https://github.com/libp2p/rust-libp2p/blob/808a7a5ef6ae6cac55971ee234714fbdfb7b7d84/protocols/ping/src/protocol.rs#L79-L86

This would mean our implementation of `OutboundUpgrade` (which is currently done in  `BamConfig`)

https://github.com/comit-network/comit-rs/blob/8c13d15e18ba4c68b4d655741876b582bcba5c21/application/comit_node/src/libp2p_bam/protocol.rs#L42-L55

would have to have the instance of the `Frame` in there which we want to send and employ the same pattern as in the `Ping` implementation (close the stream after the message is sent).

This should allow us to use the `OneshotHandler` implementation.

**Comment by D4nte** [comment]
How does this fit into the paragdim of not using bam to have a frame id if a substream is re-use for several requests?

**Comment by thomaseizinger** [comment]
> How does this fit into the paradigm of not using bam to have a frame id if a substream is re-use for several requests?

This was just me writing down findings related to this topic.

I went for a different solution eventually.

**Comment by thomaseizinger** [comment]
Resolved as part of #944.
