### ISSUE TITLE
Network connection via libp2p sometimes fails because it connects to the wrong address

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#925]
Note: Bug originally perceived by @D4nte.

The connection to the other node sometimes fails because we are trying to connect via an external address (if connected to VPN for example).

I believe, this has to do with the order in which we return the addresses here:

https://github.com/comit-network/comit-rs/blob/0e787c9e9c1c856e2f686be9bc55a2fd847f2f71/application/comit_node/src/libp2p_bam/behaviour.rs#L131-L140

Needs further investigation:

1. if this is the source of the perceived bug
2. what the correct/expected order is

**Comment by bonomat** [comment]
@D4nte try to reproduce this please.

**Comment by D4nte** [comment]
`cargo make e2e` passes on Mac OS with vpn on.
