### ISSUE TITLE
Update slack notifications for Travis to be only sent for `master` branch

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#934]

**Comment by thomaseizinger** [comment]
Having discussed this with @D4nte, we actually like it the way it currently is (for PRs as-well).

Thoughts @bonomat @LLFourn @da-kami @luckysori ?

**Comment by luckysori** [comment]
I like it for PRs too!

**Comment by bonomat** [comment]
I'm happy if it stays but can adapt if it doesn't. Up to you guys ;)

**Comment by thomaseizinger** [comment]
Let's leave it as it is then!

Can re-open this ticket at any point :)
