### ISSUE TITLE
comit-rs does not set CORS headers for error responses

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#935]
I just got an unexpected error in comit-i:
When sending an invalid request to the comit-node, I received: 

`Access to XMLHttpRequest at 'http://localhost:8000/swaps/rfc003' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.` 

This means, the comit-node did not include the corresponding CORS header in the error response.

Since we are using the cors-module from `warp`, this is very likely an issue with `warp` and has to be fixed upstream.

Tasks:
- figure out if it is an upstream bug -> open a warp issue
- try to fix it in warp otherwise patch comit-rs
- make a dry-test

**Comment by thomaseizinger** [comment]
Resolved in #1001.
