### ISSUE TITLE
comit-i API port injection when served by the comit node

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#945]
**Problem:** 
When comit-i is served by the comit_node, the port for the comit_node API within comit-i does not reflect the configuration of the comit_node but is always set to the default port `8000`.

**Solution (comit-rs part)**
Fetch a script at a new configuration endpoint that contains a function that returns the API port as set in the comit node configuration. 

1. add endpoint that serves the script (Content-Type `application/javascript`)
2. template for script (code for the function)
3. inject the API port from the configuration into the function code upon startup of the comit node.

prerequisite for: https://github.com/comit-network/comit-i/issues/52

**Comment by D4nte** [comment]
Should this be part of the `Simple Setup` epic? Should we create such epic?

**Comment by D4nte** [comment]
Done with #974
