### ISSUE TITLE
Improve the comit-rs configuration handling

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#947]
**Current situation:**
Currently the configuration for the `comit_node` and `btsieve`  has to be placed in `~/.config/comit_node/default.toml`.

Additionally the path to the `default.toml` file can be changed through the `COMIT_NODE_CONFIG_PATH` and `BTSIEVE_CONFIG_PATH` environment variable. However, currently only the path can be set there. The file name always has to be `default.toml` which is weird. 

Additionally the error messages should be improved.

**Improvement Proposal:**
1. _Command line parameter for config:_ Add command line parameter `--config` that accepts a file-path to a configuration file. 
1. _Treat `default` as fall back:_ Try to fall back to a `default.toml` file in a directory where a specific configuration file cannot be found. 
2. _Allow file-path instead of just folder-path:_ Change the environment variable handling so one can pass a complete file-path (not only folder). If there is only a folder provided the fallback mechanism should try yo load the `default.toml`.

**Improvement Proposal for error message**:

current (when configuration file cannot be found):
```
Error: configuration file "/Users/dakami/.config/comit_node/default" not found
```
change (add file extension):
```
Error: configuration file "/Users/dakami/.config/comit_node/default.toml" not found
```

current (when configuration parameter is missing in the specified configuration file):
```
Error: missing field `comit`
``` 
change (add configuration file)
```
Error: missing configuration entry `comit` in [name_of_loaded_config_file].toml
``` 

Related to: https://github.com/comit-network/comit-rs/issues/919

---

Tasks:

- comit_node: Change the path of the config file to: "$HOME/.config/comit/comit_node.toml"
- btsieve: Same thing but btsieve.toml
- try to improve the error message as per Daniel's suggestion (full path + extension) above
- prevent config-rs to look for a configuration file named "development.toml" based on the run environment
- there should also be no fallback mechanism for config files

**Comment by thomaseizinger** [comment]
Some more information on this:

> However, currently only the path can be set there. The file name always has to be default.toml which is weird.

This originates from the config library we are using: https://github.com/mehcode/config-rs

> Allow file-path instead of just folder-path: Change the environment variable handling so one can pass a complete file-path (not only folder). If there is only a folder provided the fallback mechanism should try yo load the default.toml.

Same as above.

> Command line parameter for config: Add command line parameter --config that accepts a file-path to a configuration file.

There is another ticket here: https://github.com/comit-network/comit-rs/issues/876

**Comment by D4nte** [comment]
> This originates from the config library we are using: [mehcode/config-rs](https://github.com/mehcode/config-rs)

I suggest we look at a different library. This `default.toml` always bugged me.
