### ISSUE TITLE
Remove secret seed from configuration

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#948]
The secret seed comes from the user and should not be in the configuration file of the `comit_node` (a default secret seed would not make much sense...). Instead, a pem file should be used.

Take a look at @LLFourn thoughts: https://github.com/comit-network/spikes/blob/master/0007-secret-seed-storage-and-key-derivation.md

As per the spike, no need to encrypt for now.

Related to: https://github.com/comit-network/comit-rs/issues/919

**Comment by thomaseizinger** [comment]
If we want to encrypt the secret seed, we may want to use something like this: https://docs.rs/pwbox/0.2.1/pwbox/

**Comment by D4nte** [comment]
So, should it be encrypted or not? #refine
