### ISSUE TITLE
Write a configuration file with default values to the default config path if none is found at startup

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#962]
Currently, the comit_node fails when there is no config file provided.
Resolution as per title.

DoD:
- can start comit node without config file
- comit_node emits an informative line stating the path where the config was generated

Note: This includes generating a seed.

**Comment by bonomat** [comment]
The ticket states that the comit_node should start even without a provided config file, however I see three possibilities:

1) comit_node was started with `--config /file/does/exists/` --> All good, let's do some swaps.
2) comit_node was started with `--config /file/does/not/exists/` --> Config file not found
3) comit_node was started without `--config` 

Case 1) is not relevant, but what about 2)+3)? 
Imho: 
@2) if `--config` was provided, but the file does not exist, then comit_node should not start up but print a nice error message. Otherwise a typo might endup in an unwanted config file somewhere in your path
@3) if `--config` was not provided, then we should generate a file in the default location with a default setup and start up. 

What does @comit-network/rust-devs think about this?

**Comment by D4nte** [comment]
> The ticket states that the comit_node should start even without a provided config file, however I see three possibilities:
> 
>     1. comit_node was started with `--config /file/does/exists/` --> All good, let's do some swaps.
> 
>     2. comit_node was started with `--config /file/does/not/exists/` --> Config file not found
> 
>     3. comit_node was started without `--config`
> 
> 
> Case 1) is not relevant, but what about 2)+3)?
> Imho:
> @2) if `--config` was provided, but the file does not exist, then comit_node should not start up but print a nice error message. Otherwise a typo might endup in an unwanted config file somewhere in your path
> @3) if `--config` was not provided, then we should generate a file in the default location with a default setup and start up.
> 
> What does @comit-network/rust-devs think about this?

I understand your point, if the user provides `--config` to an non-existing file then most likely you want to error out because the user is likely to have made a mistake.

But you also want to make it user friendly, hence if there is no `--config` and no file in the home then you want to generate it.

I think the proposal is fine.

An alternative would be to ask the user to make it explicit when they want files to be auto-generated with a specific option `--gen-config` but I don't think we should do that.

**Comment by D4nte** [comment]
> The ticket states that the comit_node should start even without a provided config file, however I see three possibilities:
> 
>     1. comit_node was started with `--config /file/does/exists/` --> All good, let's do some swaps.
> 
>     2. comit_node was started with `--config /file/does/not/exists/` --> Config file not found
> 
>     3. comit_node was started without `--config`
> 
> 
> Case 1) is not relevant, but what about 2)+3)?
> Imho:
> @2) if `--config` was provided, but the file does not exist, then comit_node should not start up but print a nice error message. Otherwise a typo might endup in an unwanted config file somewhere in your path
> @3) if `--config` was not provided, then we should generate a file in the default location with a default setup and start up.
> 
> What does @comit-network/rust-devs think about this?

I understand your point, if the user provides `--config` to an non-existing file then most likely you want to error out because the user is likely to have made a mistake.

But you also want to make it user friendly, hence if there is no `--config` and no file in the home then you want to generate it.

I think the proposal is fine.

An alternative would be to ask the user to make it explicit when they want files to be auto-generated with a specific option `--gen-config` but I don't think we should do that.

**Comment by thomaseizinger** [comment]
> And now that I wrote my opinion I'd like to invite you to push this ticket to the "New" pipeline so we can discuss/re-groom Monday :)

It is already in the sprint, I think it is fine to clarify some things before their implemented but it looks like we are not grooming our issues well enough :)

> @2) if --config was provided, but the file does not exist, then comit_node should not start up but print a nice error message. Otherwise a typo might endup in an unwanted config file somewhere in your path

I like this.

> @3) if --config was not provided, then we should generate a file in the default location with a default setup and start up.

Just to clarify, this is how I understood it: if `--config` is not provided AND there is no config file in the default path, we generate one and startup (with a message that we generated one!)

**Comment by bonomat** [comment]
Ok, I think we are on the same page here. 
Moving forward with implementing as proposed, i.e. a config will only be generated if `--config` was not provided.
