### ISSUE TITLE
Test mDNS on Wifi

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#964]
Check that comit_node discover each others if they are on the same wifi.
Ideally test:
- [ ] S&C Wifi
- [ ] Hotspot (phone or laptop) Wifi
- [ ] With VPN activated

**Comment by da-kami** [comment]
@bonomat and me tried to connect via Stone&Chalk Wifi and phone- and mac-hotspot. Via the Wifi it worked randomly. Most of the time it did not. It is almost impossible to reproduce under which conditions it works. 

Locally (running 2 nodes on localhost) works.

**Comment by bonomat** [comment]
@thomaseizinger : I think this means we really need `connect-by-address`.

**Comment by D4nte** [comment]
Did you try to `telnet <philipp's ip> <comit_node libp2p port>` when it failed to confirm it would be possible to connect?

**Comment by da-kami** [comment]
Did try together with @thomaseizinger today again. Through Telnet we could see that the node is reachable, however sending a Swap was still not possible. So it seems the `libp2p` discovery is not working as expected.

**Comment by bonomat** [comment]
I guess it is clear, we will need another mechanism such as connect-by-ip and/or connect-by-id through with DHT lookup. 
Closing this as the implementation is covered in: #883
