### ISSUE TITLE
Revise e2e test framework

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#985]
Figure out what the problem is with our e2e tests!

- [x] Talk to @bonomat 
- [x] Talk to @thomaseizinger 
- [x] Talk to @da-kami 
- [x] Talk to @D4nte 
- [ ] Talk to @luckysori 
- [ ] Talk to @tcharding - Authored the spike https://github.com/comit-network/spikes/pull/25

Reported issues:
- As a developer, I want to be able to run a test against a comit_node/btsieve/docker container that I started myself (e.g. I attached my comit_node to a debugger), without having to change JS code.
- As a developer, I want to be able to run a specific dry test file/suite of test without doing a JS code change
- Decouple e2e test framework from mocha
> Currently, the e2e testing framework uses mocha primitives, such as it and describe to build up a test suite that executes the individual steps. This solution is sub-optimal for the following reasons:
> - mocha uses global state which makes it hard to trace, what the describe and it invocations will actually do
> - mocha needs a workaround for long-running setup tasks (as we need them for the erc20 test to deploy the contract) which requires calling run once the setup is done for mocha know that it can start executing the tests.
> - each step in a swap is its individual test (from a mocha perspective) whereas conceptually, doing one swap is a test
> We should revise the implementation so that the actual execution of a swap is not depending on mocha for executing (but for example just goes through a list of closures and runs them). Given that, it should be easy to use mocha to define tests like "btc-eth happy path swap" that uses above mentioned library to execute the swap.

- We are actually missing a set of tests in our e2e test suite.
> That is, we don't have any tests that precisely assert the responses of the `comit_node`. Example of missing tests:
> - Is the `fund` action of a `Bitcoin <-> Ether` SWAP for Alice actually a `bitcoin-send-amount-to-address`?
> - Is the HTTP method of the `accept` action `POST`?

> Instead `actor.ts` and other parts are littered with assertions that are executed as we run through all of the e2e tests. Ideally, those things would be separated: Have a library that allows you to very easily declare a e2e test run in terms of actions and expected states and being able to precisely assert the state at any time. This would allow us to test more scenarios as we can simply combine assertions and steps in the way we like. At the moment, this is not possible as the e2e test framework always assumes happy-path (asserts HTTP status to be 200 for example)
- It should be easier to call the tests from command line/ide.
> We should not relay on cargo make for that. One way to simplify would be to not use harness.ts as the executer but instead, it should be a library that is used in the test and the test are executed in the native way the test library (mocha, jest) expect you to execute tests
- Tests should run in parallel and be better self-contained.
> Similar to what we do with bobtimus and testcontainers for the blockchain dockers. However, we should not have to build a docker image for cnd and btsieve to run the tests. Most likely the harness should start a number of cnd and btsieve on different ports to allow parallel execution.
- Output useful information on test failure (when hitting timeout)
> At the moment, we rely on test timeouts at lot because most of our tests assert that the state advances at some point. For this timeout handling, we rely on `mocha`s `this.timeout` function that controls the timeout of a single test. If such a timeout is hit, all the test displays is `Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.`. That is not useful at all. Usually this occurs in our `waitUntil` step where we are waiting for a particular state. If such a timeout is hit, it would be useful if the test framework would dump the current state of the swap.
- Assert the number of expected tests (we already had a bug that missed out on some assertions)
- Assert the casing of JSON keys in all payloads (middleware?) https://github.com/comit-network/comit-rs/issues/1138

**Comment by bonomat** [comment]
Comment moved from #833: 

Currently, the e2e testing framework uses `mocha` primitives, such as `it` and `describe` to build up a test suite that executes the individual steps. This solution is sub-optimal for the following reasons:

- mocha uses global state which makes it hard to trace, what the `describe` and `it` invocations will actually do
- mocha needs a workaround for long-running setup tasks (as we need them for the erc20 test to deploy the contract) which requires calling `run` once the setup is done for mocha know that it can start executing the tests.
- each step in a swap is its individual test (from a mocha perspective) whereas conceptually, doing one swap is a test

We should revise the implementation so that the actual execution of a swap is not depending on mocha for executing (but for example just goes through a list of closures and runs them). Given that, it should be easy to use mocha to define tests like "btc-eth happy path swap" that uses above mentioned library to execute the swap.

**Comment by D4nte** [comment]
To me:
- It should be easier to call the tests from command line/ide. We should not relay on cargo make for that. One way to simplify would be to not use `harness.ts` as the executer but instead, it should be a library that is used in the test and the test are executed in the native way the test library (mocha, jest) expect you to execute tests
- Tests should run in parallel and be better self-contained. Similar to what we do with bobtimus and testcontainers for the blockchain dockers. However, we should not have to build a docker image for `cnd` and `btsieve` to run the tests. Most likely the harness should start a number of `cnd` and `btsieve` on different ports to allow parallel execution.
