### ISSUE TITLE
Contribute `Weight` back to rust-bitcoin

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#990]
We introduced a newtype for `Weight` to calculate the fee for a Bitcoin transaction more easily:

https://github.com/comit-network/comit-rs/blob/master/vendor/bitcoin_support/src/weight.rs

Once `rust-bitcoin` merges the `Amount` type, we should contribute this back to the repository as an effort for https://github.com/comit-network/comit-rs/issues/626.

Blocked on https://github.com/rust-bitcoin/rust-bitcoin/pull/252.

**Comment by da-kami** [comment]
The weight was removed from the code, thus closed.
