### ISSUE TITLE
Clients have to use heuristics to identify a response as a ledger action

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#992]
## Problem

Actions in the cnd API are self-descriptive. Hence, at the time of execution, client software doesn't care about how the action actually works (f.e. is it a POST request that has a side-effect or am I fetching data here?)

For some of our actions (for rfc003, that is fund/refund/deploy/redeem), we return a JSON object that we call "ledger action".
At the moment, clients have to use heuristics (like [here](https://github.com/comit-network/comit-rs/blob/a5c601847f5de17f225d232ed3432258b9774697/api_tests/lib/actor.ts#L118-L126) and [here](https://github.com/coblox/bobtimus/blob/e56e567ba16eb74e7e6a69c5b77224302b30e636/src/actionExecutor.ts#L42-L45)) to actually know that the response of executing an action _is_ a ledger action.

The underlying issue here is that we don't say in the response that it is a ledger action because the `content-type` is only `application/json`, which doesn't carry any semantic information.

As mentioned [here](https://github.com/comit-network/comit-rs/issues/992#issuecomment-577523932), this also hurts API evolution because we cannot make breaking changes to this set of actions.

If we would have a specific mediatype, we could version that one and allow clients to opt into the new format by specifying an `Accept` header, similarly to how we did it [here](https://github.com/comit-network/comit-rs/pull/1818/files).

## Goal

- Robust client / sdk implementations
- An unambiguous API

## Solution

Define a custom media type that describes ledger actions. For this, we will need to first figure out a _structure_ to use for custom mediatypes. This was originally [a separate issue](https://github.com/comit-network/comit-rs/issues/993) but can also simply be done as part of this.

Once we have said structure, we can simply use this new mediatype instead of `application/json` for those responses. Client implementations should be updated to remove the hacky heuristics and instead test for the new mediatype to decide on how to process the response from cnd.

**Comment by thomaseizinger** [comment]
Alternatively to ledger actions, we could also use `siren` for those responses and just use `ledger-action` in the root `class` field to unambiguously identify it as a ledger action.

**Comment by da-kami** [comment]
When doing the problem-goal-proposal workshop we were not really able to understand this ticket properly. Please refine *once you are back* @thomaseizinger

**Comment by thomaseizinger** [comment]
@da-kami I updated the issue description. If the gain is still unclear, please come and talk to me :)

**Comment by thomaseizinger** [comment]
I would like to re-open this.

Having a dedicated mediatype is useful as it helps with API evolution:

If we ever want to make breaking changes to this set of actions, not having a mediatype makes it impossible for clients to distinguish between the different versions.

**Comment by thomaseizinger** [comment]
Closing again to not clutter the board for now until priority of https://github.com/comit-network/comit-rs/issues/1925 is determined.

**Comment by thomaseizinger** [comment]
Doing this would also allow us to (eventually) document our API more efficiently as we can simply have a section that describes the mediatype and we can refer to it from other places then.
