### ISSUE TITLE
Figure out the structure to use in mediatypes within the comit_node API

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#993]
This spike is about identifying the structure to be used for custom mediatypes in the comit_node API.

For example here: https://github.com/comit-network/comit-rs/issues/992

The following questions need to be answered:

1. Which [tree](https://en.wikipedia.org/wiki/Media_type#Registration_trees) do our mediatypes go in?

2. Are the mediatypes specific to:

- comit-rs (the reference implementation)
- comit-nodes in general
- the comit-network

**Comment by da-kami** [comment]
We took a look at this in the problem-goal-proposal workshop and for us it is not clear what the added value is (goal). Why is it so important to come up with a structure to use in mediatypes? 😀

**Comment by thomaseizinger** [comment]
Closed after refining https://github.com/comit-network/comit-rs/issues/992
