### ISSUE TITLE
Activate libp2p DHT discovery

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#998]
**to be rediscussed**

DoD:
- [ ] Organise discussion meeting

---

This issue handles the always-on implementation.
#1007 tracks the ability to configure such implementation.

DoD:
- [ ] bootstrap to libp2p nodes for DHT connection (make configurable)
- [ ] use DHT for discovery (manual test with AWS machines with public ip)

**Comment by bonomat** [comment]
After talking to various people I have the strong feeling that privacy matters - a lot. We should discuss if we really want this feature. 
One thing we could look into is if libp2p, TOR and DHT can be used together (see coblox/spikes#8)

**Comment by D4nte** [comment]
Despite being opened the last, it seems that #1007 tracks this topic as more details have been provided in it.

**Comment by thomaseizinger** [comment]
> Despite being opened the last, it seems that #1007 tracks this topic as more details have been provided in it.

I thought this issue tracks the implementation and the other one tracks how various discovery elements are configured. I assumed an initial implementation is just "always-on" since that is the smallest, viable feature.

Given this issue is now closed, does this mean the initial implementation will include everything for the configuration aswell?

**Comment by D4nte** [comment]
> > Despite being opened the last, it seems that #1007 tracks this topic as more details have been provided in it.
> 
> I thought this issue tracks the implementation and the other one tracks how various discovery elements are configured. I assumed an initial implementation is just "always-on" since that is the smallest, viable feature.
> 
> Given this issue is now closed, does this mean the initial implementation will include everything for the configuration aswell?

We clearly need to be better at grooming issues... 
Happy to re-open.
This issue handles the _always-on_ implementation.
#1007 tracks the ability to configure such implementation.

**Comment by thomaseizinger** [comment]
Closed because we won't have a DHT anytime soon.
